Number_Properties_Priority = 2.0

Number_Properties = {
	dm_challenge_research_baseline = 4,
}

String_Properties_Priority = 2.0

String_Properties = {
	dm_carriersonly_build_restrict = "hgn_shipyard",
	dm_carriersonly_research_restrict = "MothershipHealthUpgrade1,MothershipMAXSPEEDUpgrade1,MothershipBUILDSPEEDUpgrade1,ShipyardHealthUpgrade1,ShipyardMAXSPEEDUpgrade1,ShipyardBUILDSPEEDUpgrade1",
	dm_carriersonly_research_grant = "CarrierHealthUpgrade1,CarrierMAXSPEEDUpgrade1,CarrierBUILDSPEEDUpgrade1",
	dm_nocruisers_build_restrict = "hgn_battlecruiser",
	dm_nocruisers_research_restrict = "BattlecruiserIonWeapons",
	dm_noplatforms_build_restrict = "Hgn_C_Module_PlatformControl,Hgn_MS_Module_PlatformControl",
	dm_noplatforms_research_restrict = "PlatformIonWeapons",
	generic_mp_ability_research_grant = "RepairAbility,ImprovedTorpedo,ScoutEMPAbility,ScoutPingAbility,AttackBomberImprovedBombs,HyperspaceCostUpgrade1,HyperspaceCostUpgrade2",
	generic_mp_health_misc_research_grant = "ResourceCollectorHealthUpgrade1,ResourceControllerHealthUpgrade1,GunTurretHealthUpgrade1,IonTurretHealthUpgrade1",
	generic_mp_speed_fighters_research_grant = "InterceptorMAXSPEEDUpgrade1,AttackBomberMAXSPEEDUpgrade1",
	generic_mp_speed_corvettes_research_grant = "AssaultCorvetteMAXSPEEDUpgrade1,PulsarCorvetteMAXSPEEDUpgrade1",
	generic_mp_speed_frigates_research_grant = "TorpedoFrigateMAXSPEEDUpgrade1,IonCannonFrigateMAXSPEEDUpgrade1,AssaultFrigateMAXSPEEDUpgrade1",
	generic_mp_speed_capitals_research_grant = "MothershipMAXSPEEDUpgrade1,CarrierMAXSPEEDUpgrade1,BattlecruiserMAXSPEEDUpgrade1,DestroyerMAXSPEEDUpgrade1",
	generic_mp_health_fighters_research_grant = "",
	generic_mp_health_corvettes_research_grant = "AssaultCorvetteHealthUpgrade1,PulsarCorvetteHealthUpgrade1",
	generic_mp_health_frigates_research_grant = "TorpedoFrigateHealthUpgrade1,IonCannonFrigateHealthUpgrade1,AssaultFrigateHealthUpgrade1",
	generic_mp_health_capitals_research_grant = "ShipyardHealthUpgrade1,CarrierHealthUpgrade1,MothershipHealthUpgrade1,BattlecruiserHealthUpgrade1,DestroyerHealthUpgrade1",
	generic_mp_buildspeed_research_grant = "ShipyardBUILDSPEEDUpgrade1,CarrierBUILDSPEEDUpgrade1,MothershipBUILDSPEEDUpgrade1",
	generic_mp_build_restrict = "Hgn_MS_Production_CorvetteMover,Kpr_Mover,Hgn_Shipyard_SPG",
	generic_mp_research_restrict = "AssaultCorvetteEliteWeaponUpgrade,AttackBomberEliteWeaponUpgrade,SensorsDowngrade1,SensorsDowngrade2,SensorsDowngrade3,SensorsBackToNormal1,SensorsBackToNormal2,SensorsBackToNormal3,MoverHealthDowngrade,MoverHealthUpgrade,FrigateHealthUpgradeSPGAME,DamageMoverTech,KeeperHealthUpgradeSPGAME_LOW,KeeperHealthUpgradeSPGAME_MED,KeeperHealthUpgradeSPGAME_HIGH,KeeperWeaponUpgradeSPGAME_M10_LVL_1,KeeperWeaponUpgradeSPGAME_M10_LVL_2,KeeperWeaponUpgradeSPGAME_M10_LVL_3,KeeperWeaponUpgradeSPGAME_M10_LVL_4,KeeperWeaponUpgradeSPGAME_M10_LVL_5,KeeperWeaponUpgradeSPGAME_M10_LVL_6,KeeperHealthUpgradeSPGAME_M10_LVL_1,KeeperHealthUpgradeSPGAME_M10_LVL_2,KeeperHealthUpgradeSPGAME_M10_LVL_3,AttackDroidHealthUpgradeSPGAME_LOW,AttackDroidHealthUpgradeSPGAME_MED,AttackDroidHealthUpgradeSPGAME_HIGH,AttackDroidWeaponUpgradeSPGAME_LOW,AttackDroidWeaponUpgradeSPGAME_MED,AttackDroidWeaponUpgradeSPGAME_HIGH,RadiationDefenseField",	
}
