--
--  Generated\Mission15.c
--
--  Finite state machine routines for "Mission15" mission
--
--  Copyright (C) 1998 Relic Entertainment Inc.
--  All rights reserved
--
--  This code was autogenerated from Mission15.kp by KAS2C Version 2.05
--


--#include "Generated\Mission15.h"  -- prototypes and #includes for exposed game functions

--extern AITeam *CurrentTeamP;
--#define kasThisTeamPtr CurrentTeamP

--  for run-time scoping of symbols (variables, timers, etc.)


dofilepath("data:scripts/SCAR/SCAR_Util.lua")             --stock HW2 scripting utilities
dofilepath("data:scripts/SCAR/KASUtil.lua")               --HW1->HW2 scripting utilities
dofilepath("data:scripts/SCAR/SinglePlayerFlow.lua")      --Emulation of HW1 singleplayer functionality
dofilepath("data:scripts/SCAR/SinglePlayerNIS.lua")       --Emulation of HW1 singleplayer NIS functionality
dofilepath("data:scripts/SCAR/SinglePlayerHyperspace.lua")--Emulation of HW1 hyperspace logic
dofilepath("data:scripts/SCAR/SpecialFlags.lua")          --Emulation of HW1 SPECIAL_xxx logic


--kas global variables, including variables used in ifOnce blocks
G_CountdownTime = 0
G_Dist2MShip = 0
G_HeadshotDestroyed = 0
SetMediumGuns = 0
_VIFONCE020 = 0
_VIFONCE021 = 0

--Following are global variables: created outside of the KAS structure and stubbed out here.
--G_Nis9Complete : see SinglePlayerFlow.lua, nReferences: 1
--G_PlayNis : see SinglePlayerFlow.lua, nReferences: 1

--Following are Team-Scoped variables: referenced differently than globals.
FinishedNIS = {["Events"] = 0}
IntelEvent = {["Events"] = 0}
PingedHeadshot = {["Events"] = 0}
_VIFONCE001 = {["Events"] = 0}
_VIFONCE002 = {["Events"] = 0}
_VIFONCE003 = {["Events"] = 0}
_VIFONCE004 = {["Events"] = 0}
_VIFONCE005 = {["Events"] = 0}
_VIFONCE006 = {["Events"] = 0}
_VIFONCE007 = {["Events"] = 0}
_VIFONCE008 = {["Events"] = 0}
_VIFONCE009 = {["Events"] = 0}
_VIFONCE010 = {["Events"] = 0}
_VIFONCE011 = {["Events"] = 0}
_VIFONCE012 = {["Events"] = 0}
_VIFONCE013 = {["Events"] = 0}
_VIFONCE014 = {["HeadShot"] = 0}
_VIFONCE015 = {["HeadShot"] = 0}
_VIFONCE016 = {["CorvetteGuard"] = 0, ["CorvetteHarass"] = 0, ["DefendersGuard"] = 0, ["Destroyers"] = 0, ["FrgHarrass"] = 0, ["FrigatesGuard"] = 0, ["InterceptorsHarrass"] = 0}
_VIFONCE017 = {["CorvetteGuard"] = 0, ["CorvetteHarass"] = 0, ["DefendersGuard"] = 0, ["Destroyers"] = 0, ["FrgHarrass"] = 0, ["FrigatesGuard"] = 0, ["InterceptorsHarrass"] = 0}
_VIFONCE018 = {["CorvetteGuard"] = 0, ["CorvetteHarass"] = 0, ["DefendersGuard"] = 0, ["Destroyers"] = 0, ["FrgHarrass"] = 0, ["FrigatesGuard"] = 0, ["InterceptorsHarrass"] = 0}
_VIFONCE019 = {["CorvetteGuard"] = 0, ["CorvetteHarass"] = 0, ["DefendersGuard"] = 0, ["Destroyers"] = 0, ["FrgHarrass"] = 0, ["FrigatesGuard"] = 0, ["InterceptorsHarrass"] = 0}

--Following are Team-Scoped timers: referenced differently than globals.
EndofLevel = {["Events"] = 0}
HoldForIntel = {["Events"] = 1}
HoldForSM = {["Events"] = 2}
LetterboxInTimer = {["Events"] = 3}
LetterboxOutTimer = {["Events"] = 4}
LocationTimer = {["Events"] = 5}
PingHeadshot = {["Events"] = 6}
WonAndDone = {["Events"] = 7}


--KAS objective names, set by KASObjective_Add
ObjectiveID_DestroyObject = 0
ObjectiveID_Hyperspace = 1
ObjectiveID_Count = 2


--Pointer IDs, set by KASPointer_Add<xxx>
PointerID_HeadshotPointer = 0


--extern sdword CurrentMissionScope;
--extern char CurrentMissionScopeName[];

--  for displaying localized strings
strCurLanguage = 1  --Naive treatement of localization language.;

LSTRING_Location = {  -- multilingual strings
	"CHAPEL PERILOUS",
	"Chapelle des Périls",
	"Gefahr im Verzug",
	"CAPILLA DEL PELIGRO",
	"CHAPEL PERILOUS", }
LSTRING_LevelName = {  -- multilingual strings
	"15 - Chapel Perilous",
	"15 - Chapelle des Périls",
	"15 - Gefahr im Verzug",
	"15 - Capilla del peligro",
	"15 - Chapel Perilous", }
LSTRING_Objective1 = {  -- multilingual strings
	"Destroy the object",
	"Destruction de l'objet",
	"Das Objekt zerstören.",
	"Destruir el objeto",
	"Distruggi l'oggetto", }
LSTRING_Hyperspace = {  -- multilingual strings
	"                HYPERSPACE",
	"                HYPERESPACE",
	"        HYPERRAUMSPRUNG",
	"                HIPERESPACIO",
	" 				IPERSPAZIO", }

--
--  "initialize" code for Mission15 Dead FSM
--
function Init_Mission15_Dead(TeamName)
	--FSM: FSM_Mission15_Dead
	--TeamName = Dead
	if (SobGroup_Count(TeamName) > 0) then     --kasfTeamCount()
	
	KAS_EnableAllAIFeatures()    --kasfEnableAllAIFeatures()
	KAS_GiveToCPUPlayer(TeamName)    --kasfTeamGiveToAI()
	end 
	
end 


--
--  "watch" code for Mission15 Dead FSM
--
function Watch_Mission15_Dead(TeamName)
	--FSM: FSM_Mission15_Dead
	--TeamName = Dead
	
end 


--
--  "initialize" code for Mission15 Events FSM
--
function Init_Mission15_Events(TeamName)
	--FSM: FSM_Mission15_Events
	--TeamName = Events
	--kasJump("PreNIS")
	KASRule_Add(TeamName, "Watch_Mission15_Events_PreNIS", "Init_Mission15_Events")
	Init_Mission15_Events_PreNIS(TeamName)
	return
	
end 


--
--  "watch" code for Mission15 Events FSM
--
function Watch_Mission15_Events(TeamName)
	--FSM: FSM_Mission15_Events
	--TeamName = Events
	if (_VIFONCE001[TeamName] == 0 and (SobGroup_Count("GrowSelection_EnemyMShip") == 0)) then  -- "ifonce" #1    --kasfShipsCount(kasGrowSelectionPtr("EnemyMShip"))
	
	_VIFONCE001[TeamName] = 1 --created,set;
	--kasJump("EvaluateWinner")
	--KASRule_Remove("FSM_Mission15_Events", "Watch_Mission15_Events")
	KASRule_Add(TeamName, "Watch_Mission15_Events_EvaluateWinner", "Watch_Mission15_Events")
	Init_Mission15_Events_EvaluateWinner(TeamName)
	return
	end 
	if (_VIFONCE002[TeamName] == 0 and (KAS_MessageReceived(TeamName, "HeadShotDestroyed") ~= 0)) then  -- "ifonce" #2    --kasfMsgReceived("HeadShotDestroyed")
	
	_VIFONCE002[TeamName] = 1 --created,set;
	KASObjective_SetState(ObjectiveID_DestroyObject, 1)    --kasfObjectiveSet("DestroyObject", 1)
	--kasJump("EvaluateWinner")
	--KASRule_Remove("FSM_Mission15_Events", "Watch_Mission15_Events")
	KASRule_Add(TeamName, "Watch_Mission15_Events_EvaluateWinner", "Watch_Mission15_Events")
	Init_Mission15_Events_EvaluateWinner(TeamName)
	return
	end 
	
end 


--
--  "initialize" code for Mission15 Events PreNIS state
--
function Init_Mission15_Events_PreNIS(TeamName)
	--FSM: FSM_Mission15_Events
	--TeamName = Events
	KASTimer_Start(LocationTimer[TeamName], 19)
	
end 


--
--  "watch" code for Mission15 Events PreNIS state
--
function Watch_Mission15_Events_PreNIS(TeamName)
	--FSM: FSM_Mission15_Events
	--TeamName = Events
	if (_VIFONCE003[TeamName] == 0 and (KASTimer_GetRemaining(LocationTimer[TeamName]) == 16)) then  -- "ifonce" #3
	
	_VIFONCE003[TeamName] = 1 --created,set;
	singlePlayerLocationCard("$61750", 5)    --kasfLocationCard(5000, LSTRING_Location[strCurLanguage])
	end 
	if (_VIFONCE004[TeamName] == 0 and (KASTimer_GetRemaining(LocationTimer[TeamName]) == 13)) then  -- "ifonce" #4
	
	_VIFONCE004[TeamName] = 1 --created,set;
	KAS_SubtitleAddOnce(Actor_HW1_FleetCommand, "$60701", 3)    --kasfSpeechEvent((701 + 2048 + 268435456), 0)
	end 
	if (_VIFONCE005[TeamName] == 0 and (KASTimer_GetRemaining(LocationTimer[TeamName]) == 6)) then  -- "ifonce" #5
	
	_VIFONCE005[TeamName] = 1 --created,set;
	KAS_MusicStop(2)    --kasfMusicStop(2)
	end 
	if (_VIFONCE006[TeamName] == 0 and (KASTimer_GetRemaining(LocationTimer[TeamName]) == 4)) then  -- "ifonce" #6
	
	_VIFONCE006[TeamName] = 1 --created,set;
	KAS_SetLetterboxState(2, 3)    --kasfWideScreenIn(90)
	end 
	if (_VIFONCE007[TeamName] == 0 and (KASTimer_IsExpiredIfSoDestroy(LocationTimer[TeamName]) ~= 0)) then  -- "ifonce" #7
	
	_VIFONCE007[TeamName] = 1 --created,set;
	--kasJump("PlayNIS")
	--KASRule_Remove("FSM_Mission15_Events", "Watch_Mission15_Events_PreNIS")
	KASRule_Add(TeamName, "Watch_Mission15_Events_PlayNIS", "Watch_Mission15_Events_PreNIS")
	Init_Mission15_Events_PlayNIS(TeamName)
	return
	end 
	
end 


--
--  "initialize" code for Mission15 Events PlayNIS state
--
function Init_Mission15_Events_PlayNIS(TeamName)
	--FSM: FSM_Mission15_Events
	--TeamName = Events
	G_PlayNis = 9 --created,set
	ignoredFunction()    --kasfTimerCreate("HoldForIntel")
	FinishedNIS[TeamName] = 0 --created,set
	
end 


--
--  "watch" code for Mission15 Events PlayNIS state
--
function Watch_Mission15_Events_PlayNIS(TeamName)
	--FSM: FSM_Mission15_Events
	--TeamName = Events
	if (_VIFONCE008[TeamName] == 0 and (G_Nis9Complete ~= 0)) then  -- "ifonce" #8
	
	_VIFONCE008[TeamName] = 1 --created,set;
	KASTimer_Set(HoldForIntel[TeamName], 7)
	KASTimer_Resume(HoldForIntel[TeamName])
	FinishedNIS[TeamName] = 1 --set
	end 
	if (KASTimer_IsExpired(HoldForIntel[TeamName]) ~= 0 and FinishedNIS[TeamName] ~= 0) then 
	
	KASTimer_End(HoldForIntel[TeamName])
	--kasJump("FIIntro1")
	--KASRule_Remove("FSM_Mission15_Events", "Watch_Mission15_Events_PlayNIS")
	KASRule_Add(TeamName, "Watch_Mission15_Events_FIIntro1", "Watch_Mission15_Events_PlayNIS")
	Init_Mission15_Events_FIIntro1(TeamName)
	return
	end 
	
end 


--
--  "initialize" code for Mission15 Events FIIntro1 state
--
function Init_Mission15_Events_FIIntro1(TeamName)
	--FSM: FSM_Mission15_Events
	--TeamName = Events
	if (ignoredFunction(0) == 0) then     --kasfRaceOfHuman()
	
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60702", 3)    --kasfSpeechEvent((702 + 4096 + 268435456), 0)
	else
	
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60703", 3)    --kasfSpeechEvent((703 + 4096 + 268435456), 0)
	end 
	ignoredFunction()    --kasfTimerCreate("HoldForSM")
	
end 


--
--  "watch" code for Mission15 Events FIIntro1 state
--
function Watch_Mission15_Events_FIIntro1(TeamName)
	--FSM: FSM_Mission15_Events
	--TeamName = Events
	IntelEvent[TeamName] = 0 --destroyed
	IntelEvent[TeamName] = Subtitle_IsDoneOrSkipped(Actor_FleetIntel) --created,set    --kasfIntelEventEnded()
	if (_VIFONCE009[TeamName] == 0 and (IntelEvent[TeamName] ~= 0)) then  -- "ifonce" #9
	
	_VIFONCE009[TeamName] = 1 --created,set;
	KASTimer_Set(HoldForSM[TeamName], 5)
	KASTimer_Resume(HoldForSM[TeamName])
	end 
	if (KASTimer_IsExpiredIfSoDestroy(HoldForSM[TeamName]) ~= 0) then 
	
	--kasJump("FIIntroLBXIn")
	--KASRule_Remove("FSM_Mission15_Events", "Watch_Mission15_Events_FIIntro1")
	KASRule_Add(TeamName, "Watch_Mission15_Events_FIIntroLBXIn", "Watch_Mission15_Events_FIIntro1")
	Init_Mission15_Events_FIIntroLBXIn(TeamName)
	return
	end 
	
end 


--
--  "initialize" code for Mission15 Events FIIntroLBXIn state
--
function Init_Mission15_Events_FIIntroLBXIn(TeamName)
	--FSM: FSM_Mission15_Events
	--TeamName = Events
	KASRules_PauseExceptFSM(TeamName)    --kasfOtherKASPause()
	KAS_SetLetterboxState(2, 3)    --kasfWideScreenIn(90)
	KASTimer_Start(LetterboxInTimer[TeamName], 4)
	
end 


--
--  "watch" code for Mission15 Events FIIntroLBXIn state
--
function Watch_Mission15_Events_FIIntroLBXIn(TeamName)
	--FSM: FSM_Mission15_Events
	--TeamName = Events
	if (KASTimer_GetRemaining(LetterboxInTimer[TeamName]) == 2) then 
	
	KAS_SensorsToggle(1, 120000)    --kasfOpenSensors(120000)
	KAS_UniversePause(1)    --kasfUniversePause()
	end 
	if (KASTimer_IsExpiredIfSoDestroy(LetterboxInTimer[TeamName]) ~= 0) then 
	
	--kasJump("FIIntro2")
	--KASRule_Remove("FSM_Mission15_Events", "Watch_Mission15_Events_FIIntroLBXIn")
	KASRule_Add(TeamName, "Watch_Mission15_Events_FIIntro2", "Watch_Mission15_Events_FIIntroLBXIn")
	Init_Mission15_Events_FIIntro2(TeamName)
	return
	end 
	
end 


--
--  "initialize" code for Mission15 Events FIIntro2 state
--
function Init_Mission15_Events_FIIntro2(TeamName)
	--FSM: FSM_Mission15_Events
	--TeamName = Events
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60704", 3)    --kasfSpeechEvent((704 + 4096 + 268435456), 0)
	KASTimer_Start(PingHeadshot[TeamName], 1)
	PingedHeadshot[TeamName] = 0 --created,set
	
end 


--
--  "watch" code for Mission15 Events FIIntro2 state
--
function Watch_Mission15_Events_FIIntro2(TeamName)
	--FSM: FSM_Mission15_Events
	--TeamName = Events
	IntelEvent[TeamName] = 0 --destroyed
	IntelEvent[TeamName] = Subtitle_IsDoneOrSkipped(Actor_FleetIntel) --created,set    --kasfIntelEventEnded()
	if (IntelEvent[TeamName] == 2) then 
	
	if (PingedHeadshot[TeamName] == 0) then 
	
	KASTimer_End(PingHeadshot[TeamName])
	KAS_PingAddShips("HeadShot", "HeadshotAsteroidPing", "$60700")    --kasfPingAddShips(kasAITeamShipsPtr("HeadShot"), "HeadshotAsteroidPing")
	else
	
	KASPointer_Remove(PointerID_HeadshotPointer)    --kasfTutRemovePointer("HeadshotPointer")
	end 
	KASObjective_Add(ObjectiveID_DestroyObject, "$61752", OT_Primary)    --kasfObjectiveCreate("DestroyObject", LSTRING_Objective1[strCurLanguage], LSTRING_Objective1[strCurLanguage])
	Objective_SetDescription(ObjectiveID_DestroyObject, "$60843")
	--kasJump("FIIntroLBXOut")
	--KASRule_Remove("FSM_Mission15_Events", "Watch_Mission15_Events_FIIntro2")
	KASRule_Add(TeamName, "Watch_Mission15_Events_FIIntroLBXOut", "Watch_Mission15_Events_FIIntro2")
	Init_Mission15_Events_FIIntroLBXOut(TeamName)
	return
	elseif (IntelEvent[TeamName] ~= 0) then 
	
	KASPointer_Remove(PointerID_HeadshotPointer)    --kasfTutRemovePointer("HeadshotPointer")
	KASObjective_Add(ObjectiveID_DestroyObject, "$61752", OT_Primary)    --kasfObjectiveCreate("DestroyObject", LSTRING_Objective1[strCurLanguage], LSTRING_Objective1[strCurLanguage])
	Objective_SetDescription(ObjectiveID_DestroyObject, "$60843")
	--kasJump("FIIntroLBXOut")
	--KASRule_Remove("FSM_Mission15_Events", "Watch_Mission15_Events_FIIntro2")
	KASRule_Add(TeamName, "Watch_Mission15_Events_FIIntroLBXOut", "Watch_Mission15_Events_FIIntro2")
	Init_Mission15_Events_FIIntroLBXOut(TeamName)
	return
	end 
	if (_VIFONCE010[TeamName] == 0 and (KASTimer_IsExpiredIfSoDestroy(PingHeadshot[TeamName]) ~= 0)) then  -- "ifonce" #10
	
	_VIFONCE010[TeamName] = 1 --created,set;
	KAS_PingAddShips("HeadShot", "HeadshotAsteroidPing", "$60700")    --kasfPingAddShips(kasAITeamShipsPtr("HeadShot"), "HeadshotAsteroidPing")
	PointerID_HeadshotPointer = KASPointer_AddSobGroup("HeadShot")    --kasfTutSetPointerTargetShipSelection("HeadshotPointer", kasAITeamShipsPtr("HeadShot"))
	PingedHeadshot[TeamName] = 1 --set
	end 
	
end 


--
--  "initialize" code for Mission15 Events FIIntroLBXOut state
--
function Init_Mission15_Events_FIIntroLBXOut(TeamName)
	--FSM: FSM_Mission15_Events
	--TeamName = Events
	KASTimer_Start(LetterboxOutTimer[TeamName], 5)
	
end 


--
--  "watch" code for Mission15 Events FIIntroLBXOut state
--
function Watch_Mission15_Events_FIIntroLBXOut(TeamName)
	--FSM: FSM_Mission15_Events
	--TeamName = Events
	if (_VIFONCE011[TeamName] == 0 and (KASTimer_GetRemaining(LetterboxOutTimer[TeamName]) == 4)) then  -- "ifonce" #11
	
	_VIFONCE011[TeamName] = 1 --created,set;
	KAS_UniversePause(0)    --kasfUniverseUnpause()
	KAS_SensorsToggle(0, 1)    --kasfCloseSensors(1)
	KAS_SetLetterboxState(0, 1)    --kasfWideScreenOut(30)
	KASRules_UnpauseOthers()    --kasfOtherKASUnpause()
	end 
	if (KASTimer_IsExpiredIfSoDestroy(LetterboxOutTimer[TeamName]) ~= 0) then 
	
	--kasJump("Countdown")
	--KASRule_Remove("FSM_Mission15_Events", "Watch_Mission15_Events_FIIntroLBXOut")
	KASRule_Add(TeamName, "Watch_Mission15_Events_Countdown", "Watch_Mission15_Events_FIIntroLBXOut")
	Init_Mission15_Events_Countdown(TeamName)
	return
	end 
	
end 


--
--  "initialize" code for Mission15 Events Countdown state
--
function Init_Mission15_Events_Countdown(TeamName)
	--FSM: FSM_Mission15_Events
	--TeamName = Events
	KASTimer_Start(EndofLevel[TeamName], G_CountdownTime)
	KAS_MessageSendToAll(TeamName, "StartedCountdown")    --kasfMsgSendAll("StartedCountdown")
	G_HeadshotDestroyed = 0 --set
	
end 


--
--  "watch" code for Mission15 Events Countdown state
--
function Watch_Mission15_Events_Countdown(TeamName)
	--FSM: FSM_Mission15_Events
	--TeamName = Events
	if (KASTimer_GetRemaining(EndofLevel[TeamName]) == 1200 and G_HeadshotDestroyed == 0) then 
	
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60705", 3)    --kasfSpeechEvent((705 + 4096 + 268435456), 0)
	end 
	if (KASTimer_GetRemaining(EndofLevel[TeamName]) == 900 and G_HeadshotDestroyed == 0) then 
	
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60706", 3)    --kasfSpeechEvent((706 + 4096 + 268435456), 0)
	end 
	if (KASTimer_GetRemaining(EndofLevel[TeamName]) == 600 and G_HeadshotDestroyed == 0) then 
	
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60707", 3)    --kasfSpeechEvent((707 + 4096 + 268435456), 0)
	end 
	if (KASTimer_GetRemaining(EndofLevel[TeamName]) == 300 and G_HeadshotDestroyed == 0) then 
	
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60708", 3)    --kasfSpeechEvent((708 + 4096 + 268435456), 0)
	end 
	if (KASTimer_GetRemaining(EndofLevel[TeamName]) == 240 and G_HeadshotDestroyed == 0) then 
	
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60709", 3)    --kasfSpeechEvent((709 + 4096 + 268435456), 0)
	end 
	if (KASTimer_GetRemaining(EndofLevel[TeamName]) == 180 and G_HeadshotDestroyed == 0) then 
	
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60710", 3)    --kasfSpeechEvent((710 + 4096 + 268435456), 0)
	end 
	if (KASTimer_GetRemaining(EndofLevel[TeamName]) == 120 and G_HeadshotDestroyed == 0) then 
	
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60711", 3)    --kasfSpeechEvent((711 + 4096 + 268435456), 0)
	end 
	if (KASTimer_GetRemaining(EndofLevel[TeamName]) == 60 and G_HeadshotDestroyed == 0) then 
	
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60712", 3)    --kasfSpeechEvent((712 + 4096 + 268435456), 0)
	end 
	if (KASTimer_GetRemaining(EndofLevel[TeamName]) == 30 and G_HeadshotDestroyed == 0) then 
	
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60735", 3)    --kasfSpeechEvent((735 + 4096 + 268435456), 0)
	end 
	if (KASTimer_GetRemaining(EndofLevel[TeamName]) == 10 and G_HeadshotDestroyed == 0) then 
	
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60736", 3)    --kasfSpeechEvent((736 + 4096 + 268435456), 0)
	end 
	if (KASTimer_GetRemaining(EndofLevel[TeamName]) == 5 and G_HeadshotDestroyed == 0) then 
	
	KAS_SubtitleAddOnce(Actor_HW1_FleetCommand, "$60713", 3)    --kasfSpeechEvent((713 + 2048 + 268435456), 0)
	end 
	if (KASTimer_IsExpiredIfSoDestroy(EndofLevel[TeamName]) ~= 0) then 
	
	--kasJump("EvaluateWinner")
	--KASRule_Remove("FSM_Mission15_Events", "Watch_Mission15_Events_Countdown")
	KASRule_Add(TeamName, "Watch_Mission15_Events_EvaluateWinner", "Watch_Mission15_Events_Countdown")
	Init_Mission15_Events_EvaluateWinner(TeamName)
	return
	end 
	
end 


--
--  "initialize" code for Mission15 Events EvaluateWinner state
--
function Init_Mission15_Events_EvaluateWinner(TeamName)
	--FSM: FSM_Mission15_Events
	--TeamName = Events
	KASTimer_Start(WonAndDone[TeamName], 22)
	
end 


--
--  "watch" code for Mission15 Events EvaluateWinner state
--
function Watch_Mission15_Events_EvaluateWinner(TeamName)
	--FSM: FSM_Mission15_Events
	--TeamName = Events
	if (_VIFONCE012[TeamName] == 0 and (G_HeadshotDestroyed == 1)) then  -- "ifonce" #12
	
	_VIFONCE012[TeamName] = 1 --created,set;
	KASObjective_SetState(ObjectiveID_DestroyObject, 1)    --kasfObjectiveSet("DestroyObject", 1)
	end 
	if (SobGroup_Count("GrowSelection_EnemyMShip") == 0) then     --kasfShipsCount(kasGrowSelectionPtr("EnemyMShip"))
	
	KASObjective_DestroyAll()    --kasfObjectiveDestroyAll()
	KAS_MissionFailed()    --kasfMissionFailed()
	--kasFSMCreate("Dead")
	KASRule_AddFSM(TeamName, "Watch_Mission15_Dead", "Watch_Mission15_Events_EvaluateWinner")
	Init_Mission15_Dead(TeamName)
	end 
	if (_VIFONCE013[TeamName] == 0 and (KASTimer_IsExpiredIfSoDestroy(WonAndDone[TeamName]) ~= 0)) then  -- "ifonce" #13
	
	_VIFONCE013[TeamName] = 1 --created,set;
	KASObjective_Add(ObjectiveID_Hyperspace, "Hyperspace", OT_Primary)    --kasfObjectiveCreate("Hyperspace", LSTRING_Hyperspace[strCurLanguage], LSTRING_Hyperspace[strCurLanguage])
	Objective_SetDescription(ObjectiveID_Hyperspace, "hyperspace")
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60714", 3)    --kasfSpeechEvent((714 + 4096 + 268435456), 0)
	end 
	
end 


--
--  "initialize" code for Mission15 HeadShot FSM
--
function Init_Mission15_HeadShot(TeamName)
	--FSM: FSM_Mission15_HeadShot
	--TeamName = HeadShot
	
end 


--
--  "watch" code for Mission15 HeadShot FSM
--
function Watch_Mission15_HeadShot(TeamName)
	--FSM: FSM_Mission15_HeadShot
	--TeamName = HeadShot
	if (KAS_MessageReceived(TeamName, "StartedCountdown") ~= 0) then     --kasfMsgReceived("StartedCountdown")
	
	--kasJump("Moving")
	--KASRule_Remove("FSM_Mission15_HeadShot", "Watch_Mission15_HeadShot")
	KASRule_Add(TeamName, "Watch_Mission15_HeadShot_Moving", "Watch_Mission15_HeadShot")
	Init_Mission15_HeadShot_Moving(TeamName)
	return
	end 
	if (_VIFONCE014[TeamName] == 0 and (SobGroup_Count(TeamName) == 0)) then  -- "ifonce" #14    --kasfTeamCount()
	
	_VIFONCE014[TeamName] = 1 --created,set;
	KAS_MessageSendToAll(TeamName, "HeadShotDestroyed")    --kasfMsgSendAll("HeadShotDestroyed")
	G_HeadshotDestroyed = 1 --set
	SobGroup_Stop(SobGroup_GetPlayerOwner(TeamName), TeamName)    --kasfStop()
	KAS_MusicStop(2)    --kasfMusicStop(2)
	--kasFSMCreate("Dead")
	KASRule_AddFSM(TeamName, "Watch_Mission15_Dead", "Watch_Mission15_HeadShot")
	Init_Mission15_Dead(TeamName)
	end 
	
end 


--
--  "initialize" code for Mission15 HeadShot Moving state
--
function Init_Mission15_HeadShot_Moving(TeamName)
	--FSM: FSM_Mission15_HeadShot
	--TeamName = HeadShot
	SobGroup_Clear("GrowSelection_Mothership")    --kasfGrowSelectionClear(kasGrowSelectionPtr("Mothership"))
	if (KAS_FindPlayerShipsOfType("GrowSelection_Mothership", "Mothership", 0) == 0) then     --kasfFindEnemyShipsOfType(kasGrowSelectionPtr("Mothership"), "Mothership")
	
	KAS_MissionFailed()    --kasfMissionFailed()
	--kasFSMCreate("Dead")
	KASRule_AddFSM(TeamName, "Watch_Mission15_Dead", "Watch_Mission15_HeadShot_Moving")
	Init_Mission15_Dead(TeamName)
	end 
	G_Dist2MShip = KAS_FindDistance(KAS_NamedCentrePosition(TeamName), KAS_NamedCentrePosition("GrowSelection_Mothership")) - 1500 --set    --kasfFindDistance(kasThisTeamsVectorPtr(), kasShipsVectorPtr("Mothership"))
    --lmch - hack to get the headshot to impact at the right time.  It's going a bit slow in HW2 for some reason.
	SobGroup_SetMaxSpeed(TeamName, G_Dist2MShip/G_CountdownTime*390/(390-18))    --kasfTeamSetMaxVelocity(___KAS_SCOPED_VAR____G_Dist2MShip_ / ___KAS_SCOPED_VAR____G_CountdownTime_ * 390 / (390-18))
	SobGroup_MoveToPoint(SobGroup_GetPlayerOwner(TeamName), TeamName, Volume_GetPosition("TowardsPoint"))    --kasfMoveTo(kasVectorPtr("TowardsPoint"))
	
end 


--
--  "watch" code for Mission15 HeadShot Moving state
--
function Watch_Mission15_HeadShot_Moving(TeamName)
	--FSM: FSM_Mission15_HeadShot
	--TeamName = HeadShot
	if (_VIFONCE015[TeamName] == 0 and (KAS_UnderAttack(TeamName, "GrowSelection_FirstAttackingShips") > 0)) then  -- "ifonce" #15    --kasfUnderAttack(kasGrowSelectionPtr("FirstAttackingShips"))
	
	_VIFONCE015[TeamName] = 1 --created,set;
	KAS_MusicStop(0)    --kasfMusicStop(0)
	KAS_MusicPlayType("data:sound/music/battle/B02_TuranicRaidersShort", MUS_Ambient)    --kasfMusicPlay(13)
	end 
	
end 


--
--  "initialize" code for Mission15 Protection FSM
--
function Init_Mission15_Protection(TeamName)
	--FSM: FSM_Mission15_Protection
	--TeamName = Protection
	--kasJump("Guarding")
	KASRule_Add(TeamName, "Watch_Mission15_Protection_Guarding", "Init_Mission15_Protection")
	Init_Mission15_Protection_Guarding(TeamName)
	return
	
end 


--
--  "watch" code for Mission15 Protection FSM
--
function Watch_Mission15_Protection(TeamName)
	--FSM: FSM_Mission15_Protection
	--TeamName = Protection
	if (_VIFONCE016[TeamName] == 0 and (KAS_MessageReceived(TeamName, "HeadShotDestroyed") ~= 0)) then  -- "ifonce" #16    --kasfMsgReceived("HeadShotDestroyed")
	
	_VIFONCE016[TeamName] = 1 --created,set;
	--kasJump("KillMShip")
	--KASRule_Remove("FSM_Mission15_Protection", "Watch_Mission15_Protection")
	KASRule_Add(TeamName, "Watch_Mission15_Protection_KillMShip", "Watch_Mission15_Protection")
	Init_Mission15_Protection_KillMShip(TeamName)
	return
	end 
	if (_VIFONCE017[TeamName] == 0 and (SobGroup_Count(TeamName) == 0)) then  -- "ifonce" #17    --kasfTeamCount()
	
	_VIFONCE017[TeamName] = 1 --created,set;
	--kasFSMCreate("Dead")
	KASRule_AddFSM(TeamName, "Watch_Mission15_Dead", "Watch_Mission15_Protection")
	Init_Mission15_Dead(TeamName)
	end 
	
end 


--
--  "initialize" code for Mission15 Protection Guarding state
--
function Init_Mission15_Protection_Guarding(TeamName)
	--FSM: FSM_Mission15_Protection
	--TeamName = Protection
	if (KAS_TeamNamesEqual(TeamName, "DefendersGuard") ~= 0) then     --kasfThisTeamIs(kasAITeamPtr("DefendersGuard"))
	
	KAS_SetFormation(TeamName, "Wall")    --kasfFormationWall()
	else
	
	KAS_SetFormation(TeamName, "Broad")    --kasfFormationBroad()
	end 
	SobGroup_SetROE(TeamName, PassiveROE)    --kasfTacticsNeutral()
	SobGroup_GuardSobGroup(TeamName, "HeadShot")    --kasfGuardShips(kasAITeamShipsPtr("HeadShot"))
	
end 


--
--  "watch" code for Mission15 Protection Guarding state
--
function Watch_Mission15_Protection_Guarding(TeamName)
	--FSM: FSM_Mission15_Protection
	--TeamName = Protection
	SobGroup_Clear("GrowSelection_Evaluate")    --kasfGrowSelectionClear(kasGrowSelectionPtr("Evaluate"))
	if (KAS_UnderAttack(TeamName, "GrowSelection_Evaluate") > 0 or KAS_UnderAttack("HeadShot", "GrowSelection_Evaluate") > 0 or KAS_FindEnemiesNearby("GrowSelection_Evaluate", 7000) > 0 or KAS_FindEnemiesInside("HeadshotPathArea", "GrowSelection_Evaluate") > 0) then     --kasfFindEnemiesInside(kasVolumePtr("HeadshotPathArea"), kasGrowSelectionPtr("Evaluate"), 5000)    --kasfFindEnemiesNearby(kasGrowSelectionPtr("Evaluate"), 20000)    --kasfUnderAttack(kasGrowSelectionPtr("Evaluate"))    --kasfUnderAttackElsewhere(kasAITeamPtr("HeadShot"), kasGrowSelectionPtr("Evaluate"))
	
	KAS_Attack(TeamName, "GrowSelection_Evaluate")    --kasfAttack(kasGrowSelectionPtr("Evaluate"))
	--kasJump("Retaliate")
	--KASRule_Remove("FSM_Mission15_Protection", "Watch_Mission15_Protection_Guarding")
	KASRule_Add(TeamName, "Watch_Mission15_Protection_Retaliate", "Watch_Mission15_Protection_Guarding")
	Init_Mission15_Protection_Retaliate(TeamName)
	return
	end 
	
end 


--
--  "initialize" code for Mission15 Protection Retaliate state
--
function Init_Mission15_Protection_Retaliate(TeamName)
	--FSM: FSM_Mission15_Protection
	--TeamName = Protection
	
end 


--
--  "watch" code for Mission15 Protection Retaliate state
--
function Watch_Mission15_Protection_Retaliate(TeamName)
	--FSM: FSM_Mission15_Protection
	--TeamName = Protection
	SobGroup_Clear("GrowSelection_Evaluate")    --kasfGrowSelectionClear(kasGrowSelectionPtr("Evaluate"))
	if (KAS_GetCurrentOrder(TeamName) ~= 2) then     --kasfShipsOrder((&kasThisTeamPtr->shipList))
	
	if (KAS_UnderAttack(TeamName, "GrowSelection_Evaluate") > 0 or KAS_UnderAttack("HeadShot", "GrowSelection_Evaluate") > 0 or KAS_FindEnemiesNearby("GrowSelection_Evaluate", 7000) > 0 or KAS_FindEnemiesInside("HeadshotPathArea", "GrowSelection_Evaluate") > 0) then     --kasfFindEnemiesInside(kasVolumePtr("HeadshotPathArea"), kasGrowSelectionPtr("Evaluate"), 5000)    --kasfFindEnemiesNearby(kasGrowSelectionPtr("Evaluate"), 20000)    --kasfUnderAttack(kasGrowSelectionPtr("Evaluate"))    --kasfUnderAttackElsewhere(kasAITeamPtr("HeadShot"), kasGrowSelectionPtr("Evaluate"))
	
	SobGroup_FillShipsByIndexRange("GrowSelection_Evaluate", "GrowSelection_Evaluate", 0, 1)    --kasfShipsSelectIndex(kasGrowSelectionPtr("Evaluate"), kasGrowSelectionPtr("Evaluate"), 0)
	KAS_Attack(TeamName, "GrowSelection_Evaluate")    --kasfAttack(kasGrowSelectionPtr("Evaluate"))
	else
	
	--kasJump("Guarding")
	--KASRule_Remove("FSM_Mission15_Protection", "Watch_Mission15_Protection_Retaliate")
	KASRule_Add(TeamName, "Watch_Mission15_Protection_Guarding", "Watch_Mission15_Protection_Retaliate")
	Init_Mission15_Protection_Guarding(TeamName)
	return
	end 
	end 
	if (KAS_TeamHealth(TeamName) < 40) then     --kasfTeamHealthAverage()
	
	SobGroup_SetROE(TeamName, DefensiveROE)    --kasfTacticsEvasive()
		SobGroup_SetStance(TeamName, AggressiveStance)
	elseif (KAS_TeamHealth(TeamName) < 75) then     --kasfTeamHealthAverage()
	
	SobGroup_SetROE(TeamName, PassiveROE)    --kasfTacticsNeutral()
	else
	
	SobGroup_SetROE(TeamName, OffensiveROE)    --kasfTacticsAggressive()
		SobGroup_SetStance(TeamName, AggressiveStance)
	end 
	
end 


--
--  "initialize" code for Mission15 Protection KillMShip state
--
function Init_Mission15_Protection_KillMShip(TeamName)
	--FSM: FSM_Mission15_Protection
	--TeamName = Protection
	if (SobGroup_Count("GrowSelection_EnemyMShip") == 0) then     --kasfShipsCount(kasGrowSelectionPtr("EnemyMShip"))
	
	--kasFSMCreate("Dead")
	KASRule_AddFSM(TeamName, "Watch_Mission15_Dead", "Watch_Mission15_Protection_KillMShip")
	Init_Mission15_Dead(TeamName)
	end 
	
end 


--
--  "watch" code for Mission15 Protection KillMShip state
--
function Watch_Mission15_Protection_KillMShip(TeamName)
	--FSM: FSM_Mission15_Protection
	--TeamName = Protection
	if (KAS_GetCurrentOrder(TeamName) ~= 2) then     --kasfShipsOrder((&kasThisTeamPtr->shipList))
	
	SobGroup_SetROE(TeamName, OffensiveROE)    --kasfTacticsAggressive()
		SobGroup_SetStance(TeamName, AggressiveStance)
	if (KAS_FillShipsByNonCapital("GrowSelection_Evaluate", TeamName) > 0) then     --kasfShipsSelectNonCapital(kasGrowSelectionPtr("Evaluate"), (&kasThisTeamPtr->shipList))
	
	KAS_KamikazeEveryone("GrowSelection_EnemyMShip")    --kasfKamikazeEveryone(kasGrowSelectionPtr("EnemyMShip"))
	else
	
	KAS_Attack(TeamName, "GrowSelection_EnemyMShip")    --kasfAttack(kasGrowSelectionPtr("EnemyMShip"))
	end 
	elseif (KAS_FillShipsByCapital("GrowSelection_Evaluate", TeamName) > 0) then     --kasfShipsSelectCapital(kasGrowSelectionPtr("Evaluate"), (&kasThisTeamPtr->shipList))
	
	KAS_MoveAttack(TeamName, "GrowSelection_EnemyMShip")    --kasfMoveAttack(kasGrowSelectionPtr("EnemyMShip"))
	end 
	
end 


--
--  "initialize" code for Mission15 Harrass FSM
--
function Init_Mission15_Harrass(TeamName)
	--FSM: FSM_Mission15_Harrass
	--TeamName = Harrass
	SobGroup_SetROE(TeamName, DefensiveROE)    --kasfTacticsEvasive()
		SobGroup_SetStance(TeamName, AggressiveStance)
	--kasJump("Bother")
	KASRule_Add(TeamName, "Watch_Mission15_Harrass_Bother", "Init_Mission15_Harrass")
	Init_Mission15_Harrass_Bother(TeamName)
	return
	
end 


--
--  "watch" code for Mission15 Harrass FSM
--
function Watch_Mission15_Harrass(TeamName)
	--FSM: FSM_Mission15_Harrass
	--TeamName = Harrass
	if (_VIFONCE018[TeamName] == 0 and (KAS_MessageReceived(TeamName, "HeadShotDestroyed") ~= 0)) then  -- "ifonce" #18    --kasfMsgReceived("HeadShotDestroyed")
	
	_VIFONCE018[TeamName] = 1 --created,set;
	--kasJump("KillMShip")
	--KASRule_Remove("FSM_Mission15_Harrass", "Watch_Mission15_Harrass")
	KASRule_Add(TeamName, "Watch_Mission15_Harrass_KillMShip", "Watch_Mission15_Harrass")
	Init_Mission15_Harrass_KillMShip(TeamName)
	return
	end 
	if (_VIFONCE019[TeamName] == 0 and (SobGroup_Count(TeamName) == 0)) then  -- "ifonce" #19    --kasfTeamCount()
	
	_VIFONCE019[TeamName] = 1 --created,set;
	--kasFSMCreate("Dead")
	KASRule_AddFSM(TeamName, "Watch_Mission15_Dead", "Watch_Mission15_Harrass")
	Init_Mission15_Dead(TeamName)
	end 
	
end 


--
--  "initialize" code for Mission15 Harrass Bother state
--
function Init_Mission15_Harrass_Bother(TeamName)
	--FSM: FSM_Mission15_Harrass
	--TeamName = Harrass
	if (KAS_FillShipsByCapital("GrowSelection_Evaluate", TeamName) > 0) then     --kasfShipsSelectCapital(kasGrowSelectionPtr("Evaluate"), (&kasThisTeamPtr->shipList))
	
	KAS_SetFormation(TeamName, "Wall")    --kasfFormationWall()
	else
	
	KAS_SetFormation(TeamName, "Claw")    --kasfFormationClaw()
	end 
	KAS_AttackHarrass(TeamName)    --kasfAttackHarass()
	
end 


--
--  "watch" code for Mission15 Harrass Bother state
--
function Watch_Mission15_Harrass_Bother(TeamName)
	--FSM: FSM_Mission15_Harrass
	--TeamName = Harrass
	SobGroup_Clear("GrowSelection_HEval")    --kasfGrowSelectionClear(kasGrowSelectionPtr("HEval"))
	if (KAS_GetCurrentOrder(TeamName) ~= 2) then     --kasfShipsOrder((&kasThisTeamPtr->shipList))
	
	SobGroup_Clear("GrowSelection_HEval")    --kasfGrowSelectionClear(kasGrowSelectionPtr("HEval"))
	if (KAS_UnderAttack(TeamName, "GrowSelection_HEval") > 0 or KAS_UnderAttack("HeadShot", "GrowSelection_HEval") > 0 or KAS_FindEnemiesNearTeam(TeamName, "GrowSelection_HEval", 7000) > 0 or KAS_FindEnemiesInside("HeadshotPathArea", "GrowSelection_HEval") > 0) then     --kasfFindEnemiesInside(kasVolumePtr("HeadshotPathArea"), kasGrowSelectionPtr("HEval"), 5000)    --kasfFindEnemiesNearTeam(kasGrowSelectionPtr("HEval"), 20000)    --kasfUnderAttack(kasGrowSelectionPtr("HEval"))    --kasfUnderAttackElsewhere(kasAITeamPtr("HeadShot"), kasGrowSelectionPtr("HEval"))
	
	SobGroup_FillShipsByIndexRange("GrowSelection_HEval", "GrowSelection_HEval", 0, 1)    --kasfShipsSelectIndex(kasGrowSelectionPtr("HEval"), kasGrowSelectionPtr("HEval"), 0)
	KAS_Attack(TeamName, "GrowSelection_HEval")    --kasfAttack(kasGrowSelectionPtr("HEval"))
	else
	
	--kasJump("Guard")
	--KASRule_Remove("FSM_Mission15_Harrass", "Watch_Mission15_Harrass_Bother")
	KASRule_Add(TeamName, "Watch_Mission15_Harrass_Guard", "Watch_Mission15_Harrass_Bother")
	Init_Mission15_Harrass_Guard(TeamName)
	return
	end 
	end 
	
end 


--
--  "initialize" code for Mission15 Harrass Guard state
--
function Init_Mission15_Harrass_Guard(TeamName)
	--FSM: FSM_Mission15_Harrass
	--TeamName = Harrass
	SobGroup_GuardSobGroup(TeamName, "HeadShot")    --kasfGuardShips(kasAITeamShipsPtr("HeadShot"))
	
end 


--
--  "watch" code for Mission15 Harrass Guard state
--
function Watch_Mission15_Harrass_Guard(TeamName)
	--FSM: FSM_Mission15_Harrass
	--TeamName = Harrass
	SobGroup_Clear("GrowSelection_HEval")    --kasfGrowSelectionClear(kasGrowSelectionPtr("HEval"))
	if (KAS_UnderAttack(TeamName, "GrowSelection_HEval") > 0 or KAS_UnderAttack("HeadShot", "GrowSelection_HEval") > 0 or KAS_FindEnemiesNearTeam(TeamName, "GrowSelection_HEval", 7000) > 0 or KAS_FindEnemiesInside("HeadshotPathArea", "GrowSelection_HEval") > 0) then     --kasfFindEnemiesInside(kasVolumePtr("HeadshotPathArea"), kasGrowSelectionPtr("HEval"), 5000)    --kasfFindEnemiesNearTeam(kasGrowSelectionPtr("HEval"), 20000)    --kasfUnderAttack(kasGrowSelectionPtr("HEval"))    --kasfUnderAttackElsewhere(kasAITeamPtr("HeadShot"), kasGrowSelectionPtr("HEval"))
	
	SobGroup_FillShipsByIndexRange("GrowSelection_HEval", "GrowSelection_HEval", 0, 1)    --kasfShipsSelectIndex(kasGrowSelectionPtr("HEval"), kasGrowSelectionPtr("HEval"), 0)
	KAS_Attack(TeamName, "GrowSelection_HEval")    --kasfAttack(kasGrowSelectionPtr("HEval"))
	
	--kasJump("Bother")
	--KASRule_Remove("FSM_Mission15_Harrass", "Watch_Mission15_Harrass_Guard")
	KASRule_Add(TeamName, "Watch_Mission15_Harrass_Bother", "Watch_Mission15_Harrass_Guard")
	Init_Mission15_Harrass_Bother(TeamName)
	return
	end 
	
end 


--
--  "initialize" code for Mission15 Harrass KillMShip state
--
function Init_Mission15_Harrass_KillMShip(TeamName)
	--FSM: FSM_Mission15_Harrass
	--TeamName = Harrass
	if (SobGroup_Count("GrowSelection_EnemyMShip") == 0) then     --kasfShipsCount(kasGrowSelectionPtr("EnemyMShip"))
	
	--kasFSMCreate("Dead")
	KASRule_AddFSM(TeamName, "Watch_Mission15_Dead", "Watch_Mission15_Harrass_KillMShip")
	Init_Mission15_Dead(TeamName)
	end 
	
end 


--
--  "watch" code for Mission15 Harrass KillMShip state
--
function Watch_Mission15_Harrass_KillMShip(TeamName)
	--FSM: FSM_Mission15_Harrass
	--TeamName = Harrass
	if (KAS_GetCurrentOrder(TeamName) ~= 2) then     --kasfShipsOrder((&kasThisTeamPtr->shipList))
	
	SobGroup_SetROE(TeamName, OffensiveROE)    --kasfTacticsAggressive()
		SobGroup_SetStance(TeamName, AggressiveStance)
	if (KAS_FillShipsByNonCapital("GrowSelection_Evaluate", TeamName) > 0) then     --kasfShipsSelectNonCapital(kasGrowSelectionPtr("Evaluate"), (&kasThisTeamPtr->shipList))
	
	KAS_KamikazeEveryone("GrowSelection_EnemyMShip")    --kasfKamikazeEveryone(kasGrowSelectionPtr("EnemyMShip"))
	else
	
	KAS_Attack(TeamName, "GrowSelection_EnemyMShip")    --kasfAttack(kasGrowSelectionPtr("EnemyMShip"))
	end 
	elseif (KAS_FillShipsByCapital("GrowSelection_Evaluate", TeamName) > 0) then     --kasfShipsSelectCapital(kasGrowSelectionPtr("Evaluate"), (&kasThisTeamPtr->shipList))
	
	KAS_MoveAttack(TeamName, "GrowSelection_EnemyMShip")    --kasfMoveAttack(kasGrowSelectionPtr("EnemyMShip"))
	end 
	
end 


--
--  "initialize" code for Mission15 WaitForCountDown FSM
--
function Init_Mission15_WaitForCountDown(TeamName)
	--FSM: FSM_Mission15_WaitForCountDown
	--TeamName = "Destroyers"
	
end 


--
--  "watch" code for Mission15 WaitForCountDown FSM
--
function Watch_Mission15_WaitForCountDown(TeamName)
	--FSM: FSM_Mission15_WaitForCountDown
	--TeamName = "Destroyers"
	if (KAS_MessageReceived(TeamName, "StartedCountdown") ~= 0) then     --kasfMsgReceived("StartedCountdown")
	
	if (KAS_TeamNamesEqual(TeamName, "Destroyers") ~= 0 or KAS_TeamNamesEqual(TeamName, "FrigatesGuard") ~= 0 or KAS_TeamNamesEqual(TeamName, "DefendersGuard") ~= 0 or KAS_TeamNamesEqual(TeamName, "CorvetteGuard") ~= 0) then     --kasfThisTeamIs(kasAITeamPtr("CorvetteGuard"))    --kasfThisTeamIs(kasAITeamPtr("DefendersGuard"))    --kasfThisTeamIs(kasAITeamPtr("FrigatesGuard"))    --kasfThisTeamIs(kasAITeamPtr("Destroyers"))
	
	--kasFSMCreate("Protection")
	KASRule_AddFSM(TeamName, "Watch_Mission15_Protection", "Watch_Mission15_WaitForCountDown")
	Init_Mission15_Protection(TeamName)
	elseif (KAS_TeamNamesEqual(TeamName, "FrgHarrass") ~= 0 or KAS_TeamNamesEqual(TeamName, "InterceptorsHarrass") ~= 0 or KAS_TeamNamesEqual(TeamName, "CorvetteHarass") ~= 0) then     --kasfThisTeamIs(kasAITeamPtr("CorvetteHarass"))    --kasfThisTeamIs(kasAITeamPtr("InterceptorsHarrass"))    --kasfThisTeamIs(kasAITeamPtr("FrgHarrass"))
	
	--kasFSMCreate("Harrass")
	KASRule_AddFSM(TeamName, "Watch_Mission15_Harrass", "Watch_Mission15_WaitForCountDown")
	Init_Mission15_Harrass(TeamName)
	end 
	end 
	
end 


--
--  "initialize" code for Mission15 mission
--
function Init_Mission15(MissionName)
	--FSM: FSM_Mission15
	--MissionName = "Mission15"
	G_HeadshotDestroyed = 0 --created,set
	G_CountdownTime = 390 --created,set
	G_Dist2MShip = 0 --created,set
	--kasFSMCreate("Events")
	KASRule_AddFSM("Events", "Watch_Mission15_Events", "Init_Mission15")
	Init_Mission15_Events("Events")
	--kasFSMCreate("HeadShot")
	KASRule_AddFSM("HeadShot", "Watch_Mission15_HeadShot", "Init_Mission15")
	Init_Mission15_HeadShot("HeadShot")
	--kasFSMCreate("WaitForCountDown")
	KASRule_AddFSM("Destroyers", "Watch_Mission15_WaitForCountDown", "Init_Mission15")
	Init_Mission15_WaitForCountDown("Destroyers")
	--kasFSMCreate("WaitForCountDown")
	KASRule_AddFSM("FrigatesGuard", "Watch_Mission15_WaitForCountDown", "Init_Mission15")
	Init_Mission15_WaitForCountDown("FrigatesGuard")
	--kasFSMCreate("WaitForCountDown")
	KASRule_AddFSM("DefendersGuard", "Watch_Mission15_WaitForCountDown", "Init_Mission15")
	Init_Mission15_WaitForCountDown("DefendersGuard")
	--kasFSMCreate("WaitForCountDown")
	KASRule_AddFSM("FrgHarrass", "Watch_Mission15_WaitForCountDown", "Init_Mission15")
	Init_Mission15_WaitForCountDown("FrgHarrass")
	--kasFSMCreate("WaitForCountDown")
	KASRule_AddFSM("InterceptorsHarrass", "Watch_Mission15_WaitForCountDown", "Init_Mission15")
	Init_Mission15_WaitForCountDown("InterceptorsHarrass")
	--kasFSMCreate("WaitForCountDown")
	KASRule_AddFSM("CorvetteGuard", "Watch_Mission15_WaitForCountDown", "Init_Mission15")
	Init_Mission15_WaitForCountDown("CorvetteGuard")
	--kasFSMCreate("WaitForCountDown")
	KASRule_AddFSM("CorvetteHarass", "Watch_Mission15_WaitForCountDown", "Init_Mission15")
	Init_Mission15_WaitForCountDown("CorvetteHarass")
	SobGroup_Clear("GrowSelection_EnemyMShip")    --kasfGrowSelectionClear(kasGrowSelectionPtr("EnemyMShip"))
	KAS_FindPlayerShipsOfType("GrowSelection_EnemyMShip", "Mothership", 0)    --kasfFindEnemyShipsOfType(kasGrowSelectionPtr("EnemyMShip"), "Mothership")
	KAS_CampaignAutoSave(15, "$61751")    --kasfSaveLevel(15, LSTRING_LevelName[strCurLanguage])
	
end 


--
--  "watch" code for Mission15 mission
--
function Watch_Mission15(MissionName)
	--FSM: FSM_Mission15
	--MissionName = "Mission15"
	if (_VIFONCE020 == 0 and (KAS_PlayerHasResearch(0, "CorvetteDrive") ~= 0)) then  -- "ifonce" #20    --kasfDoesPlayerHave("MassDrive10Kt")
	
	_VIFONCE020 = 1 --created,set;
	KAS_UnrestrictResearchOption(0, "CorvetteChassis")    --kasfAllowPlayerToResearch("Chassis2")
	end 
	if ((KAS_PlayerHasResearch(0, "CorvetteChassis") ~= 0) and (SetMediumGuns == 0)) then     --kasfDoesPlayerHave("Chassis2")
	
	KAS_UnrestrictResearchOption(0, "HeavyCorvetteUpgrade")    --kasfAllowPlayerToResearch("MediumGuns")
	SetMediumGuns = 1 --created,set
	end 
	if (_VIFONCE021 == 0 and (KAS_PlayerHasResearch(0, "FighterChassis") ~= 0)) then  -- "ifonce" #21    --kasfDoesPlayerHave("Chassis1")
	
	_VIFONCE021 = 1 --created,set;
	KAS_UnrestrictResearchOption(0, "CorvetteDrive")    --kasfAllowPlayerToResearch("MassDrive10Kt")
	end 
	
end 

function OnStartOrLoad()
    print("OnStartOrLoad issued")

    --Mission-global GrowSelections/SobGroups
    KASSobGroup_Create("GrowSelection_EnemyMShip")
    KASSobGroup_Create("GrowSelection_Evaluate")
    KASSobGroup_Create("GrowSelection_FirstAttackingShips")
    KASSobGroup_Create("GrowSelection_HEval")
    KASSobGroup_Create("GrowSelection_Mothership")
    KASSobGroup_CreateIfNotExist("CorvetteGuard")
    KASSobGroup_CreateIfNotExist("CorvetteHarass")
    KASSobGroup_CreateIfNotExist("DefendersGuard")
    KASSobGroup_CreateIfNotExist("Destroyers")
    KASSobGroup_CreateIfNotExist("Events")
    KASSobGroup_CreateIfNotExist("FrgHarrass")
    KASSobGroup_CreateIfNotExist("FrigatesGuard")
    KASSobGroup_CreateIfNotExist("HeadShot")
    KASSobGroup_CreateIfNotExist("InterceptorsHarrass")

    Sound_SpeechSubtitlePath("speech:missions/Mission15/")
    Scar_TracesEnable("SGAction, SGQuery, Camera, ATI, Player")

    LCWatcher_SpecifyLocalFilter(LC_Scar, "_VIFONCE;CorvetteGuard;CorvetteHarass;DefendersGuard;Destroyers;Events;FrgHarrass;FrigatesGuard;HeadShot;InterceptorsHarrass;Events;CorvetteGuard;CorvetteHarass;DefendersGuard;Destroyers;FrgHarrass;FrigatesGuard;InterceptorsHarrass;HeadShot;CorvetteGuard;CorvetteHarass;DefendersGuard;Destroyers;FrgHarrass;FrigatesGuard;InterceptorsHarrass;CorvetteGuard;CorvetteHarass;DefendersGuard;Destroyers;FrgHarrass;FrigatesGuard;InterceptorsHarrass;")
    KAS_SetColourSchemeColours(1, {1,0.823529411764706,0}, {1, 0, 0}, "DATA:Badges/Taiidan.tga", {0.921,0.75,0.419}, "data:/effect/trails/tai_trail_clr.tga")
    Player_SetTeamColourTheme(1, {1,0.823529411764706,0}, {1, 0, 0}, "DATA:Badges/Taiidan.tga", {0.921,0.75,0.419}, "data:/effect/trails/tai_trail_clr.tga")
    Player_SetTeamColourTheme(3, {1,0.823529411764706,0}, {1, 0, 0}, "DATA:Badges/Taiidan.tga", {0.921,0.75,0.419}, "data:/effect/trails/tai_trail_clr.tga")
    KAS_SetColourScheme("CorvetteGuard", 1)
    KAS_SetColourScheme("CorvetteHarass", 1)
    KAS_SetColourScheme("DefendersGuard", 1)
    KAS_SetColourScheme("Destroyers", 1)
    KAS_SetColourScheme("FrgHarrass", 1)
    KAS_SetColourScheme("FrigatesGuard", 1)
    KAS_SetColourScheme("HeadShot", 1)
    KAS_SetColourScheme("InterceptorsHarrass", 1)
    Player_SetPlayerName(1, "$60715")
    Player_SetPlayerName(3, "$60715")

    singlePlayerOnStartOrLoad(15)
end

function OnInit()
    print("OnInit issued")

    Player_RestrictAllResearch(0, 1)
    SobGroup_LoadPersistantData("Kus_Mothership")
    Camera_Interpolate('here', 'Camera_Startpos', 0)
    KAS_RememberStartingRUs()
    singlePlayerStartGame(15)
    KAS_CPUPlayerInit()

    KASRule_Add("Mission15", "Watch_Mission15", "OnInit")
    Init_Mission15("Mission15")
    KAS_SetLetterboxStart(1, 5, 1, 1)
    singlePlayerPauseUntilHyperspaceComplete("OnInit_Finish()")
	HW2_ReactiveInfo() --Added for info in log file
end

function OnInit_Finish()
    print("OnInit_Finish issued")

    KAS_MusicPlayType( "data:sound/music/ambient/A09_mission11and15", MUS_Ambient )
    KAS_SetFormation("CorvetteGuard", "Wall")
    KAS_SetFormation("CorvetteHarass", "Wall")
    KAS_SetFormation("DefendersGuard", "Wall")
    KAS_SetFormation("Destroyers", "Broad")
    KAS_SetFormation("FrgHarrass", "Broad")
    KAS_SetFormation("FrigatesGuard", "Broad")
    KAS_SetFormation("InterceptorsHarrass", "Claw")
end

