-- ============================================================================= 
-- Homeworld 2 Clean Data Resource Project
-- By S110
-- Version 1.0
-- 02/06/2010
-- Tools used: EditPad Lite, LuaDC version 0.9.19, and Cold Fusion LUA Decompiler v1.0.0
-- =============================================================================

BUILDCOLOR = {244, 213, 0, 255}
RESEARCHCOLOR = {124, 200, 196, 255}
LAUNCHCOLOR = {83, 202, 0, 255}

NewTaskbar = {size = {0, 498, 800, 102}, stylesheet = "HW2StyleSheet", pixelUVCoords = 1, callUpdateWhenInactive = 1, minimizedPos = {0, 565}, fstringShipCount = "$2764", healthBarGoodColor = {0, 255, 0, 255}, healthBarPoorColor = {255, 255, 0, 255}, healthBarFatalColor = {255, 0, 0, 255}, healthBarBackgroundColor = {128, 128, 128, 255}, healthBarEnemyColor = {255, 0, 0, 255}, healthBarEnemyBackgroundColor = {128, 0, 0, 255}, healthBarAlliedBackgroundColor = {255, 255, 0, 255}, healthBarAlliedBackgroundColor = {128, 0, 0, 255}, soundOnShow = "SFX_TaksbarMenuONOFF", soundOnHide = "SFX_TaksbarMenuONOFF", Regions = {{0, 15, 221, 87}, {220, 0, 363, 102}, {581, 15, 219, 87},}, ;
	{type = "Frame", name = "blackBg", position = {0, 16}, size = {800, 86}, backgroundColor = {0, 0, 0, 0}, giveParentMouseInput = 1},
	{type = "Frame", position = {0, 0}, size = {800, 102}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\background.mres", textureUV = {0, 0, 800, 102},}, giveParentMouseInput = 1},
	{type = "TextButton", position = {220, 3}, buttonStyle = "Taskbar_ControlGroups1ButtonStyle", Text = {text = "1"}, name = "btnControlGroup1", onMouseClicked = "MainUI_UserEventData( eSelectGroup, 1)", onMouseDoubleClicked = "MainUI_UserEvent( eFocus)", helpTip = "$2761", helpTipTextLabel = "commandsHelpTip", DefaultGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\controlgroups.mres", textureUV = {0, 0, 33, 11}, color = {0, 160, 255, 0},},},
	{type = "TextButton", position = {247, 3}, buttonStyle = "Taskbar_ControlGroups1ButtonStyle", Text = {text = "2"}, name = "btnControlGroup2", onMouseClicked = "MainUI_UserEventData( eSelectGroup, 2)", onMouseDoubleClicked = "MainUI_UserEvent( eFocus)", helpTip = "$2761", helpTipTextLabel = "commandsHelpTip", DefaultGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\controlgroups.mres", textureUV = {0, 0, 33, 11}, color = {0, 160, 255, 0},},},
	{type = "TextButton", position = {274, 3}, buttonStyle = "Taskbar_ControlGroups1ButtonStyle", Text = {text = "3"}, name = "btnControlGroup3", onMouseClicked = "MainUI_UserEventData( eSelectGroup, 3)", onMouseDoubleClicked = "MainUI_UserEvent( eFocus)", helpTip = "$2761", helpTipTextLabel = "commandsHelpTip", DefaultGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\controlgroups.mres", textureUV = {0, 0, 33, 11}, color = {0, 160, 255, 0},},},
	{type = "TextButton", position = {301, 3}, buttonStyle = "Taskbar_ControlGroups1ButtonStyle", Text = {text = "4"}, name = "btnControlGroup4", onMouseClicked = "MainUI_UserEventData( eSelectGroup, 4)", onMouseDoubleClicked = "MainUI_UserEvent( eFocus)", helpTip = "$2761", helpTipTextLabel = "commandsHelpTip", DefaultGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\controlgroups.mres", textureUV = {0, 0, 33, 11}, color = {0, 160, 255, 0},},},
	{type = "TextButton", position = {328, 3}, buttonStyle = "Taskbar_ControlGroups1ButtonStyle", Text = {text = "5"}, name = "btnControlGroup5", onMouseClicked = "MainUI_UserEventData( eSelectGroup, 5)", onMouseDoubleClicked = "MainUI_UserEvent( eFocus)", helpTip = "$2761", helpTipTextLabel = "commandsHelpTip", DefaultGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\controlgroups.mres", textureUV = {0, 0, 33, 11}, color = {0, 160, 255, 0},},},
	{type = "TextButton", position = {442, 3}, buttonStyle = "Taskbar_ControlGroups2ButtonStyle", Text = {text = "6"}, name = "btnControlGroup6", onMouseClicked = "MainUI_UserEventData( eSelectGroup, 6)", onMouseDoubleClicked = "MainUI_UserEvent( eFocus)", helpTip = "$2761", helpTipTextLabel = "commandsHelpTip", DefaultGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\controlgroups.mres", textureUV = {33, 0, 0, 11}, color = {0, 160, 255, 0},},},
	{type = "TextButton", position = {469, 3}, buttonStyle = "Taskbar_ControlGroups2ButtonStyle", Text = {text = "7"}, name = "btnControlGroup7", onMouseClicked = "MainUI_UserEventData( eSelectGroup, 7)", onMouseDoubleClicked = "MainUI_UserEvent( eFocus)", helpTip = "$2761", helpTipTextLabel = "commandsHelpTip", DefaultGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\controlgroups.mres", textureUV = {33, 0, 0, 11}, color = {0, 160, 255, 0},},},
	{type = "TextButton", position = {496, 3}, buttonStyle = "Taskbar_ControlGroups2ButtonStyle", Text = {text = "8"}, name = "btnControlGroup8", onMouseClicked = "MainUI_UserEventData( eSelectGroup, 8)", onMouseDoubleClicked = "MainUI_UserEvent( eFocus)", helpTip = "$2761", helpTipTextLabel = "commandsHelpTip", DefaultGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\controlgroups.mres", textureUV = {33, 0, 0, 11}, color = {0, 160, 255, 0},},},
	{type = "TextButton", position = {523, 3}, buttonStyle = "Taskbar_ControlGroups2ButtonStyle", Text = {text = "9"}, name = "btnControlGroup9", onMouseClicked = "MainUI_UserEventData( eSelectGroup, 9)", onMouseDoubleClicked = "MainUI_UserEvent( eFocus)", helpTip = "$2761", helpTipTextLabel = "commandsHelpTip", DefaultGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\controlgroups.mres", textureUV = {33, 0, 0, 11}, color = {0, 160, 255, 0},},},
	{type = "TextButton", position = {550, 3}, buttonStyle = "Taskbar_ControlGroups2ButtonStyle", Text = {text = "10"}, name = "btnControlGroup10", onMouseClicked = "MainUI_UserEventData( eSelectGroup, 10)", onMouseDoubleClicked = "MainUI_UserEvent( eFocus)", helpTip = "$2761", helpTipTextLabel = "commandsHelpTip", DefaultGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\controlgroups.mres", textureUV = {33, 0, 0, 11}, color = {0, 160, 255, 0},},},
	{type = "Button", position = {356, 3}, size = {91, 11}, DefaultGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\hide1.tga", textureUV = {0, 0, 182, 22},}, OverGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\hide1_OVER.tga", textureUV = {0, 0, 182, 22},}, name = "btnHide1", helpTip = "$2738", helpTipTextLabel = "commandsHelpTip", hotKeyID = 55},
	{type = "Button", position = {356, 3}, size = {91, 11}, visible = 0, DefaultGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\hide2.tga", textureUV = {0, 0, 182, 22},}, OverGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\hide2_OVER.tga", textureUV = {0, 0, 182, 22},}, name = "btnHide2", helpTip = "$2739", helpTipTextLabel = "commandsHelpTip", hotKeyID = 55},
	{type = "TextButton", toggleButton = 1, position = {5, 19}, size = {68, 13}, buttonStyle = "Taskbar_PanelButtonStyle", backgroundColor = {0, 224, 255, 255}, overColor = {0, 224, 255, 255}, pressedColor = {0, 224, 255, 255}, textColor = {0, 224, 255, 255}, Text = {textStyle = "Taskbar_PanelButtonTextStyle", text = "$2705"}, name = "btnFleet", onMouseClicked = "UI_ToggleScreen( 'FleetMenu', 0)", helpTip = "$2740", helpTipTextLabel = "commandsHelpTip", clickedTextColor = {0, 0, 0, 255}, ClickedGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\panelbutton.tga", textureUV = {0, 0, 64, 13},},},
	{type = "TextButton", position = {83, 19}, size = {67, 13}, buttonStyle = "Taskbar_PanelButtonStyle", toggleButton = 1, Text = {textStyle = "Taskbar_PanelButtonTextStyle", text = "$2714"}, name = "btnStrike", onMousePressed = "UI_ToggleScreen( 'StrikeGroupsMenu', 0)", helpTip = "$2741", helpTipTextLabel = "commandsHelpTip", soundOnClicked = "", soundOnPressed = "SFX_ButtonClick", backgroundColor = {0, 224, 255, 255}, overColor = {0, 224, 255, 255}, pressedColor = {0, 224, 255, 255}, textColor = {0, 224, 255, 255}, clickedTextColor = {0, 0, 0, 255}, ClickedGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\panelbutton.tga", textureUV = {0, 0, 64, 13},},},
	{type = "TextButton", position = {152, 19}, size = {67, 13}, buttonStyle = "Taskbar_PanelButtonStyle", toggleButton = 1, Text = {textStyle = "Taskbar_PanelButtonTextStyle", text = "$2715"}, name = "btnTactics", onMousePressed = "UI_ToggleScreen( 'TacticsMenu', 0)", helpTip = "$2742", helpTipTextLabel = "commandsHelpTip", soundOnClicked = "", soundOnPressed = "SFX_ButtonClick", backgroundColor = {0, 224, 255, 255}, overColor = {0, 224, 255, 255}, pressedColor = {0, 224, 255, 255}, textColor = {0, 224, 255, 255}, clickedTextColor = {0, 0, 0, 255}, ClickedGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\panelbutton.tga", textureUV = {0, 0, 64, 13},},},
	{type = "TextButton", position = {229, 19}, size = {53, 13}, buttonStyle = "Taskbar_MenuButtonStyle", Text = {textStyle = "Taskbar_MenuButtonTextStyle", text = "$2707"}, name = "btnEvents", onMouseClicked = "UI_ToggleScreen( 'EventsScreen', 0)", helpTip = "$2743", helpTipTextLabel = "commandsHelpTip", hotKeyID = 140},
	{type = "TextButton", visible = 0, position = {229, 19}, size = {132, 13}, buttonStyle = "Taskbar_MenuButtonStyle_Wide", Text = {textStyle = "Taskbar_MenuButtonTextStyle", text = "$2707"}, name = "btnEvents_wide", onMouseClicked = "UI_ToggleScreen( 'EventsScreen', 0)", helpTip = "$2743", helpTipTextLabel = "commandsHelpTip", hotKeyID = 140},
	{type = "TextButton", position = {284, 19}, size = {77, 13}, buttonStyle = "Taskbar_MenuButtonStyle", Text = {textStyle = "Taskbar_MenuButtonTextStyle", text = "$2704"}, name = "btnObjectives", onMouseClicked = "UI_ToggleScreen( 'ObjectivesList', 0)", helpTip = "$2744", helpTipTextLabel = "commandsHelpTip", hotKeyID = 137},
	{type = "TextButton", position = {284, 19}, size = {77, 13}, buttonStyle = "Taskbar_MenuButtonStyle", Text = {textStyle = "Taskbar_MenuButtonTextStyle", text = "$2716"}, name = "btnChat", onMouseClicked = "UI_ToggleScreen( 'ChatScreen', 0)", helpTip = "$2747", helpTipTextLabel = "commandsHelpTip", hotKeyID = 131},
	{type = "TextButton", position = {363, 19}, size = {78, 13}, buttonStyle = "Taskbar_MenuButtonStyle", Text = {textStyle = "Taskbar_MenuButtonTextStyle", text = "$2703"}, name = "btnSensors", onMouseClicked = "MainUI_UserEvent( eSensorsManager)", helpTip = "$2745", helpTipTextLabel = "commandsHelpTip", hotKeyID = 54},
	{type = "TextButton", position = {443, 19}, size = {77, 13}, buttonStyle = "Taskbar_MenuButtonStyle", Text = {textStyle = "Taskbar_MenuButtonTextStyle", text = "$2713"}, name = "btnDiplomacy", onMouseClicked = "UI_ToggleScreen( 'DiplomacyScreen', 0)", helpTip = "$2746", helpTipTextLabel = "commandsHelpTip", hotKeyID = 141},
	{type = "TextButton", position = {443, 19}, size = {77, 13}, visible = 0, buttonStyle = "Taskbar_MenuButtonStyle", Text = {textStyle = "Taskbar_MenuButtonTextStyle", text = "$2762"}, name = "btnRecall", onMouseClicked = "UI_ToggleScreen( 'SpeechRecall', 0)", helpTip = "$2763", helpTipTextLabel = "commandsHelpTip", hotKeyID = 142},
	{type = "TextButton", position = {522, 19}, size = {53, 13}, buttonStyle = "Taskbar_MenuButtonStyle", toggleButton = 0, Text = {textStyle = "Taskbar_MenuButtonTextStyle", text = "$2702"}, name = "btnMenu", onMouseClicked = "MainUI_UserEvent( eMenu )", helpTip = "$2774", helpTipTextLabel = "commandsHelpTip", hotKeyID = 4},
	{type = "TextButton", visible = 0, position = {443, 19}, size = {132, 13}, buttonStyle = "Taskbar_MenuButtonStyle_Wide", toggleButton = 0, Text = {textStyle = "Taskbar_MenuButtonTextStyle", text = "$2702"}, name = "btnMenu_wide", onMouseClicked = "MainUI_UserEvent( eMenu )", helpTip = "$2774", helpTipTextLabel = "commandsHelpTip", hotKeyID = 4},
	{type = "TextButton", toggleButton = 1, position = {585, 19}, size = {68, 13}, buttonStyle = "Taskbar_PanelButtonStyle", backgroundColor = BUILDCOLOR, overColor = BUILDCOLOR, pressedColor = BUILDCOLOR, textColor = BUILDCOLOR, Text = {textStyle = "Taskbar_PanelButtonTextStyle", text = "$2700"}, name = "btnBuild", onMouseClicked = "MainUI_UserEventData( eBuildManager, 1)", helpTip = "$2748", helpTipTextLabel = "commandsHelpTip", hotKeyID = 50},
	{type = "TextButton", toggleButton = 1, position = {655, 19}, size = {69, 13}, buttonStyle = "Taskbar_PanelButtonStyle", backgroundColor = RESEARCHCOLOR, overColor = RESEARCHCOLOR, pressedColor = RESEARCHCOLOR, textColor = RESEARCHCOLOR, Text = {textStyle = "Taskbar_PanelButtonTextStyle", text = "$2701"}, name = "btnResearch", onMouseClicked = "MainUI_UserEvent( eResearchManager)", helpTip = "$2749", helpTipTextLabel = "commandsHelpTip", hotKeyID = 49},
	{type = "TextButton", toggleButton = 1, position = {726, 19}, size = {69, 13}, buttonStyle = "Taskbar_PanelButtonStyle", backgroundColor = LAUNCHCOLOR, overColor = LAUNCHCOLOR, pressedColor = LAUNCHCOLOR, textColor = LAUNCHCOLOR, Text = {textStyle = "Taskbar_PanelButtonTextStyle", text = "$2706"}, name = "btnLaunch", onMouseClicked = "MainUI_UserEventData( eLaunchManager, 1)", helpTip = "$2760", helpTipTextLabel = "commandsHelpTip", hotKeyID = 52},
	{type = "TextLabel", name = "commandsHelpTip", position = {4, 1}, size = {214, 13}, Text = {textStyle = "Taskbar_MenuButtonTextStyle", color = {255, 255, 255, 255}, hAlign = "Left"},},
	{type = "Frame", position = {1, 38}, name = "commandButtons", autosize = 1, ;
	{type = "Frame", name = "commandButtonsFrame", autosize = 1, autoarrange = 1, autoarrangeWidth = 155, autoarrangeSpace = 1, ;
	{type = "Button", buttonStyle = "Taskbar_CommandButtonStyle", name = "btnMove", onMouseClicked = "MainUI_UserEvent( eMove)", helpTip = "$2717", helpTipTextLabel = "commandsHelpTip", hotKeyID = 10, ;
	{type = "Frame", size = {30, 30}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {1, 1, 31, 31},}, DisabledGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {1, 1, 31, 31}, color = {90, 155, 211, 160}, blackAndWhite = 1}, giveParentMouseInput = 1},},
	{type = "Button", buttonStyle = "Taskbar_CommandButtonStyle", name = "btnAttack", onMouseClicked = "MainUI_UserEventData( eControlModifier, 0)", helpTip = "$2718", helpTipTextLabel = "commandsHelpTip", hotKeyID = 115, ;
	{type = "Frame", size = {30, 30}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {33, 1, 63, 31},}, DisabledGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {33, 1, 63, 31}, color = {90, 155, 211, 160}, blackAndWhite = 1}, giveParentMouseInput = 1},},
	{type = "Button", buttonStyle = "Taskbar_CommandButtonStyle", name = "btnAttackMove", onMouseClicked = "MainUI_UserEvent( eMoveAttack )", helpTip = "$2724", helpTipTextLabel = "commandsHelpTip", hotKeyID = 25, ;
	{type = "Frame", size = {30, 30}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {129, 97, 159, 127},}, DisabledGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {129, 97, 159, 127}, color = {90, 155, 211, 160}, blackAndWhite = 1}, giveParentMouseInput = 1},},
	{type = "Button", buttonStyle = "Taskbar_CommandButtonStyle", name = "btnGuard", onMouseClicked = "MainUI_UserEvent( eGuard)", helpTip = "$2719", helpTipTextLabel = "commandsHelpTip", hotKeyID = 14, ;
	{type = "Frame", size = {30, 30}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {65, 1, 95, 31},}, DisabledGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {65, 1, 95, 31}, color = {90, 155, 211, 160}, blackAndWhite = 1}, giveParentMouseInput = 1},},
	{type = "Button", buttonStyle = "Taskbar_CommandButtonStyle", name = "btnDock", onMouseClicked = "MainUI_UserEvent( eDock)", helpTip = "$2720", helpTipTextLabel = "commandsHelpTip", hotKeyID = 15, ;
	{type = "Frame", size = {30, 30}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {97, 1, 127, 31},}, DisabledGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {97, 1, 127, 31}, color = {90, 155, 211, 160}, blackAndWhite = 1}, giveParentMouseInput = 1},},
	{type = "Button", buttonStyle = "Taskbar_CommandButtonStyle", name = "btnCancelOrders", onMouseClicked = "MainUI_UserEvent( eCancelOrders)", helpTip = "$2722", helpTipTextLabel = "commandsHelpTip", hotKeyID = 17, ;
	{type = "Frame", size = {30, 30}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {33, 97, 63, 127},}, DisabledGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {33, 97, 63, 127}, color = {90, 155, 211, 160}, blackAndWhite = 1}, giveParentMouseInput = 1},},
	{type = "Button", buttonStyle = "Taskbar_CommandButtonStyle", name = "btnWaypoint", onMouseClicked = "MainUI_UserEvent( eTempWaypoint)", helpTip = "$2727", helpTipTextLabel = "commandsHelpTip", hotKeyID = 56, ;
	{type = "Frame", size = {30, 30}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {97, 33, 127, 63},}, DisabledGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {97, 33, 127, 63}, color = {90, 155, 211, 160}, blackAndWhite = 1}, giveParentMouseInput = 1},},
	{type = "Button", buttonStyle = "Taskbar_CommandButtonStyle", name = "btnResource", onMouseClicked = "MainUI_UserEventData( eHarvest, 0); MainUI_UserEventData( eHarvest, 1);", helpTip = "$2723", helpTipTextLabel = "commandsHelpTip", hotKeyID = 12, ;
	{type = "Frame", size = {30, 30}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {1, 33, 31, 63},}, DisabledGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {1, 33, 31, 63}, color = {90, 155, 211, 160}, blackAndWhite = 1}, giveParentMouseInput = 1},},
	{type = "Button", buttonStyle = "Taskbar_CommandButtonStyle", name = "btnHyperspace", onMouseClicked = "MainUI_UserEvent( eHyperspace)", helpTip = "$2725", helpTipTextLabel = "commandsHelpTip", hotKeyID = 11, ;
	{type = "Frame", size = {30, 30}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {33, 33, 63, 63},}, DisabledGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {33, 33, 63, 63}, color = {90, 155, 211, 160}, blackAndWhite = 1}, giveParentMouseInput = 1},},
	{type = "Button", buttonStyle = "Taskbar_CommandButtonStyle", name = "btnRetire", onMouseClicked = "MainUI_UserEvent( eRetire)", helpTip = "$2728", helpTipTextLabel = "commandsHelpTip", hotKeyID = 23, ;
	{type = "Frame", size = {30, 30}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {129, 33, 159, 63},}, DisabledGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {129, 33, 159, 63}, color = {90, 155, 211, 160}, blackAndWhite = 1}, giveParentMouseInput = 1},},},
	{type = "Button", position = {157, 2}, size = {13, 59}, DefaultGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\special.tga", textureUV = {0, 0, 13, 59},}, OverGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\special_OVER.tga", textureUV = {0, 0, 13, 59},}, name = "btnSpecial", helpTip = "$2729", helpTipTextLabel = "commandsHelpTip", hotKeyID = 150, onMouseClicked =  [[UI_SetElementVisible("NewTaskbar", "specialButtons", 1); UI_SetElementVisible("NewTaskbar", "commandButtons", 0);]], soundOnClicked = "SFX_ButtonClick"},},
	{type = "Frame", position = {1, 38}, name = "specialButtons", visible = 0, autosize = 1, ;
	{type = "Frame", name = "specialButtonsFrame", autosize = 1, autoarrange = 1, autoarrangeWidth = 155, autoarrangeSpace = 1, ;
	{type = "Button", buttonStyle = "Taskbar_CommandButtonStyle", name = "btnPing", onMouseClicked = "MainUI_UserEvent( eSensorPing)", helpTip = "$2769", helpTipTextLabel = "commandsHelpTip", hotKeyID = 147, ;
	{type = "Frame", size = {30, 30}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {129, 65, 159, 95},}, DisabledGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {129, 65, 159, 95}, color = {90, 155, 211, 160}, blackAndWhite = 1}, giveParentMouseInput = 1},},
	{type = "Button", buttonStyle = "Taskbar_CommandButtonStyle", name = "btnEMP", onMouseClicked = "MainUI_UserEventData2( eSpecialAttack, 0, 2)", helpTip = "$2768", helpTipTextLabel = "commandsHelpTip", hotKeyID = 146, ;
	{type = "Frame", size = {30, 30}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {97, 65, 127, 95},}, DisabledGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {97, 65, 127, 95}, color = {90, 155, 211, 160}, blackAndWhite = 1}, giveParentMouseInput = 1},},
	{type = "Button", buttonStyle = "Taskbar_CommandButtonStyle", name = "btnDefenseField", onMouseClicked = "MainUI_UserEvent( eDefenseField)", helpTip = "$2765", helpTipTextLabel = "commandsHelpTip", hotKeyID = 143, ;
	{type = "Frame", size = {30, 30}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {1, 65, 31, 95},}, DisabledGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {1, 65, 31, 95}, color = {90, 155, 211, 160}, blackAndWhite = 1}, giveParentMouseInput = 1},},
	{type = "Button", buttonStyle = "Taskbar_CommandButtonStyle", name = "btnCloak", onMouseClicked = "MainUI_UserEvent( eCloak)", helpTip = "$2766", helpTipTextLabel = "commandsHelpTip", hotKeyID = 144, ;
	{type = "Frame", size = {30, 30}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {33, 65, 63, 95},}, DisabledGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {33, 65, 63, 95}, color = {90, 155, 211, 160}, blackAndWhite = 1}, giveParentMouseInput = 1},},
	{type = "Button", buttonStyle = "Taskbar_CommandButtonStyle", name = "btnScuttleConfirm", onMouseClicked =  [[MainUI_UserEvent( eScuttle); UI_SetElementVisible("NewTaskbar", "scuttleButtons", 0); UI_SetElementVisible("NewTaskbar", "specialButtons", 1);]], helpTip = "$2759", helpTipTextLabel = "commandsHelpTip", enabled = 0, ;
	{type = "Frame", size = {30, 30}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {225, 97, 255, 127},}, DisabledGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {225, 97, 255, 127}, color = {90, 155, 211, 160}, blackAndWhite = 1}, giveParentMouseInput = 1},},
	{type = "Button", buttonStyle = "Taskbar_CommandButtonStyle", name = "btnRepair", onMouseClicked = "MainUI_UserEvent( eRepair)", helpTip = "$2726", helpTipTextLabel = "commandsHelpTip", hotKeyID = 20, ;
	{type = "Frame", size = {30, 30}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {65, 33, 95, 63},}, DisabledGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {65, 33, 95, 63}, color = {90, 155, 211, 160}, blackAndWhite = 1}, giveParentMouseInput = 1},},
	{type = "Button", buttonStyle = "Taskbar_CommandButtonStyle", name = "btnMines", onMouseClicked = "MainUI_UserEvent( eDropMinesInstant)", helpTip = "$2772", helpTipTextLabel = "commandsHelpTip", hotKeyID = 24, ;
	{type = "Frame", size = {30, 30}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {65, 97, 95, 127},}, DisabledGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {65, 97, 95, 127}, color = {90, 155, 211, 160}, blackAndWhite = 1}, giveParentMouseInput = 1},},
	{type = "Button", buttonStyle = "Taskbar_CommandButtonStyle", name = "btnRally", onMouseClicked = "MainUI_UserEvent( eRallyPoint)", helpTip = "$2721", helpTipTextLabel = "commandsHelpTip", hotKeyID = 138, ;
	{type = "Frame", size = {30, 30}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {129, 1, 159, 31},}, DisabledGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {129, 1, 159, 31}, color = {90, 155, 211, 160}, blackAndWhite = 1}, giveParentMouseInput = 1},},
	{type = "Button", buttonStyle = "Taskbar_CommandButtonStyle", name = "btnRallyObject", onMouseClicked = "MainUI_UserEventData( eRallyObject, 0 )", helpTip = "$2767", helpTipTextLabel = "commandsHelpTip", hotKeyID = 22, ;
	{type = "Frame", size = {30, 30}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {1, 97, 31, 127},}, DisabledGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {1, 97, 31, 127}, color = {90, 155, 211, 160}, blackAndWhite = 1}, giveParentMouseInput = 1},},
	{type = "Button", buttonStyle = "Taskbar_CommandButtonStyle", name = "btnScuttle", onMouseClicked =  [[UI_SetElementVisible("NewTaskbar", "scuttleButtons", 1); UI_SetElementVisible("NewTaskbar", "specialButtons", 0);]], helpTip = "$2773", helpTipTextLabel = "commandsHelpTip", hotKeyID = 5, ;
	{type = "Frame", size = {30, 30}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {97, 97, 127, 127},}, DisabledGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {97, 97, 127, 127}, color = {90, 155, 211, 160}, blackAndWhite = 1}, giveParentMouseInput = 1},},},
	{type = "Button", position = {157, 2}, size = {13, 59}, DefaultGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\special.tga", textureUV = {0, 0, 13, 59},}, OverGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\special_OVER.tga", textureUV = {0, 0, 13, 59},}, name = "btnSpecial", helpTip = "$2729", helpTipTextLabel = "commandsHelpTip", hotKeyID = 150, onMouseClicked =  [[UI_SetElementVisible("NewTaskbar", "specialButtons", 0); UI_SetElementVisible("NewTaskbar", "commandButtons", 1);]], soundOnClicked = "SFX_ButtonClick"},},
	{type = "Frame", position = {1, 38}, name = "scuttleButtons", visible = 0, autosize = 1, ;
	{type = "TextLabel", position = {40, 7}, size = {80, 30}, wrapping = 1, Text = {font = "ButtonFont", text = "$2712", hAlign = "Right", vAlign = "Top", color = {255, 255, 255, 255},},},
	{type = "Frame", position = {124, 0}, autosize = 1, autoarrange = 1, autoarrangeSpace = 1, ;
	{type = "Button", buttonStyle = "Taskbar_CommandButtonStyle", name = "btnScuttleConfirm", onMouseClicked =  [[MainUI_UserEvent( eScuttle); UI_SetElementVisible("NewTaskbar", "scuttleButtons", 0); UI_SetElementVisible("NewTaskbar", "specialButtons", 1);]], helpTip = "$2759", helpTipTextLabel = "commandsHelpTip", ;
	{type = "Frame", size = {30, 30}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {225, 97, 255, 127},}, DisabledGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {225, 97, 255, 127}, color = {90, 155, 211, 160}, blackAndWhite = 1}, giveParentMouseInput = 1},},
	{type = "Button", buttonStyle = "Taskbar_CommandButtonStyle", name = "btnScuttleCancel", onMouseClicked =  [[UI_SetElementVisible("NewTaskbar", "scuttleButtons", 0); UI_SetElementVisible("NewTaskbar", "specialButtons", 1);]], helpTip = "$2613", helpTipTextLabel = "commandsHelpTip", ;
	{type = "Frame", size = {30, 30}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {161, 1, 191, 31},}, DisabledGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\command_icons.mres", textureUV = {161, 1, 191, 31}, color = {90, 155, 211, 160}, blackAndWhite = 1}, giveParentMouseInput = 1},},},
	{type = "Button", position = {157, 2}, size = {13, 59}, DefaultGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\special.tga", textureUV = {0, 0, 13, 59},}, OverGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\special_OVER.tga", textureUV = {0, 0, 13, 59},}, name = "btnSpecial", helpTip = "$2729", helpTipTextLabel = "commandsHelpTip", onMouseClicked =  [[UI_SetElementVisible("NewTaskbar", "scuttleButtons", 0); UI_SetElementVisible("NewTaskbar", "specialButtons", 1);]], soundOnClicked = "SFX_ButtonClick"},},
	{type = "Frame", position = {179, 38}, size = {590, 64}, autoarrange = 1, autoarrangeWidth = 590, autoarrangeSpace = 1, ;
	{type = "Button", buttonStyle = "Taskbar_ShipButtonStyle", name = "btnShip13"},
	{type = "Button", buttonStyle = "Taskbar_ShipButtonStyle", name = "btnShip11"},
	{type = "Button", buttonStyle = "Taskbar_ShipButtonStyle", name = "btnShip09"},
	{type = "Button", buttonStyle = "Taskbar_ShipButtonStyle", name = "btnShip07"},
	{type = "Button", buttonStyle = "Taskbar_ShipButtonStyle", name = "btnShip05"},
	{type = "Button", buttonStyle = "Taskbar_ShipButtonStyle", name = "btnShip03"},
	{type = "Button", buttonStyle = "Taskbar_ShipButtonStyle", name = "btnShip01"},
	{type = "Button", buttonStyle = "Taskbar_ShipButtonStyle", name = "btnShip14"},
	{type = "Button", buttonStyle = "Taskbar_ShipButtonStyle", name = "btnShip12"},
	{type = "Button", buttonStyle = "Taskbar_ShipButtonStyle", name = "btnShip10"},
	{type = "Button", buttonStyle = "Taskbar_ShipButtonStyle", name = "btnShip08"},
	{type = "Button", buttonStyle = "Taskbar_ShipButtonStyle", name = "btnShip06"},
	{type = "Button", buttonStyle = "Taskbar_ShipButtonStyle", name = "btnShip04"},
	{type = "Button", buttonStyle = "Taskbar_ShipButtonStyle", name = "btnShip02"},},
	{type = "Button", position = {768, 40}, size = {13, 28}, DefaultGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\shipnext.tga", textureUV = {0, 0, 13, 28},}, OverGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\shipnext_OVER.tga", textureUV = {0, 0, 13, 28},}, DisabledGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\shipnext.tga", textureUV = {0, 0, 13, 28}, color = {255, 255, 255, 128},}, name = "btnShipNext", helpTip = "$2731", helpTipTextLabel = "commandsHelpTip", soundOnClicked = "SFX_ButtonClick"},
	{type = "Button", position = {768, 71}, size = {13, 28}, DefaultGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\shipprev.tga", textureUV = {0, 0, 13, 28},}, OverGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\shipprev_OVER.tga", textureUV = {0, 0, 13, 28},}, DisabledGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\shipprev.tga", textureUV = {0, 0, 13, 28}, color = {255, 255, 255, 128},}, name = "btnShipPrev", helpTip = "$2730", helpTipTextLabel = "commandsHelpTip", soundOnClicked = "SFX_ButtonClick"},
	{type = "Frame", position = {176, 37}, size = {620, 68}, name = "unitStats", ;
	{type = "Frame", position = {0, 2}, size = {608, 61}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\unitstats_border.mres", textureUV = {0, 0, 608, 61},},},
	{type = "Button", position = {211, 0}, size = {200, 64}, name = "unitIcon", backgroundGraphicHAlign = "Center", backgroundGraphicVAlign = "Center"},
	{type = "Frame", position = {215, 3}, size = {391, 59}, ;
	{type = "ProgressBar", backgroundColor = {0, 128, 0, 255}, progressColor = {0, 255, 0, 255}, borderColor = {0, 0, 0, 255}, outerBorderWidth = 1, position = {50, 50}, size = {100, 2}, name = "unitProgress"},
	{type = "Frame", name = "subsystems", position = {193, 5}, size = {210, 48}, autoarrange = 1, autoarrangeWidth = 210, ;
	{type = "Button", name = "subsystem1", buttonStyle = "Taskbar_SubsystemButtonStyle"},
	{type = "Button", name = "subsystem2", buttonStyle = "Taskbar_SubsystemButtonStyle"},
	{type = "Button", name = "subsystem3", buttonStyle = "Taskbar_SubsystemButtonStyle"},
	{type = "Button", name = "subsystem4", buttonStyle = "Taskbar_SubsystemButtonStyle"},
	{type = "Button", name = "subsystem5", buttonStyle = "Taskbar_SubsystemButtonStyle"},
	{type = "Button", name = "subsystem6", buttonStyle = "Taskbar_SubsystemButtonStyle"},
	{type = "Button", name = "subsystem7", buttonStyle = "Taskbar_SubsystemButtonStyle"},
	{type = "Button", name = "subsystem8", buttonStyle = "Taskbar_SubsystemButtonStyle"},
	{type = "Button", name = "subsystem9", buttonStyle = "Taskbar_SubsystemButtonStyle"},
	{type = "Button", name = "subsystem10", buttonStyle = "Taskbar_SubsystemButtonStyle"},
	{type = "Button", name = "subsystem11", buttonStyle = "Taskbar_SubsystemButtonStyle"},
	{type = "Button", name = "subsystem12", buttonStyle = "Taskbar_SubsystemButtonStyle"},},
	{type = "Button", name = "subsystem_production", visible = 0, size = {32, 24}, DefaultGraphic = {size = {32, 24}, texture = "DATA:UI\\NewUI\\Taskbar\\subsystem_button.mres", textureUV = {0, 0, 32, 24},}, OverGraphic = {size = {32, 24}, texture = "DATA:UI\\NewUI\\Taskbar\\subsystem_button.mres", textureUV = {0, 24, 32, 48},}, PressedGraphic = {size = {32, 24}, texture = "DATA:UI\\NewUI\\Taskbar\\subsystem_button.mres", textureUV = {0, 48, 32, 72},}, DisabledGraphic = {size = {32, 24}, texture = "DATA:UI\\NewUI\\Taskbar\\subsystem_button.mres", textureUV = {0, 0, 32, 24}, color = {255, 255, 255, 200},}, helpTip = "$2811", soundOnClicked = "SFX_ButtonClick"},
	{type = "Button", name = "subsystem_sensor", visible = 0, size = {32, 24}, DefaultGraphic = {size = {32, 24}, texture = "DATA:UI\\NewUI\\Taskbar\\subsystem_button.mres", textureUV = {32, 0, 64, 24},}, OverGraphic = {size = {32, 24}, texture = "DATA:UI\\NewUI\\Taskbar\\subsystem_button.mres", textureUV = {32, 24, 64, 48},}, PressedGraphic = {size = {32, 24}, texture = "DATA:UI\\NewUI\\Taskbar\\subsystem_button.mres", textureUV = {32, 48, 64, 72},}, DisabledGraphic = {size = {32, 24}, texture = "DATA:UI\\NewUI\\Taskbar\\subsystem_button.mres", textureUV = {32, 0, 64, 24}, color = {255, 255, 255, 200},}, helpTip = "$2813", soundOnClicked = "SFX_ButtonClick"},
	{type = "Button", name = "subsystem_generic", visible = 0, size = {32, 24}, DefaultGraphic = {size = {32, 24}, texture = "DATA:UI\\NewUI\\Taskbar\\subsystem_button.mres", textureUV = {64, 0, 96, 24},}, OverGraphic = {size = {32, 24}, texture = "DATA:UI\\NewUI\\Taskbar\\subsystem_button.mres", textureUV = {64, 24, 96, 48},}, PressedGraphic = {size = {32, 24}, texture = "DATA:UI\\NewUI\\Taskbar\\subsystem_button.mres", textureUV = {64, 48, 96, 72},}, DisabledGraphic = {size = {32, 24}, texture = "DATA:UI\\NewUI\\Taskbar\\subsystem_button.mres", textureUV = {64, 0, 96, 24}, color = {255, 255, 255, 200},}, helpTip = "$2812", soundOnClicked = "SFX_ButtonClick"},
	{type = "Button", name = "subsystem_innate", visible = 0, size = {32, 24}, DefaultGraphic = {size = {32, 24}, texture = "DATA:UI\\NewUI\\Taskbar\\subsystem_button.mres", textureUV = {96, 0, 128, 24},}, OverGraphic = {size = {32, 24}, texture = "DATA:UI\\NewUI\\Taskbar\\subsystem_button.mres", textureUV = {96, 24, 128, 48},}, PressedGraphic = {size = {32, 24}, texture = "DATA:UI\\NewUI\\Taskbar\\subsystem_button.mres", textureUV = {96, 48, 128, 72},}, DisabledGraphic = {size = {32, 24}, texture = "DATA:UI\\NewUI\\Taskbar\\subsystem_button.mres", textureUV = {96, 0, 128, 24}, color = {255, 255, 255, 200},}, helpTip = "$2814", soundOnClicked = "SFX_ButtonClick"},
	{type = "Frame", name = "subsystemselected", position = {93, 7}, size = {159, 45}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\subsystem_pointer.tga", textureUV = {0, 0, 159, 45},}, ;
	{type = "Frame", position = {104, 9}, size = {64, 32}, name = "subsystemIcon"},
	{type = "ProgressBar", backgroundColor = {0, 128, 0, 255}, progressColor = {0, 255, 0, 255}, position = {111, 6}, size = {40, 2}, name = "subsystemProgress"},},},
	{type = "Frame", position = {3, 3}, size = {220, 59}, autoarrange = 1, marginHeight = 4, ;
	{type = "Frame", autosize = 1, ;
	{type = "TextLabel", position = {5, 0}, size = {45, 13}, wrapping = 1, Text = {textStyle = "Taskbar_MenuButtonTextStyle", text = "$2708", hAlign = "Left", vAlign = "Top", color = {255, 255, 255, 255},},},
	{type = "TextLabel", position = {50, 0}, size = {161, 13}, wrapping = 1, autosize = 1, Text = {textStyle = "Taskbar_MenuButtonTextStyle", color = {238, 188, 5, 255}, hAlign = "Left", vAlign = "Top"}, name = "unitname"},},
	{type = "Frame", autosize = 1, ;
	{type = "TextLabel", position = {5, 0}, size = {45, 13}, wrapping = 1, Text = {textStyle = "Taskbar_MenuButtonTextStyle", text = "$2709", hAlign = "Left", vAlign = "Top", color = {255, 255, 255, 255},},},
	{type = "TextLabel", position = {50, 0}, size = {161, 13}, wrapping = 1, autosize = 1, Text = {textStyle = "Taskbar_MenuButtonTextStyle", color = {238, 188, 5, 255}, hAlign = "Left", vAlign = "Top"}, name = "unitrole"},},},
	{type = "Frame", position = {3, 45}, autosize = 1, autoarrange = 1, autoarrangeWidth = 300, ;
	{type = "Frame", name = "maxspeedframe", size = {67, 15}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\stats_box.mres", textureUV = {0, 0, 67, 15},}, helpTip = "$2711", helpTipTextLabel = "commandsHelpTip", ;
	{type = "Frame", position = {5, 3}, size = {9, 9}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\stats_icons.mres", textureUV = {0, 0, 9, 9},},},
	{type = "TextLabel", position = {19, 1}, size = {49, 13}, Text = {textStyle = "Taskbar_MenuButtonTextStyle", color = {0, 198, 0, 255}, hAlign = "Left", vAlign = "Center"}, name = "unitmaxspeed"},},
	{type = "Frame", name = "attackdamageframe", size = {67, 15}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\stats_box.mres", textureUV = {0, 0, 67, 15},}, helpTip = "$2710", helpTipTextLabel = "commandsHelpTip", ;
	{type = "Frame", position = {5, 3}, size = {9, 9}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\stats_icons.mres", textureUV = {11, 0, 20, 9},},},
	{type = "TextLabel", position = {19, 1}, size = {49, 13}, Text = {textStyle = "Taskbar_MenuButtonTextStyle", color = {222, 37, 19, 255}, hAlign = "Left", vAlign = "Center"}, name = "unitattackdamage"},},
	{type = "Frame", name = "shieldsframe", size = {67, 15}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\stats_box.mres", textureUV = {0, 0, 67, 15},}, helpTip = "$2770", helpTipTextLabel = "commandsHelpTip", ;
	{type = "Frame", position = {5, 3}, size = {9, 9}, BackgroundGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\stats_icons.mres", textureUV = {22, 0, 31, 9},},},
	{type = "TextLabel", position = {19, 1}, size = {49, 13}, Text = {textStyle = "Taskbar_MenuButtonTextStyle", color = {0, 128, 255, 255}, hAlign = "Left", vAlign = "Center"}, name = "unitshields"},},},},
	{type = "Button", position = {784, 40}, size = {13, 59}, DefaultGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\Taskbar_Icon_Back.tga", textureUV = {0, 0, 13, 59},}, OverGraphic = {texture = "DATA:UI\\NewUI\\Taskbar\\Taskbar_Icon_Back_OVER.tga", textureUV = {0, 0, 13, 59},}, name = "btnShipBack", helpTip = "$2732", helpTipTextLabel = "commandsHelpTip", enabled = 0, soundOnClicked = "SFX_ButtonClick"},}
