aitrace("LOADING VAYGR UPGRADE INFO")
rt_mothership = {
	MOTHERSHIPMAXSPEEDUPGRADE1,

}
rt_capital = {
	SUPERCAPHEALTHUPGRADE1,
	SUPERCAPSPEEDUPGRADE1,
}
rt_fighter = {
	
	FIGHTERSPEEDUPGRADE1,

}
rt_corvette = {
	
	CORVETTEHEALTHUPGRADE1,
	CORVETTESPEEDUPGRADE1,
}
rt_frigate = {
	FRIGATEHEALTHUPGRADE1,
	FRIGATESPEEDUPGRADE1,
}
rt_platform = {
	PLATFORMHEALTHUPGRADE1,
}
rt_collector = {
	UTILITYHEALTHUPGRADE1,
}
--rt_refinery = {
--	RESOURCECONTROLLERHEALTHUPGRADE1,
--	RESOURCECONTROLLERHEALTHUPGRADE2,
--}
--rt_hyperspace = {
--	cost = {
--		HYPERSPACECOSTUPGRADE1,
--		HYPERSPACECOSTUPGRADE2,
--	},
--	transittime = {
--		HYPERSPACETRANSITTIMEUPGRADE1,
--		HYPERSPACETRANSITTIMEUPGRADE2,
--	},
--	recoverytime = {
--		HYPERSPACERECOVERYTIMEUPGRADE1,
--		HYPERSPACERECOVERYTIMEUPGRADE2,
--	},
--}