speechSetDir("m06a")
at 0
    print("swapRaces")
    cameraBlendIn("Camera0", 6)
at frame 1
    SFXVolume(0.3)
    musicVolume(1.0)
    speechVolume(0.8)
    musicStart("50")
at 10
    wideScreenOut(2)
    focus()
    cameraBlendOut("Camera0", 2)
with Kus_Mothership
{
    at frame 0
        hide()
        centreShip()
}

with Ben_BentusiExchange
{
    at 0
        remainAtEnd("Traders")
        focusAtEnd()
        hide()
    at 0.5
        show()
}

