--
--  Generated\Mission11.c
--
--  Finite state machine routines for "Mission11" mission
--
--  Copyright (C) 1998 Relic Entertainment Inc.
--  All rights reserved
--
--  This code was autogenerated from Mission11.kp by KAS2C Version 2.05
--


--#include "Generated\Mission11.h"  -- prototypes and #includes for exposed game functions

--extern AITeam *CurrentTeamP;
--#define kasThisTeamPtr CurrentTeamP

--  for run-time scoping of symbols (variables, timers, etc.)


dofilepath("data:scripts/SCAR/SCAR_Util.lua")             --stock HW2 scripting utilities
dofilepath("data:scripts/SCAR/KASUtil.lua")               --HW1->HW2 scripting utilities
dofilepath("data:scripts/SCAR/SinglePlayerFlow.lua")      --Emulation of HW1 singleplayer functionality
dofilepath("data:scripts/SCAR/SinglePlayerNIS.lua")       --Emulation of HW1 singleplayer NIS functionality
dofilepath("data:scripts/SCAR/SinglePlayerHyperspace.lua")--Emulation of HW1 hyperspace logic
dofilepath("data:scripts/SCAR/SpecialFlags.lua")          --Emulation of HW1 SPECIAL_xxx logic


--kas global variables, including variables used in ifOnce blocks
EveryoneSHIPS = 0
G_CLICK_DestroyFleet = 0
G_CreateObjectiveNow = 0
G_FCDoneRasping = 0
G_GivePlayerSuperHeavy = 0
G_MissionComplete = 0
G_N07IsPlaying = 0
G_N08IsPlaying = 0
G_PlayN08Now = 0
G_PlayedN07 = 0
G_PlayedN08 = 0
G_PlayerHasAttackedTraders = 0
G_TradersGoNow = 0
G_TradersInPosition = 0
G_TradersObliteratePlayer = 0
MothershipSHIPS = 0
SetMediumGuns = 0
_VIFONCE017 = 0
_VIFONCE018 = 0
_VIFONCE019 = 0
_VIFONCE020 = 0
_VIFONCE021 = 0
_VIFONCE022 = 0
_VIFONCE023 = 0
_VIFONCE024 = 0
_VIFONCE025 = 0
_VIFONCE026 = 0
_VIFONCE027 = 0
_VIFONCE028 = 0
_VIFONCE029 = 0

--Following are global variables: created outside of the KAS structure and stubbed out here.
--G_Nis7Complete : see SinglePlayerFlow.lua, nReferences: 4
--G_Nis8Complete : see SinglePlayerFlow.lua, nReferences: 1
--G_PlayNis : see SinglePlayerFlow.lua, nReferences: 2

--Following are Team-Scoped variables: referenced differently than globals.
CurrentTraderHealth = {["Traders"] = 0}
KeepBentusiAliveForever = {["Traders"] = 0}
_VIFONCE001 = {["FleetIntel"] = 0}
_VIFONCE002 = {["FleetIntel"] = 0}
_VIFONCE003 = {["FleetIntel"] = 0}
_VIFONCE004 = {["FleetIntel"] = 0}
_VIFONCE005 = {["FleetIntel"] = 0}
_VIFONCE006 = {["FleetIntel"] = 0}
_VIFONCE007 = {["FleetIntel"] = 0}
_VIFONCE008 = {["FleetIntel"] = 0}
_VIFONCE009 = {["FleetIntel"] = 0}
_VIFONCE010 = {["FleetIntel"] = 0}
_VIFONCE011 = {["FleetIntel"] = 0}
_VIFONCE012 = {["Traders"] = 0}
_VIFONCE013 = {["Traders"] = 0}
_VIFONCE014 = {["Traders"] = 0}
_VIFONCE015 = {["Traders"] = 0}
_VIFONCE016 = {["Cruiser"] = 0, ["Destroyers"] = 0, ["IonCannonFrigates"] = 0}

--Following are Team-Scoped timers: referenced differently than globals.
KeepTraderShipAlive = {["Traders"] = 8}
PlayFinalEvent = {["FleetIntel"] = 9}
WideScreenInBeforeNIS2 = {["FleetIntel"] = 10}


--kas timer names, with mappings to indices
TimerID_CreateNISTeamsTimer = 5
TimerID_G_FCHyperspaceSuccessful = 1
TimerID_G_FIDefendTraders = 2
TimerID_G_GivePlayerTimeToWithdrawAttack = 0
TimerID_G_PlayTechEvent = 7
TimerID_G_TradersTalk = 3
TimerID_LocationCardTimer = 4
TimerID_WideScreenInBeforeNIS = 6


--KAS objective names, set by KASObjective_Add
ObjectiveID_DestroyFleet = 0
ObjectiveID_Hyperspace = 1
ObjectiveID_Count = 2


--extern sdword CurrentMissionScope;
--extern char CurrentMissionScopeName[];

--  for displaying localized strings
strCurLanguage = 1  --Naive treatement of localization language.;

LSTRING_Savegame = {  -- multilingual strings
	"11 - Tenhauser Gate",
	"11 - Porte de Tenhauser",
	"11 - Tenhauser-Tor",
	"11 - Puerta de Tannhauser",
	"11 - Il Portale di Tenhauser", }
LSTRING_LocationCard = {  -- multilingual strings
	"TENHAUSER GATE",
	"PORTE DE TENHAUSER",
	"TENHAUSER-TOR",
	"PUERTA DE TANNHAUSER",
	"IL PORTALE DI TENHAUSER", }
LSTRING_FIDestroyTaiidanTASKBAR = {  -- multilingual strings
	"Destroy the Taiidan fleet",
	"Destruction flotte Taiidan",
	"Die Taiidan-Flotte vernichten.",
	"Destruir la flota taiidana",
	"Distruggi la flotta dei Taiidan", }
LSTRING_FIDestroyKushanTASKBAR = {  -- multilingual strings
	"Destroy the Kushan fleet",
	"Destruction flotte Kushan",
	"Die Kushan-Flotte vernichten.",
	"Destruir la flota kushana",
	"Distruggi la flotta dei Kushan", }
LSTRING_Hyperspace = {  -- multilingual strings
	"                      HYPERSPACE",
	"                      HYPERESPACE",
	"           HYPERRAUMSPRUNG",
	"                    HIPERESPACIO",
	"					IPERSPAZIO", }

--
--  "initialize" code for Mission11 FleetIntel FSM
--
function Init_Mission11_FleetIntel(TeamName)
	--FSM: FSM_Mission11_FleetIntel
	--TeamName = FleetIntel
	--kasJump("FIIdle")
	KASRule_Add(TeamName, "Watch_Mission11_FleetIntel_FIIdle", "Init_Mission11_FleetIntel")
	Init_Mission11_FleetIntel_FIIdle(TeamName)
	return
	
end 


--
--  "watch" code for Mission11 FleetIntel FSM
--
function Watch_Mission11_FleetIntel(TeamName)
	--FSM: FSM_Mission11_FleetIntel
	--TeamName = FleetIntel
	
end 


--
--  "initialize" code for Mission11 FleetIntel FCIntro state
--
function Init_Mission11_FleetIntel_FCIntro(TeamName)
	--FSM: FSM_Mission11_FleetIntel
	--TeamName = FleetIntel
	KAS_SubtitleAddOnce(Actor_HW1_FleetCommand, "$60632", 3)    --kasfSpeechEvent((632 + 2048 + 268435456), 0)
	
end 


--
--  "watch" code for Mission11 FleetIntel FCIntro state
--
function Watch_Mission11_FleetIntel_FCIntro(TeamName)
	--FSM: FSM_Mission11_FleetIntel
	--TeamName = FleetIntel
	if (Subtitle_IsDoneOrSkipped(Actor_FleetIntel) ~= 0) then     --kasfIntelEventEnded()
	
	G_FCDoneRasping = 1 --created,set
	--kasJump("FIIdle")
	--KASRule_Remove("FSM_Mission11_FleetIntel", "Watch_Mission11_FleetIntel_FCIntro")
	KASRule_Add(TeamName, "Watch_Mission11_FleetIntel_FIIdle", "Watch_Mission11_FleetIntel_FCIntro")
	Init_Mission11_FleetIntel_FIIdle(TeamName)
	return
	end 
	
end 


--
--  "initialize" code for Mission11 FleetIntel FIDefendTraders state
--
function Init_Mission11_FleetIntel_FIDefendTraders(TeamName)
	--FSM: FSM_Mission11_FleetIntel
	--TeamName = FleetIntel
	if (ignoredFunction(0) == 0) then     --kasfRaceOfHuman()
	
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60633", 3)    --kasfSpeechEvent((633 + 4096 + 268435456), 0)
	elseif (ignoredFunction(0) == 1) then     --kasfRaceOfHuman()
	
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60634", 3)    --kasfSpeechEvent((634 + 4096 + 268435456), 0)
	end 
	
end 


--
--  "watch" code for Mission11 FleetIntel FIDefendTraders state
--
function Watch_Mission11_FleetIntel_FIDefendTraders(TeamName)
	--FSM: FSM_Mission11_FleetIntel
	--TeamName = FleetIntel
	if (Subtitle_IsDoneOrSkipped(Actor_FleetIntel) ~= 0) then     --kasfIntelEventEnded()
	
	if (_VIFONCE001[TeamName] == 0 and (1 ~= 0)) then  -- "ifonce" #1
	
	_VIFONCE001[TeamName] = 1 --created,set;
	G_CreateObjectiveNow = 1 --created,set
	end 
	G_CLICK_DestroyFleet = 0 --destroyed
	--kasJump("FIIdle")
	--KASRule_Remove("FSM_Mission11_FleetIntel", "Watch_Mission11_FleetIntel_FIDefendTraders")
	KASRule_Add(TeamName, "Watch_Mission11_FleetIntel_FIIdle", "Watch_Mission11_FleetIntel_FIDefendTraders")
	Init_Mission11_FleetIntel_FIIdle(TeamName)
	return
	end 
	
end 


--
--  "initialize" code for Mission11 FleetIntel FIResearchSuperHeavy state
--
function Init_Mission11_FleetIntel_FIResearchSuperHeavy(TeamName)
	--FSM: FSM_Mission11_FleetIntel
	--TeamName = FleetIntel
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60782", 3)    --kasfSpeechEvent((782 + 4096 + 268435456), 0)
	
end 


--
--  "watch" code for Mission11 FleetIntel FIResearchSuperHeavy state
--
function Watch_Mission11_FleetIntel_FIResearchSuperHeavy(TeamName)
	--FSM: FSM_Mission11_FleetIntel
	--TeamName = FleetIntel
	if (Subtitle_IsDoneOrSkipped(Actor_FleetIntel) ~= 0) then     --kasfIntelEventEnded()
	
	--kasJump("FIIdle")
	--KASRule_Remove("FSM_Mission11_FleetIntel", "Watch_Mission11_FleetIntel_FIResearchSuperHeavy")
	KASRule_Add(TeamName, "Watch_Mission11_FleetIntel_FIIdle", "Watch_Mission11_FleetIntel_FIResearchSuperHeavy")
	Init_Mission11_FleetIntel_FIIdle(TeamName)
	return
	end 
	
end 


--
--  "initialize" code for Mission11 FleetIntel TradersThanks state
--
function Init_Mission11_FleetIntel_TradersThanks(TeamName)
	--FSM: FSM_Mission11_FleetIntel
	--TeamName = FleetIntel
	KAS_SubtitleAddOnce(Actor_HW1_BentusiTraders, "$60635", 3)    --kasfSpeechEvent((635 + 8192 + 268435456), 0)
	
end 


--
--  "watch" code for Mission11 FleetIntel TradersThanks state
--
function Watch_Mission11_FleetIntel_TradersThanks(TeamName)
	--FSM: FSM_Mission11_FleetIntel
	--TeamName = FleetIntel
	if (Subtitle_IsDoneOrSkipped(Actor_FleetIntel) ~= 0) then     --kasfIntelEventEnded()
	
	if (_VIFONCE002[TeamName] == 0 and (1 ~= 0)) then  -- "ifonce" #2
	
	_VIFONCE002[TeamName] = 1 --created,set;
	G_PlayN08Now = 1 --created,set
	end 
	--kasJump("FIIdle")
	--KASRule_Remove("FSM_Mission11_FleetIntel", "Watch_Mission11_FleetIntel_TradersThanks")
	KASRule_Add(TeamName, "Watch_Mission11_FleetIntel_FIIdle", "Watch_Mission11_FleetIntel_TradersThanks")
	Init_Mission11_FleetIntel_FIIdle(TeamName)
	return
	end 
	
end 


--
--  "initialize" code for Mission11 FleetIntel TradersFirstWarning state
--
function Init_Mission11_FleetIntel_TradersFirstWarning(TeamName)
	--FSM: FSM_Mission11_FleetIntel
	--TeamName = FleetIntel
	KAS_SubtitleAddOnce(Actor_HW1_BentusiTraders, "$60494", 3)    --kasfSpeechEvent((494 + 8192 + 268435456), 0)
	
end 


--
--  "watch" code for Mission11 FleetIntel TradersFirstWarning state
--
function Watch_Mission11_FleetIntel_TradersFirstWarning(TeamName)
	--FSM: FSM_Mission11_FleetIntel
	--TeamName = FleetIntel
	if (Subtitle_IsDoneOrSkipped(Actor_FleetIntel) ~= 0) then     --kasfIntelEventEnded()
	
	--kasJump("FICeaseFire")
	--KASRule_Remove("FSM_Mission11_FleetIntel", "Watch_Mission11_FleetIntel_TradersFirstWarning")
	KASRule_Add(TeamName, "Watch_Mission11_FleetIntel_FICeaseFire", "Watch_Mission11_FleetIntel_TradersFirstWarning")
	Init_Mission11_FleetIntel_FICeaseFire(TeamName)
	return
	end 
	
end 


--
--  "initialize" code for Mission11 FleetIntel FICeaseFire state
--
function Init_Mission11_FleetIntel_FICeaseFire(TeamName)
	--FSM: FSM_Mission11_FleetIntel
	--TeamName = FleetIntel
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60495", 3)    --kasfSpeechEvent((495 + 4096 + 268435456), 0)
	KASTimer_Start(TimerID_G_GivePlayerTimeToWithdrawAttack, 12)
	
end 


--
--  "watch" code for Mission11 FleetIntel FICeaseFire state
--
function Watch_Mission11_FleetIntel_FICeaseFire(TeamName)
	--FSM: FSM_Mission11_FleetIntel
	--TeamName = FleetIntel
	if ((G_PlayerHasAttackedTraders == 0) and (KASTimer_IsExpiredIfSoDestroy(TimerID_G_GivePlayerTimeToWithdrawAttack) ~= 0)) then 
	
	--kasJump("FIIdle")
	--KASRule_Remove("FSM_Mission11_FleetIntel", "Watch_Mission11_FleetIntel_FICeaseFire")
	KASRule_Add(TeamName, "Watch_Mission11_FleetIntel_FIIdle", "Watch_Mission11_FleetIntel_FICeaseFire")
	Init_Mission11_FleetIntel_FIIdle(TeamName)
	return
	end 
	if ((G_PlayerHasAttackedTraders == 1) and (KASTimer_IsExpiredIfSoDestroy(TimerID_G_GivePlayerTimeToWithdrawAttack) ~= 0)) then 
	
	--kasJump("TradersTellPlayer")
	--KASRule_Remove("FSM_Mission11_FleetIntel", "Watch_Mission11_FleetIntel_FICeaseFire")
	KASRule_Add(TeamName, "Watch_Mission11_FleetIntel_TradersTellPlayer", "Watch_Mission11_FleetIntel_FICeaseFire")
	Init_Mission11_FleetIntel_TradersTellPlayer(TeamName)
	return
	end 
	
end 


--
--  "initialize" code for Mission11 FleetIntel TradersTellPlayer state
--
function Init_Mission11_FleetIntel_TradersTellPlayer(TeamName)
	--FSM: FSM_Mission11_FleetIntel
	--TeamName = FleetIntel
	KAS_SubtitleAddOnce(Actor_HW1_BentusiTraders, "$60496", 3)    --kasfSpeechEvent((496 + 8192 + 268435456), 0)
	
end 


--
--  "watch" code for Mission11 FleetIntel TradersTellPlayer state
--
function Watch_Mission11_FleetIntel_TradersTellPlayer(TeamName)
	--FSM: FSM_Mission11_FleetIntel
	--TeamName = FleetIntel
	if (Subtitle_IsDoneOrSkipped(Actor_FleetIntel) ~= 0) then     --kasfIntelEventEnded()
	
	G_TradersObliteratePlayer = 1 --created,set
	end 
	
end 


--
--  "initialize" code for Mission11 FleetIntel TradersPlayN08 state
--
function Init_Mission11_FleetIntel_TradersPlayN08(TeamName)
	--FSM: FSM_Mission11_FleetIntel
	--TeamName = FleetIntel
	G_PlayNis = 8 --created,set
	G_N08IsPlaying = 1 --created,set
	KAS_SetHidden("Traders", 1)    --kasfHideShips(kasAITeamShipsPtr("Traders"))
	--kasJump("FIIdle")
	KASRule_Add(TeamName, "Watch_Mission11_FleetIntel_FIIdle", "Init_Mission11_FleetIntel_TradersPlayN08")
	Init_Mission11_FleetIntel_FIIdle(TeamName)
	return
	
end 


--
--  "watch" code for Mission11 FleetIntel TradersPlayN08 state
--
function Watch_Mission11_FleetIntel_TradersPlayN08(TeamName)
	--FSM: FSM_Mission11_FleetIntel
	--TeamName = FleetIntel
	
end 


--
--  "initialize" code for Mission11 FleetIntel TradersCouncilComin state
--
function Init_Mission11_FleetIntel_TradersCouncilComin(TeamName)
	--FSM: FSM_Mission11_FleetIntel
	--TeamName = FleetIntel
	KAS_SubtitleAddOnce(Actor_HW1_BentusiTraders, "$60646", 3)    --kasfSpeechEvent((646 + 8192 + 268435456), 0)
	
end 


--
--  "watch" code for Mission11 FleetIntel TradersCouncilComin state
--
function Watch_Mission11_FleetIntel_TradersCouncilComin(TeamName)
	--FSM: FSM_Mission11_FleetIntel
	--TeamName = FleetIntel
	if (Subtitle_IsDoneOrSkipped(Actor_FleetIntel) ~= 0) then     --kasfIntelEventEnded()
	
	if (_VIFONCE003[TeamName] == 0 and (1 ~= 0)) then  -- "ifonce" #3
	
	_VIFONCE003[TeamName] = 1 --created,set;
	G_TradersGoNow = 1 --created,set
	KASTimer_Start(PlayFinalEvent[TeamName], 12)
	end 
	--kasJump("FIIdle")
	--KASRule_Remove("FSM_Mission11_FleetIntel", "Watch_Mission11_FleetIntel_TradersCouncilComin")
	KASRule_Add(TeamName, "Watch_Mission11_FleetIntel_FIIdle", "Watch_Mission11_FleetIntel_TradersCouncilComin")
	Init_Mission11_FleetIntel_FIIdle(TeamName)
	return
	end 
	
end 


--
--  "initialize" code for Mission11 FleetIntel FIEngageHyperdrive state
--
function Init_Mission11_FleetIntel_FIEngageHyperdrive(TeamName)
	--FSM: FSM_Mission11_FleetIntel
	--TeamName = FleetIntel
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60647", 3)    --kasfSpeechEvent((647 + 4096 + 268435456), 0)
	if (_VIFONCE004[TeamName] == 0 and (1 ~= 0)) then  -- "ifonce" #4
	
	_VIFONCE004[TeamName] = 1 --created,set;
	G_MissionComplete = 1 --created,set
	end 
	
end 


--
--  "watch" code for Mission11 FleetIntel FIEngageHyperdrive state
--
function Watch_Mission11_FleetIntel_FIEngageHyperdrive(TeamName)
	--FSM: FSM_Mission11_FleetIntel
	--TeamName = FleetIntel
	if (Subtitle_IsDoneOrSkipped(Actor_FleetIntel) ~= 0) then     --kasfIntelEventEnded()
	
	--kasJump("FIIdle")
	--KASRule_Remove("FSM_Mission11_FleetIntel", "Watch_Mission11_FleetIntel_FIEngageHyperdrive")
	KASRule_Add(TeamName, "Watch_Mission11_FleetIntel_FIIdle", "Watch_Mission11_FleetIntel_FIEngageHyperdrive")
	Init_Mission11_FleetIntel_FIIdle(TeamName)
	return
	end 
	
end 


--
--  "initialize" code for Mission11 FleetIntel FIIdle state
--
function Init_Mission11_FleetIntel_FIIdle(TeamName)
	--FSM: FSM_Mission11_FleetIntel
	--TeamName = FleetIntel
	
end 


--
--  "watch" code for Mission11 FleetIntel FIIdle state
--
function Watch_Mission11_FleetIntel_FIIdle(TeamName)
	--FSM: FSM_Mission11_FleetIntel
	--TeamName = FleetIntel
	if (_VIFONCE005[TeamName] == 0 and (KASTimer_IsExpiredIfSoDestroy(TimerID_G_FCHyperspaceSuccessful) ~= 0)) then  -- "ifonce" #5
	
	_VIFONCE005[TeamName] = 1 --created,set;
	--kasJump("FCIntro")
	--KASRule_Remove("FSM_Mission11_FleetIntel", "Watch_Mission11_FleetIntel_FIIdle")
	KASRule_Add(TeamName, "Watch_Mission11_FleetIntel_FCIntro", "Watch_Mission11_FleetIntel_FIIdle")
	Init_Mission11_FleetIntel_FCIntro(TeamName)
	return
	end 
	if (_VIFONCE006[TeamName] == 0 and (KASTimer_IsExpiredIfSoDestroy(TimerID_G_FIDefendTraders) ~= 0)) then  -- "ifonce" #6
	
	_VIFONCE006[TeamName] = 1 --created,set;
	--kasJump("FIDefendTraders")
	--KASRule_Remove("FSM_Mission11_FleetIntel", "Watch_Mission11_FleetIntel_FIIdle")
	KASRule_Add(TeamName, "Watch_Mission11_FleetIntel_FIDefendTraders", "Watch_Mission11_FleetIntel_FIIdle")
	Init_Mission11_FleetIntel_FIDefendTraders(TeamName)
	return
	end 
	if (_VIFONCE007[TeamName] == 0 and ((G_GivePlayerSuperHeavy == 1) and (G_N07IsPlaying == 0) and (G_N08IsPlaying == 0))) then  -- "ifonce" #7
	
	_VIFONCE007[TeamName] = 1 --created,set;
	--kasJump("FIResearchSuperHeavy")
	--KASRule_Remove("FSM_Mission11_FleetIntel", "Watch_Mission11_FleetIntel_FIIdle")
	KASRule_Add(TeamName, "Watch_Mission11_FleetIntel_FIResearchSuperHeavy", "Watch_Mission11_FleetIntel_FIIdle")
	Init_Mission11_FleetIntel_FIResearchSuperHeavy(TeamName)
	return
	end 
	if (_VIFONCE008[TeamName] == 0 and (G_TradersInPosition == 1)) then  -- "ifonce" #8
	
	_VIFONCE008[TeamName] = 1 --created,set;
	--kasJump("TradersThanks")
	--KASRule_Remove("FSM_Mission11_FleetIntel", "Watch_Mission11_FleetIntel_FIIdle")
	KASRule_Add(TeamName, "Watch_Mission11_FleetIntel_TradersThanks", "Watch_Mission11_FleetIntel_FIIdle")
	Init_Mission11_FleetIntel_TradersThanks(TeamName)
	return
	end 
	if (G_PlayerHasAttackedTraders == 1) then 
	
	--kasJump("TradersFirstWarning")
	--KASRule_Remove("FSM_Mission11_FleetIntel", "Watch_Mission11_FleetIntel_FIIdle")
	KASRule_Add(TeamName, "Watch_Mission11_FleetIntel_TradersFirstWarning", "Watch_Mission11_FleetIntel_FIIdle")
	Init_Mission11_FleetIntel_TradersFirstWarning(TeamName)
	return
	end 
	if (_VIFONCE009[TeamName] == 0 and (G_PlayN08Now == 1)) then  -- "ifonce" #9
	
	_VIFONCE009[TeamName] = 1 --created,set;
	KASTimer_Start(WideScreenInBeforeNIS2[TeamName], 3)
	KAS_SetLetterboxState(2, 3)    --kasfWideScreenIn(90)
	G_PlayedN08 = 1 --created,set
	end 
	if (KASTimer_IsExpiredIfSoDestroy(WideScreenInBeforeNIS2[TeamName]) ~= 0) then 
	
	--kasJump("TradersPlayN08")
	--KASRule_Remove("FSM_Mission11_FleetIntel", "Watch_Mission11_FleetIntel_FIIdle")
	KASRule_Add(TeamName, "Watch_Mission11_FleetIntel_TradersPlayN08", "Watch_Mission11_FleetIntel_FIIdle")
	Init_Mission11_FleetIntel_TradersPlayN08(TeamName)
	return
	end 
	if (_VIFONCE010[TeamName] == 0 and (KASTimer_IsExpiredIfSoDestroy(TimerID_G_TradersTalk) ~= 0)) then  -- "ifonce" #10
	
	_VIFONCE010[TeamName] = 1 --created,set;
	--kasJump("TradersCouncilComin")
	--KASRule_Remove("FSM_Mission11_FleetIntel", "Watch_Mission11_FleetIntel_FIIdle")
	KASRule_Add(TeamName, "Watch_Mission11_FleetIntel_TradersCouncilComin", "Watch_Mission11_FleetIntel_FIIdle")
	Init_Mission11_FleetIntel_TradersCouncilComin(TeamName)
	return
	end 
	if (_VIFONCE011[TeamName] == 0 and (KASTimer_IsExpiredIfSoDestroy(PlayFinalEvent[TeamName]) ~= 0)) then  -- "ifonce" #11
	
	_VIFONCE011[TeamName] = 1 --created,set;
	--kasJump("FIEngageHyperdrive")
	--KASRule_Remove("FSM_Mission11_FleetIntel", "Watch_Mission11_FleetIntel_FIIdle")
	KASRule_Add(TeamName, "Watch_Mission11_FleetIntel_FIEngageHyperdrive", "Watch_Mission11_FleetIntel_FIIdle")
	Init_Mission11_FleetIntel_FIEngageHyperdrive(TeamName)
	return
	end 
	if (G_CLICK_DestroyFleet ~= 0) then 
	
	--kasJump("FIDefendTraders")
	--KASRule_Remove("FSM_Mission11_FleetIntel", "Watch_Mission11_FleetIntel_FIIdle")
	KASRule_Add(TeamName, "Watch_Mission11_FleetIntel_FIDefendTraders", "Watch_Mission11_FleetIntel_FIIdle")
	Init_Mission11_FleetIntel_FIDefendTraders(TeamName)
	return
	end 
	
end 


--
--  "initialize" code for Mission11 Traders FSM
--
function Init_Mission11_Traders(TeamName)
	--FSM: FSM_Mission11_Traders
	--TeamName = Traders
	KAS_TeamAttributesSet(TeamName, 256)    --kasfTeamAttributesSet(256)
	SobGroup_SetHealth(TeamName, 43 / 100)    --kasfTeamSetPercentDamaged(43)
	KAS_SetTraderDisabled(1)    --kasfSetTraderDisabled(1)
	KAS_TeamMakeCrazy(TeamName, 1)    --kasfTeamMakeCrazy(1)
	--kasJump("Flounder")
	KASRule_Add(TeamName, "Watch_Mission11_Traders_Flounder", "Init_Mission11_Traders")
	Init_Mission11_Traders_Flounder(TeamName)
	return
	
end 


--
--  "watch" code for Mission11 Traders FSM
--
function Watch_Mission11_Traders(TeamName)
	--FSM: FSM_Mission11_Traders
	--TeamName = Traders
	if (_VIFONCE012[TeamName] == 0 and (G_Nis7Complete == 1)) then  -- "ifonce" #12
	
	_VIFONCE012[TeamName] = 1 --created,set;
	SobGroup_SetHealth(TeamName, 33 / 100)    --kasfTeamSetPercentDamaged(33)
	end 
	if (_VIFONCE013[TeamName] == 0 and (KAS_TeamHealth(TeamName) < 25)) then  -- "ifonce" #13    --kasfTeamHealthAverage()
	
	_VIFONCE013[TeamName] = 1 --created,set;
	KASTimer_Start(KeepTraderShipAlive[TeamName], 90)
	end 
	if ((KAS_TeamHealth(TeamName) < 25) and (KASTimer_GetRemaining(KeepTraderShipAlive[TeamName]) > 0)) then     --kasfTeamHealthAverage()
	
	SobGroup_SetHealth(TeamName, 25 / 100)    --kasfTeamSetPercentDamaged(25)
	end 
	if (_VIFONCE014[TeamName] == 0 and (G_N08IsPlaying == 1)) then  -- "ifonce" #14
	
	_VIFONCE014[TeamName] = 1 --created,set;
	CurrentTraderHealth[TeamName] = KAS_TeamHealth(TeamName) --created,set    --kasfTeamHealthAverage()
	KeepBentusiAliveForever[TeamName] = 1 --created,set
	end 
	if (KeepBentusiAliveForever[TeamName] == 1) then 
	
	SobGroup_SetHealth(TeamName, CurrentTraderHealth[TeamName] / 100)    --kasfTeamSetPercentDamaged(___KAS_SCOPED_VAR____CurrentTraderHealth_)
	end 
	
end 


--
--  "initialize" code for Mission11 Traders Flounder state
--
function Init_Mission11_Traders_Flounder(TeamName)
	--FSM: FSM_Mission11_Traders
	--TeamName = Traders
	KAS_TeamMakeCrazy(TeamName, 1)    --kasfTeamMakeCrazy(1)
	
end 


--
--  "watch" code for Mission11 Traders Flounder state
--
function Watch_Mission11_Traders_Flounder(TeamName)
	--FSM: FSM_Mission11_Traders
	--TeamName = Traders
	if (KAS_UnderAttack(TeamName, "GrowSelection_Null929292") == 0) then     --kasfUnderAttack(kasGrowSelectionPtr("Null929292"))
	
	KAS_TeamMakeCrazy(TeamName, 0)    --kasfTeamMakeCrazy(0)
	end 
	if (KASObjective_GetState(ObjectiveID_DestroyFleet) == 1) then     --kasfObjectiveGet("DestroyFleet")
	
	KAS_TeamMakeCrazy(TeamName, 0)    --kasfTeamMakeCrazy(0)
	--kasJump("FlyUpToPlayer")
	--KASRule_Remove("FSM_Mission11_Traders", "Watch_Mission11_Traders_Flounder")
	KASRule_Add(TeamName, "Watch_Mission11_Traders_FlyUpToPlayer", "Watch_Mission11_Traders_Flounder")
	Init_Mission11_Traders_FlyUpToPlayer(TeamName)
	return
	end 
	
end 


--
--  "initialize" code for Mission11 Traders FlyUpToPlayer state
--
function Init_Mission11_Traders_FlyUpToPlayer(TeamName)
	--FSM: FSM_Mission11_Traders
	--TeamName = Traders
	SobGroup_FollowPath(TeamName, "TraderPath", 1, 1, 0)    --kasfPatrolPath(kasPathPtr("TraderPath"))
	
end 


--
--  "watch" code for Mission11 Traders FlyUpToPlayer state
--
function Watch_Mission11_Traders_FlyUpToPlayer(TeamName)
	--FSM: FSM_Mission11_Traders
	--TeamName = Traders
	if (_VIFONCE015[TeamName] == 0 and (SobGroup_GetNextPathPoint(TeamName) == 0)) then  -- "ifonce" #15    --kasfPathNextPoint()
	
	_VIFONCE015[TeamName] = 1 --created,set;
	G_TradersInPosition = 1 --created,set
	--kasJump("WaitToHyperspace")
	--KASRule_Remove("FSM_Mission11_Traders", "Watch_Mission11_Traders_FlyUpToPlayer")
	KASRule_Add(TeamName, "Watch_Mission11_Traders_WaitToHyperspace", "Watch_Mission11_Traders_FlyUpToPlayer")
	Init_Mission11_Traders_WaitToHyperspace(TeamName)
	return
	end 
	if (KAS_UnderAttack(TeamName, "GrowSelection_Null87238923") ~= 0) then     --kasfUnderAttack(kasGrowSelectionPtr("Null87238923"))
	
	G_PlayerHasAttackedTraders = 1 --created,set
	--kasJump("UnderAttackWatch")
	--KASRule_Remove("FSM_Mission11_Traders", "Watch_Mission11_Traders_FlyUpToPlayer")
	KASRule_Add(TeamName, "Watch_Mission11_Traders_UnderAttackWatch", "Watch_Mission11_Traders_FlyUpToPlayer")
	Init_Mission11_Traders_UnderAttackWatch(TeamName)
	return
	end 
	
end 


--
--  "initialize" code for Mission11 Traders UnderAttackWatch state
--
function Init_Mission11_Traders_UnderAttackWatch(TeamName)
	--FSM: FSM_Mission11_Traders
	--TeamName = Traders
	
end 


--
--  "watch" code for Mission11 Traders UnderAttackWatch state
--
function Watch_Mission11_Traders_UnderAttackWatch(TeamName)
	--FSM: FSM_Mission11_Traders
	--TeamName = Traders
	if (G_TradersObliteratePlayer == 1) then 
	
	--kasJump("TradersObliteratePlayer")
	--KASRule_Remove("FSM_Mission11_Traders", "Watch_Mission11_Traders_UnderAttackWatch")
	KASRule_Add(TeamName, "Watch_Mission11_Traders_TradersObliteratePlayer", "Watch_Mission11_Traders_UnderAttackWatch")
	Init_Mission11_Traders_TradersObliteratePlayer(TeamName)
	return
	end 
	if (KAS_UnderAttack(TeamName, "GrowSelection_Null8723487238") == 0) then     --kasfUnderAttack(kasGrowSelectionPtr("Null8723487238"))
	
	G_PlayerHasAttackedTraders = 0 --destroyed
	if (G_TradersInPosition == 1) then 
	
	--kasJump("WaitToHyperspace")
	--KASRule_Remove("FSM_Mission11_Traders", "Watch_Mission11_Traders_UnderAttackWatch")
	KASRule_Add(TeamName, "Watch_Mission11_Traders_WaitToHyperspace", "Watch_Mission11_Traders_UnderAttackWatch")
	Init_Mission11_Traders_WaitToHyperspace(TeamName)
	return
	else
	
	--kasJump("FlyUpToPlayer")
	--KASRule_Remove("FSM_Mission11_Traders", "Watch_Mission11_Traders_UnderAttackWatch")
	KASRule_Add(TeamName, "Watch_Mission11_Traders_FlyUpToPlayer", "Watch_Mission11_Traders_UnderAttackWatch")
	Init_Mission11_Traders_FlyUpToPlayer(TeamName)
	return
	end 
	end 
	
end 


--
--  "initialize" code for Mission11 Traders TradersObliteratePlayer state
--
function Init_Mission11_Traders_TradersObliteratePlayer(TeamName)
	--FSM: FSM_Mission11_Traders
	--TeamName = Traders
	CurrentTraderHealth[TeamName] = KAS_TeamHealth(TeamName) --created,set    --kasfTeamHealthAverage()
	KAS_FindEnemiesInside("MothershipSphere", "GrowSelection_PlayerFleet")    --kasfFindEnemiesInside(kasVolumePtr("MothershipSphere"), kasGrowSelectionPtr("PlayerFleet"), 1000)
	if (KAS_FillShipsByClass_Normal("GrowSelection_TraderTargets", "GrowSelection_PlayerFleet", "SmallCapitalShip") ~= 0) then     --kasfShipsSelectClass(kasGrowSelectionPtr("TraderTargets"), kasGrowSelectionPtr("PlayerFleet"), "CLASS_Destroyer")
	
	elseif (KAS_FillShipsByClass_Normal("GrowSelection_TraderTargets", "GrowSelection_PlayerFleet", "Frigate") ~= 0) then     --kasfShipsSelectClass(kasGrowSelectionPtr("TraderTargets"), kasGrowSelectionPtr("PlayerFleet"), "CLASS_Frigate")
	
	elseif (KAS_FillShipsByClass_Normal("GrowSelection_TraderTargets", "GrowSelection_PlayerFleet", "Mothership") ~= 0) then     --kasfShipsSelectClass(kasGrowSelectionPtr("TraderTargets"), kasGrowSelectionPtr("PlayerFleet"), "CLASS_Mothership")
	
	else
	
	KAS_ShipsAdd("GrowSelection_TraderTargets", "GrowSelection_PlayerFleet")    --kasfShipsAdd(kasGrowSelectionPtr("TraderTargets"), kasGrowSelectionPtr("PlayerFleet"))
	end 
	if (SobGroup_Count("GrowSelection_TraderTargets") > 0) then     --kasfShipsCount(kasGrowSelectionPtr("TraderTargets"))
	
	KAS_Attack(TeamName, "GrowSelection_TraderTargets")    --kasfAttack(kasGrowSelectionPtr("TraderTargets"))
	end 
	
end 


--
--  "watch" code for Mission11 Traders TradersObliteratePlayer state
--
function Watch_Mission11_Traders_TradersObliteratePlayer(TeamName)
	--FSM: FSM_Mission11_Traders
	--TeamName = Traders
	SobGroup_SetHealth(TeamName, CurrentTraderHealth[TeamName] / 100)    --kasfTeamSetPercentDamaged(___KAS_SCOPED_VAR____CurrentTraderHealth_)
	if ((SobGroup_Count("GrowSelection_TraderTargets") == 0) or (KAS_GetCurrentOrder("Traders") ~= 2)) then     --kasfShipsCount(kasGrowSelectionPtr("TraderTargets"))    --kasfShipsOrder(kasAITeamShipsPtr("Traders"))
	
	--kasJump("TradersObliteratePlayer")
	--KASRule_Remove("FSM_Mission11_Traders", "Watch_Mission11_Traders_TradersObliteratePlayer")
	KASRule_Add(TeamName, "Watch_Mission11_Traders_TradersObliteratePlayer", "Watch_Mission11_Traders_TradersObliteratePlayer")
	Init_Mission11_Traders_TradersObliteratePlayer(TeamName)
	return
	end 
	
end 


--
--  "initialize" code for Mission11 Traders WaitToHyperspace state
--
function Init_Mission11_Traders_WaitToHyperspace(TeamName)
	--FSM: FSM_Mission11_Traders
	--TeamName = Traders
	
end 


--
--  "watch" code for Mission11 Traders WaitToHyperspace state
--
function Watch_Mission11_Traders_WaitToHyperspace(TeamName)
	--FSM: FSM_Mission11_Traders
	--TeamName = Traders
	if (KAS_UnderAttack(TeamName, "GrowSelection_Null87238923") ~= 0) then     --kasfUnderAttack(kasGrowSelectionPtr("Null87238923"))
	
	G_PlayerHasAttackedTraders = 1 --created,set
	--kasJump("UnderAttackWatch")
	--KASRule_Remove("FSM_Mission11_Traders", "Watch_Mission11_Traders_WaitToHyperspace")
	KASRule_Add(TeamName, "Watch_Mission11_Traders_UnderAttackWatch", "Watch_Mission11_Traders_WaitToHyperspace")
	Init_Mission11_Traders_UnderAttackWatch(TeamName)
	return
	end 
	if (G_TradersGoNow == 1) then 
	
	--kasJump("HyperspaceOut")
	--KASRule_Remove("FSM_Mission11_Traders", "Watch_Mission11_Traders_WaitToHyperspace")
	KASRule_Add(TeamName, "Watch_Mission11_Traders_HyperspaceOut", "Watch_Mission11_Traders_WaitToHyperspace")
	Init_Mission11_Traders_HyperspaceOut(TeamName)
	return
	end 
	
end 


--
--  "initialize" code for Mission11 Traders HyperspaceOut state
--
function Init_Mission11_Traders_HyperspaceOut(TeamName)
	--FSM: FSM_Mission11_Traders
	--TeamName = Traders
	KAS_TeamHyperspaceOut(TeamName)    --kasfTeamHyperspaceOut()
	--kasJump("NullState")
	KASRule_Add(TeamName, "Watch_Mission11_Traders_NullState", "Init_Mission11_Traders_HyperspaceOut")
	Init_Mission11_Traders_NullState(TeamName)
	return
	
end 


--
--  "watch" code for Mission11 Traders HyperspaceOut state
--
function Watch_Mission11_Traders_HyperspaceOut(TeamName)
	--FSM: FSM_Mission11_Traders
	--TeamName = Traders
	
end 


--
--  "initialize" code for Mission11 Traders NullState state
--
function Init_Mission11_Traders_NullState(TeamName)
	--FSM: FSM_Mission11_Traders
	--TeamName = Traders
	
end 


--
--  "watch" code for Mission11 Traders NullState state
--
function Watch_Mission11_Traders_NullState(TeamName)
	--FSM: FSM_Mission11_Traders
	--TeamName = Traders
	
end 


--
--  "initialize" code for Mission11 Cruiser FSM
--
function Init_Mission11_Cruiser(TeamName)
	--FSM: FSM_Mission11_Cruiser
	--TeamName = Cruiser
	--kasJump("AttackTraders")
	KASRule_Add(TeamName, "Watch_Mission11_Cruiser_AttackTraders", "Init_Mission11_Cruiser")
	Init_Mission11_Cruiser_AttackTraders(TeamName)
	return
	
end 


--
--  "watch" code for Mission11 Cruiser FSM
--
function Watch_Mission11_Cruiser(TeamName)
	--FSM: FSM_Mission11_Cruiser
	--TeamName = Cruiser
	if (_VIFONCE016[TeamName] == 0 and (KASObjective_GetState(ObjectiveID_DestroyFleet) == 1)) then  -- "ifonce" #16    --kasfObjectiveGet("DestroyFleet")
	
	_VIFONCE016[TeamName] = 1 --created,set;
	--kasJump("NullState")
	--KASRule_Remove("FSM_Mission11_Cruiser", "Watch_Mission11_Cruiser")
	KASRule_Add(TeamName, "Watch_Mission11_Cruiser_NullState", "Watch_Mission11_Cruiser")
	Init_Mission11_Cruiser_NullState(TeamName)
	return
	end 
	
end 


--
--  "initialize" code for Mission11 Cruiser AttackTraders state
--
function Init_Mission11_Cruiser_AttackTraders(TeamName)
	--FSM: FSM_Mission11_Cruiser
	--TeamName = Cruiser
	KAS_MoveAttack(TeamName, "Traders")    --kasfMoveAttack(kasAITeamShipsPtr("Traders"))
	
end 


--
--  "watch" code for Mission11 Cruiser AttackTraders state
--
function Watch_Mission11_Cruiser_AttackTraders(TeamName)
	--FSM: FSM_Mission11_Cruiser
	--TeamName = Cruiser
	if (KAS_TeamNamesEqual(TeamName, "Cruiser") ~= 0) then     --kasfThisTeamIs(kasAITeamPtr("Cruiser"))
	
	if (KAS_UnderAttack(TeamName, "GrowSelection_CruiserUnderAttack") ~= 0) then     --kasfUnderAttack(kasGrowSelectionPtr("CruiserUnderAttack"))
	
	KAS_FillShipsByClass_Normal("GrowSelection_Mothership", "GrowSelection_CruiserUnderAttack", "Mothership")    --kasfShipsSelectClass(kasGrowSelectionPtr("Mothership"), kasGrowSelectionPtr("CruiserUnderAttack"), "CLASS_Mothership")
	SobGroup_FillSubtract("GrowSelection_CruiserUnderAttack", "GrowSelection_CruiserUnderAttack", "GrowSelection_Mothership")    --kasfShipsRemove(kasGrowSelectionPtr("CruiserUnderAttack"), kasGrowSelectionPtr("Mothership"))
	if (SobGroup_Count("GrowSelection_CruiserUnderAttack") > 0) then     --kasfShipsCount(kasGrowSelectionPtr("CruiserUnderAttack"))
	
	--kasJump("DefendYourself")
	--KASRule_Remove("FSM_Mission11_Cruiser", "Watch_Mission11_Cruiser_AttackTraders")
	KASRule_Add(TeamName, "Watch_Mission11_Cruiser_DefendYourself", "Watch_Mission11_Cruiser_AttackTraders")
	Init_Mission11_Cruiser_DefendYourself(TeamName)
	return
	end 
	end 
	elseif (KAS_TeamNamesEqual(TeamName, "Destroyers") ~= 0) then     --kasfThisTeamIs(kasAITeamPtr("Destroyers"))
	
	if (KAS_UnderAttack(TeamName, "GrowSelection_DestroyersUnderAttack") ~= 0) then     --kasfUnderAttack(kasGrowSelectionPtr("DestroyersUnderAttack"))
	
	KAS_FillShipsByClass_Normal("GrowSelection_Mothership", "GrowSelection_DestroyersUnderAttack", "Mothership")    --kasfShipsSelectClass(kasGrowSelectionPtr("Mothership"), kasGrowSelectionPtr("DestroyersUnderAttack"), "CLASS_Mothership")
	SobGroup_FillSubtract("GrowSelection_DestroyersUnderAttack", "GrowSelection_DestroyersUnderAttack", "GrowSelection_Mothership")    --kasfShipsRemove(kasGrowSelectionPtr("DestroyersUnderAttack"), kasGrowSelectionPtr("Mothership"))
	if (SobGroup_Count("GrowSelection_DestroyersUnderAttack") > 0) then     --kasfShipsCount(kasGrowSelectionPtr("DestroyersUnderAttack"))
	
	--kasJump("DefendYourself")
	--KASRule_Remove("FSM_Mission11_Cruiser", "Watch_Mission11_Cruiser_AttackTraders")
	KASRule_Add(TeamName, "Watch_Mission11_Cruiser_DefendYourself", "Watch_Mission11_Cruiser_AttackTraders")
	Init_Mission11_Cruiser_DefendYourself(TeamName)
	return
	end 
	end 
	elseif (KAS_TeamNamesEqual(TeamName, "IonCannonFrigates") ~= 0) then     --kasfThisTeamIs(kasAITeamPtr("IonCannonFrigates"))
	
	if (KAS_UnderAttack(TeamName, "GrowSelection_IonFrigUnderAttack") ~= 0) then     --kasfUnderAttack(kasGrowSelectionPtr("IonFrigUnderAttack"))
	
	KAS_FillShipsByClass_Normal("GrowSelection_Mothership", "GrowSelection_IonFrigUnderAttack", "Mothership")    --kasfShipsSelectClass(kasGrowSelectionPtr("Mothership"), kasGrowSelectionPtr("IonFrigUnderAttack"), "CLASS_Mothership")
	SobGroup_FillSubtract("GrowSelection_IonFrigUnderAttack", "GrowSelection_IonFrigUnderAttack", "GrowSelection_Mothership")    --kasfShipsRemove(kasGrowSelectionPtr("IonFrigUnderAttack"), kasGrowSelectionPtr("Mothership"))
	if (SobGroup_Count("GrowSelection_IonFrigUnderAttack") > 0) then     --kasfShipsCount(kasGrowSelectionPtr("IonFrigUnderAttack"))
	
	--kasJump("DefendYourself")
	--KASRule_Remove("FSM_Mission11_Cruiser", "Watch_Mission11_Cruiser_AttackTraders")
	KASRule_Add(TeamName, "Watch_Mission11_Cruiser_DefendYourself", "Watch_Mission11_Cruiser_AttackTraders")
	Init_Mission11_Cruiser_DefendYourself(TeamName)
	return
	end 
	end 
	end 
	if (KAS_TeamNamesEqual(TeamName, "Cruiser") ~= 0) then     --kasfThisTeamIs(kasAITeamPtr("Cruiser"))
	
	if (KAS_FindEnemiesNearTeam(TeamName, "GrowSelection_CruiserL00kingForSCs", 5250) ~= 0) then     --kasfFindEnemiesNearTeam(kasGrowSelectionPtr("CruiserL00kingForSCs"), 15000)
	
	KAS_FillShipsByType_Normal("GrowSelection_CruiserFoundSomeSCs", "GrowSelection_CruiserL00kingForSCs", "SalvageCorvette")    --kasfShipsSelectType(kasGrowSelectionPtr("CruiserFoundSomeSCs"), kasGrowSelectionPtr("CruiserL00kingForSCs"), "SalCapCorvette")
	if ((SobGroup_Count("GrowSelection_CruiserFoundSomeSCs") > 0) and (KAS_GetCurrentOrder("GrowSelection_CruiserFoundSomeSCs") == 7)) then     --kasfShipsCount(kasGrowSelectionPtr("CruiserFoundSomeSCs"))    --kasfShipsOrder(kasGrowSelectionPtr("CruiserFoundSomeSCs"))
	
	--kasJump("DefendYourself")
	--KASRule_Remove("FSM_Mission11_Cruiser", "Watch_Mission11_Cruiser_AttackTraders")
	KASRule_Add(TeamName, "Watch_Mission11_Cruiser_DefendYourself", "Watch_Mission11_Cruiser_AttackTraders")
	Init_Mission11_Cruiser_DefendYourself(TeamName)
	return
	end 
	end 
	elseif (KAS_TeamNamesEqual(TeamName, "Destroyers") ~= 0) then     --kasfThisTeamIs(kasAITeamPtr("Destroyers"))
	
	if (KAS_FindEnemiesNearTeam(TeamName, "GrowSelection_DestroyersL00kingForSCs", 5250) ~= 0) then     --kasfFindEnemiesNearTeam(kasGrowSelectionPtr("DestroyersL00kingForSCs"), 15000)
	
	KAS_FillShipsByType_Normal("GrowSelection_DestroyersFoundSomeSCs", "GrowSelection_DestroyersL00kingForSCs", "SalvageCorvette")    --kasfShipsSelectType(kasGrowSelectionPtr("DestroyersFoundSomeSCs"), kasGrowSelectionPtr("DestroyersL00kingForSCs"), "SalCapCorvette")
	if ((SobGroup_Count("GrowSelection_DestroyersFoundSomeSCs") > 0) and (KAS_GetCurrentOrder("GrowSelection_DestroyersFoundSomeSCs") == 7)) then     --kasfShipsCount(kasGrowSelectionPtr("DestroyersFoundSomeSCs"))    --kasfShipsOrder(kasGrowSelectionPtr("DestroyersFoundSomeSCs"))
	
	--kasJump("DefendYourself")
	--KASRule_Remove("FSM_Mission11_Cruiser", "Watch_Mission11_Cruiser_AttackTraders")
	KASRule_Add(TeamName, "Watch_Mission11_Cruiser_DefendYourself", "Watch_Mission11_Cruiser_AttackTraders")
	Init_Mission11_Cruiser_DefendYourself(TeamName)
	return
	end 
	end 
	elseif (KAS_TeamNamesEqual(TeamName, "IonCannonFrigates") ~= 0) then     --kasfThisTeamIs(kasAITeamPtr("IonCannonFrigates"))
	
	if (KAS_FindEnemiesNearTeam(TeamName, "GrowSelection_IonFrigL00kingForSCs", 5250) ~= 0) then     --kasfFindEnemiesNearTeam(kasGrowSelectionPtr("IonFrigL00kingForSCs"), 15000)
	
	KAS_FillShipsByType_Normal("GrowSelection_IonFrigFoundSomeSCs", "GrowSelection_IonFrigL00kingForSCs", "SalvageCorvette")    --kasfShipsSelectType(kasGrowSelectionPtr("IonFrigFoundSomeSCs"), kasGrowSelectionPtr("IonFrigL00kingForSCs"), "SalCapCorvette")
	if ((SobGroup_Count("GrowSelection_IonFrigFoundSomeSCs") > 0) and (KAS_GetCurrentOrder("GrowSelection_IonFrigFoundSomeSCs") == 7)) then     --kasfShipsCount(kasGrowSelectionPtr("IonFrigFoundSomeSCs"))    --kasfShipsOrder(kasGrowSelectionPtr("IonFrigFoundSomeSCs"))
	
	--kasJump("DefendYourself")
	--KASRule_Remove("FSM_Mission11_Cruiser", "Watch_Mission11_Cruiser_AttackTraders")
	KASRule_Add(TeamName, "Watch_Mission11_Cruiser_DefendYourself", "Watch_Mission11_Cruiser_AttackTraders")
	Init_Mission11_Cruiser_DefendYourself(TeamName)
	return
	end 
	end 
	end 
	
end 


--
--  "initialize" code for Mission11 Cruiser DefendYourself state
--
function Init_Mission11_Cruiser_DefendYourself(TeamName)
	--FSM: FSM_Mission11_Cruiser
	--TeamName = Cruiser
	if (KAS_TeamNamesEqual(TeamName, "Cruiser") ~= 0) then     --kasfThisTeamIs(kasAITeamPtr("Cruiser"))
	
	if (KAS_FillShipsByType_Normal("GrowSelection_CruiserNearbyTargets", "GrowSelection_CruiserUnderAttack", "SalvageCorvette") ~= 0) then     --kasfShipsSelectType(kasGrowSelectionPtr("CruiserNearbyTargets"), kasGrowSelectionPtr("CruiserUnderAttack"), "SalCapCorvette")
	
	elseif (KAS_FillShipsByType_Normal("GrowSelection_CruiserNearbyTargets", "GrowSelection_CruiserFoundSomeSCs", "SalvageCorvette") ~= 0) then     --kasfShipsSelectType(kasGrowSelectionPtr("CruiserNearbyTargets"), kasGrowSelectionPtr("CruiserFoundSomeSCs"), "SalCapCorvette")
	
	elseif (KAS_FillShipsByClass_Normal("GrowSelection_CruiserNearbyTargets", "GrowSelection_CruiserUnderAttack", "Corvette_hw1") ~= 0) then     --kasfShipsSelectClass(kasGrowSelectionPtr("CruiserNearbyTargets"), kasGrowSelectionPtr("CruiserUnderAttack"), "CLASS_Corvette")
	
	elseif (KAS_FillShipsByClass_Normal("GrowSelection_CruiserNearbyTargets", "GrowSelection_CruiserUnderAttack", "Frigate") ~= 0) then     --kasfShipsSelectClass(kasGrowSelectionPtr("CruiserNearbyTargets"), kasGrowSelectionPtr("CruiserUnderAttack"), "CLASS_Frigate")
	
	elseif (KAS_FillShipsByClass_Normal("GrowSelection_CruiserNearbyTargets", "GrowSelection_CruiserUnderAttack", "Fighter_hw1") ~= 0) then     --kasfShipsSelectClass(kasGrowSelectionPtr("CruiserNearbyTargets"), kasGrowSelectionPtr("CruiserUnderAttack"), "CLASS_Fighter")
	
	else
	
	KAS_ShipsAdd("GrowSelection_CruiserNearbyTargets", "GrowSelection_CruiserUnderAttack")    --kasfShipsAdd(kasGrowSelectionPtr("CruiserNearbyTargets"), kasGrowSelectionPtr("CruiserUnderAttack"))
	end 
	if (SobGroup_Count("GrowSelection_CruiserNearbyTargets") > 0) then     --kasfShipsCount(kasGrowSelectionPtr("CruiserNearbyTargets"))
	
	KAS_Attack(TeamName, "GrowSelection_CruiserNearbyTargets")    --kasfAttack(kasGrowSelectionPtr("CruiserNearbyTargets"))
	else
	
	--kasJump("AttackPlayerMothership")
	KASRule_Add(TeamName, "Watch_Mission11_Cruiser_AttackPlayerMothership", "Init_Mission11_Cruiser_DefendYourself")
	Init_Mission11_Cruiser_AttackPlayerMothership(TeamName)
	return
	end 
	elseif (KAS_TeamNamesEqual(TeamName, "Destroyers") ~= 0) then     --kasfThisTeamIs(kasAITeamPtr("Destroyers"))
	
	if (KAS_FillShipsByType_Normal("GrowSelection_DestroyersNearbyTargets", "GrowSelection_DestroyersUnderAttack", "SalvageCorvette") ~= 0) then     --kasfShipsSelectType(kasGrowSelectionPtr("DestroyersNearbyTargets"), kasGrowSelectionPtr("DestroyersUnderAttack"), "SalCapCorvette")
	
	elseif (KAS_FillShipsByType_Normal("GrowSelection_DestroyersNearbyTargets", "GrowSelection_DestroyersFoundSomeSCs", "SalvageCorvette") ~= 0) then     --kasfShipsSelectType(kasGrowSelectionPtr("DestroyersNearbyTargets"), kasGrowSelectionPtr("DestroyersFoundSomeSCs"), "SalCapCorvette")
	
	elseif (KAS_FillShipsByClass_Normal("GrowSelection_DestroyersNearbyTargets", "GrowSelection_DestroyersUnderAttack", "Corvette_hw1") ~= 0) then     --kasfShipsSelectClass(kasGrowSelectionPtr("DestroyersNearbyTargets"), kasGrowSelectionPtr("DestroyersUnderAttack"), "CLASS_Corvette")
	
	elseif (KAS_FillShipsByClass_Normal("GrowSelection_DestroyersNearbyTargets", "GrowSelection_DestroyersUnderAttack", "Frigate") ~= 0) then     --kasfShipsSelectClass(kasGrowSelectionPtr("DestroyersNearbyTargets"), kasGrowSelectionPtr("DestroyersUnderAttack"), "CLASS_Frigate")
	
	elseif (KAS_FillShipsByClass_Normal("GrowSelection_DestroyersNearbyTargets", "GrowSelection_DestroyersUnderAttack", "Fighter_hw1") ~= 0) then     --kasfShipsSelectClass(kasGrowSelectionPtr("DestroyersNearbyTargets"), kasGrowSelectionPtr("DestroyersUnderAttack"), "CLASS_Fighter")
	
	else
	
	KAS_ShipsAdd("GrowSelection_DestroyersNearbyTargets", "GrowSelection_DestroyersUnderAttack")    --kasfShipsAdd(kasGrowSelectionPtr("DestroyersNearbyTargets"), kasGrowSelectionPtr("DestroyersUnderAttack"))
	end 
	if (SobGroup_Count("GrowSelection_DestroyersNearbyTargets") > 0) then     --kasfShipsCount(kasGrowSelectionPtr("DestroyersNearbyTargets"))
	
	KAS_Attack(TeamName, "GrowSelection_DestroyersNearbyTargets")    --kasfAttack(kasGrowSelectionPtr("DestroyersNearbyTargets"))
	else
	
	--kasJump("AttackPlayerMothership")
	KASRule_Add(TeamName, "Watch_Mission11_Cruiser_AttackPlayerMothership", "Init_Mission11_Cruiser_DefendYourself")
	Init_Mission11_Cruiser_AttackPlayerMothership(TeamName)
	return
	end 
	elseif (KAS_TeamNamesEqual(TeamName, "IonCannonFrigates") ~= 0) then     --kasfThisTeamIs(kasAITeamPtr("IonCannonFrigates"))
	
	if (KAS_FillShipsByType_Normal("GrowSelection_IonFrigNearbyTargets", "GrowSelection_IonFrigUnderAttack", "SalvageCorvette") ~= 0) then     --kasfShipsSelectType(kasGrowSelectionPtr("IonFrigNearbyTargets"), kasGrowSelectionPtr("IonFrigUnderAttack"), "SalCapCorvette")
	
	elseif (KAS_FillShipsByType_Normal("GrowSelection_IonFrigNearbyTargets", "GrowSelection_IonFrigFoundSomeSCs", "SalvageCorvette") ~= 0) then     --kasfShipsSelectType(kasGrowSelectionPtr("IonFrigNearbyTargets"), kasGrowSelectionPtr("IonFrigFoundSomeSCs"), "SalCapCorvette")
	
	elseif (KAS_FillShipsByClass_Normal("GrowSelection_IonFrigNearbyTargets", "GrowSelection_IonFrigUnderAttack", "Corvette_hw1") ~= 0) then     --kasfShipsSelectClass(kasGrowSelectionPtr("IonFrigNearbyTargets"), kasGrowSelectionPtr("IonFrigUnderAttack"), "CLASS_Corvette")
	
	elseif (KAS_FillShipsByClass_Normal("GrowSelection_IonFrigNearbyTargets", "GrowSelection_IonFrigUnderAttack", "Frigate") ~= 0) then     --kasfShipsSelectClass(kasGrowSelectionPtr("IonFrigNearbyTargets"), kasGrowSelectionPtr("IonFrigUnderAttack"), "CLASS_Frigate")
	
	elseif (KAS_FillShipsByClass_Normal("GrowSelection_IonFrigNearbyTargets", "GrowSelection_IonFrigUnderAttack", "Fighter_hw1") ~= 0) then     --kasfShipsSelectClass(kasGrowSelectionPtr("IonFrigNearbyTargets"), kasGrowSelectionPtr("IonFrigUnderAttack"), "CLASS_Fighter")
	
	else
	
	KAS_ShipsAdd("GrowSelection_IonFrigNearbyTargets", "GrowSelection_IonFrigUnderAttack")    --kasfShipsAdd(kasGrowSelectionPtr("IonFrigNearbyTargets"), kasGrowSelectionPtr("IonFrigUnderAttack"))
	end 
	if (SobGroup_Count("GrowSelection_IonFrigNearbyTargets") > 0) then     --kasfShipsCount(kasGrowSelectionPtr("IonFrigNearbyTargets"))
	
	KAS_Attack(TeamName, "GrowSelection_IonFrigNearbyTargets")    --kasfAttack(kasGrowSelectionPtr("IonFrigNearbyTargets"))
	else
	
	--kasJump("AttackPlayerMothership")
	KASRule_Add(TeamName, "Watch_Mission11_Cruiser_AttackPlayerMothership", "Init_Mission11_Cruiser_DefendYourself")
	Init_Mission11_Cruiser_AttackPlayerMothership(TeamName)
	return
	end 
	end 
	
end 


--
--  "watch" code for Mission11 Cruiser DefendYourself state
--
function Watch_Mission11_Cruiser_DefendYourself(TeamName)
	--FSM: FSM_Mission11_Cruiser
	--TeamName = Cruiser
	if (KAS_TeamNamesEqual(TeamName, "Cruiser") ~= 0) then     --kasfThisTeamIs(kasAITeamPtr("Cruiser"))
	
	if ((SobGroup_Count("GrowSelection_CruiserNearbyTargets") == 0) or (KAS_GetCurrentOrder("Cruiser") ~= 2)) then     --kasfShipsCount(kasGrowSelectionPtr("CruiserNearbyTargets"))    --kasfShipsOrder(kasAITeamShipsPtr("Cruiser"))
	
	--kasJump("DefendYourself")
	--KASRule_Remove("FSM_Mission11_Cruiser", "Watch_Mission11_Cruiser_DefendYourself")
	KASRule_Add(TeamName, "Watch_Mission11_Cruiser_DefendYourself", "Watch_Mission11_Cruiser_DefendYourself")
	Init_Mission11_Cruiser_DefendYourself(TeamName)
	return
	end 
	elseif (KAS_TeamNamesEqual(TeamName, "Destroyers") ~= 0) then     --kasfThisTeamIs(kasAITeamPtr("Destroyers"))
	
	if ((SobGroup_Count("GrowSelection_DestroyersNearbyTargets") == 0) or (KAS_GetCurrentOrder("Destroyers") ~= 2)) then     --kasfShipsCount(kasGrowSelectionPtr("DestroyersNearbyTargets"))    --kasfShipsOrder(kasAITeamShipsPtr("Destroyers"))
	
	--kasJump("DefendYourself")
	--KASRule_Remove("FSM_Mission11_Cruiser", "Watch_Mission11_Cruiser_DefendYourself")
	KASRule_Add(TeamName, "Watch_Mission11_Cruiser_DefendYourself", "Watch_Mission11_Cruiser_DefendYourself")
	Init_Mission11_Cruiser_DefendYourself(TeamName)
	return
	end 
	elseif (KAS_TeamNamesEqual(TeamName, "IonCannonFrigates") ~= 0) then     --kasfThisTeamIs(kasAITeamPtr("IonCannonFrigates"))
	
	if ((SobGroup_Count("GrowSelection_IonFrigNearbyTargets") == 0) or (KAS_GetCurrentOrder("IonCannonFrigates") ~= 2)) then     --kasfShipsCount(kasGrowSelectionPtr("IonFrigNearbyTargets"))    --kasfShipsOrder(kasAITeamShipsPtr("IonCannonFrigates"))
	
	--kasJump("DefendYourself")
	--KASRule_Remove("FSM_Mission11_Cruiser", "Watch_Mission11_Cruiser_DefendYourself")
	KASRule_Add(TeamName, "Watch_Mission11_Cruiser_DefendYourself", "Watch_Mission11_Cruiser_DefendYourself")
	Init_Mission11_Cruiser_DefendYourself(TeamName)
	return
	end 
	end 
	if (KAS_TeamNamesEqual(TeamName, "Cruiser") ~= 0) then     --kasfThisTeamIs(kasAITeamPtr("Cruiser"))
	
	if (KAS_FindEnemiesNearTeam(TeamName, "GrowSelection_CruiserL00kingForSCs", 5250) ~= 0) then     --kasfFindEnemiesNearTeam(kasGrowSelectionPtr("CruiserL00kingForSCs"), 15000)
	
	KAS_FillShipsByType_Normal("GrowSelection_CruiserFoundSomeSCs", "GrowSelection_CruiserL00kingForSCs", "SalvageCorvette")    --kasfShipsSelectType(kasGrowSelectionPtr("CruiserFoundSomeSCs"), kasGrowSelectionPtr("CruiserL00kingForSCs"), "SalCapCorvette")
	if ((SobGroup_Count("GrowSelection_CruiserFoundSomeSCs") > 0) and (KAS_GetCurrentOrder("GrowSelection_CruiserFoundSomeSCs") == 7)) then     --kasfShipsCount(kasGrowSelectionPtr("CruiserFoundSomeSCs"))    --kasfShipsOrder(kasGrowSelectionPtr("CruiserFoundSomeSCs"))
	
	--kasJump("DefendYourself")
	--KASRule_Remove("FSM_Mission11_Cruiser", "Watch_Mission11_Cruiser_DefendYourself")
	KASRule_Add(TeamName, "Watch_Mission11_Cruiser_DefendYourself", "Watch_Mission11_Cruiser_DefendYourself")
	Init_Mission11_Cruiser_DefendYourself(TeamName)
	return
	end 
	end 
	elseif (KAS_TeamNamesEqual(TeamName, "Destroyers") ~= 0) then     --kasfThisTeamIs(kasAITeamPtr("Destroyers"))
	
	if (KAS_FindEnemiesNearTeam(TeamName, "GrowSelection_DestroyersL00kingForSCs", 5250) ~= 0) then     --kasfFindEnemiesNearTeam(kasGrowSelectionPtr("DestroyersL00kingForSCs"), 15000)
	
	KAS_FillShipsByType_Normal("GrowSelection_DestroyersFoundSomeSCs", "GrowSelection_DestroyersL00kingForSCs", "SalvageCorvette")    --kasfShipsSelectType(kasGrowSelectionPtr("DestroyersFoundSomeSCs"), kasGrowSelectionPtr("DestroyersL00kingForSCs"), "SalCapCorvette")
	if ((SobGroup_Count("GrowSelection_DestroyersFoundSomeSCs") > 0) and (KAS_GetCurrentOrder("GrowSelection_DestroyersFoundSomeSCs") == 7)) then     --kasfShipsCount(kasGrowSelectionPtr("DestroyersFoundSomeSCs"))    --kasfShipsOrder(kasGrowSelectionPtr("DestroyersFoundSomeSCs"))
	
	--kasJump("DefendYourself")
	--KASRule_Remove("FSM_Mission11_Cruiser", "Watch_Mission11_Cruiser_DefendYourself")
	KASRule_Add(TeamName, "Watch_Mission11_Cruiser_DefendYourself", "Watch_Mission11_Cruiser_DefendYourself")
	Init_Mission11_Cruiser_DefendYourself(TeamName)
	return
	end 
	end 
	elseif (KAS_TeamNamesEqual(TeamName, "IonCannonFrigates") ~= 0) then     --kasfThisTeamIs(kasAITeamPtr("IonCannonFrigates"))
	
	if (KAS_FindEnemiesNearTeam(TeamName, "GrowSelection_IonFrigL00kingForSCs", 5250) ~= 0) then     --kasfFindEnemiesNearTeam(kasGrowSelectionPtr("IonFrigL00kingForSCs"), 15000)
	
	KAS_FillShipsByType_Normal("GrowSelection_IonFrigFoundSomeSCs", "GrowSelection_IonFrigL00kingForSCs", "SalvageCorvette")    --kasfShipsSelectType(kasGrowSelectionPtr("IonFrigFoundSomeSCs"), kasGrowSelectionPtr("IonFrigL00kingForSCs"), "SalCapCorvette")
	if ((SobGroup_Count("GrowSelection_IonFrigFoundSomeSCs") > 0) and (KAS_GetCurrentOrder("GrowSelection_IonFrigFoundSomeSCs") == 7)) then     --kasfShipsCount(kasGrowSelectionPtr("IonFrigFoundSomeSCs"))    --kasfShipsOrder(kasGrowSelectionPtr("IonFrigFoundSomeSCs"))
	
	--kasJump("DefendYourself")
	--KASRule_Remove("FSM_Mission11_Cruiser", "Watch_Mission11_Cruiser_DefendYourself")
	KASRule_Add(TeamName, "Watch_Mission11_Cruiser_DefendYourself", "Watch_Mission11_Cruiser_DefendYourself")
	Init_Mission11_Cruiser_DefendYourself(TeamName)
	return
	end 
	end 
	end 
	
end 


--
--  "initialize" code for Mission11 Cruiser AttackPlayerMothership state
--
function Init_Mission11_Cruiser_AttackPlayerMothership(TeamName)
	--FSM: FSM_Mission11_Cruiser
	--TeamName = Cruiser
	KAS_MoveAttack(TeamName, "GrowSelection_PlayerMothership")    --kasfMoveAttack(kasGrowSelectionPtr("PlayerMothership"))
	
end 


--
--  "watch" code for Mission11 Cruiser AttackPlayerMothership state
--
function Watch_Mission11_Cruiser_AttackPlayerMothership(TeamName)
	--FSM: FSM_Mission11_Cruiser
	--TeamName = Cruiser
	if (KAS_TeamNamesEqual(TeamName, "Cruiser") ~= 0) then     --kasfThisTeamIs(kasAITeamPtr("Cruiser"))
	
	if (KAS_UnderAttack(TeamName, "GrowSelection_CruiserUnderAttack") ~= 0) then     --kasfUnderAttack(kasGrowSelectionPtr("CruiserUnderAttack"))
	
	KAS_FillShipsByClass_Normal("GrowSelection_Mothership", "GrowSelection_CruiserUnderAttack", "Mothership")    --kasfShipsSelectClass(kasGrowSelectionPtr("Mothership"), kasGrowSelectionPtr("CruiserUnderAttack"), "CLASS_Mothership")
	SobGroup_FillSubtract("GrowSelection_CruiserUnderAttack", "GrowSelection_CruiserUnderAttack", "GrowSelection_Mothership")    --kasfShipsRemove(kasGrowSelectionPtr("CruiserUnderAttack"), kasGrowSelectionPtr("Mothership"))
	if (SobGroup_Count("GrowSelection_CruiserUnderAttack") > 0) then     --kasfShipsCount(kasGrowSelectionPtr("CruiserUnderAttack"))
	
	--kasJump("DefendYourself")
	--KASRule_Remove("FSM_Mission11_Cruiser", "Watch_Mission11_Cruiser_AttackPlayerMothership")
	KASRule_Add(TeamName, "Watch_Mission11_Cruiser_DefendYourself", "Watch_Mission11_Cruiser_AttackPlayerMothership")
	Init_Mission11_Cruiser_DefendYourself(TeamName)
	return
	end 
	end 
	elseif (KAS_TeamNamesEqual(TeamName, "Destroyers") ~= 0) then     --kasfThisTeamIs(kasAITeamPtr("Destroyers"))
	
	if (KAS_UnderAttack(TeamName, "GrowSelection_DestroyersUnderAttack") ~= 0) then     --kasfUnderAttack(kasGrowSelectionPtr("DestroyersUnderAttack"))
	
	KAS_FillShipsByClass_Normal("GrowSelection_Mothership", "GrowSelection_DestroyersUnderAttack", "Mothership")    --kasfShipsSelectClass(kasGrowSelectionPtr("Mothership"), kasGrowSelectionPtr("DestroyersUnderAttack"), "CLASS_Mothership")
	SobGroup_FillSubtract("GrowSelection_DestroyersUnderAttack", "GrowSelection_DestroyersUnderAttack", "GrowSelection_Mothership")    --kasfShipsRemove(kasGrowSelectionPtr("DestroyersUnderAttack"), kasGrowSelectionPtr("Mothership"))
	if (SobGroup_Count("GrowSelection_DestroyersUnderAttack") > 0) then     --kasfShipsCount(kasGrowSelectionPtr("DestroyersUnderAttack"))
	
	--kasJump("DefendYourself")
	--KASRule_Remove("FSM_Mission11_Cruiser", "Watch_Mission11_Cruiser_AttackPlayerMothership")
	KASRule_Add(TeamName, "Watch_Mission11_Cruiser_DefendYourself", "Watch_Mission11_Cruiser_AttackPlayerMothership")
	Init_Mission11_Cruiser_DefendYourself(TeamName)
	return
	end 
	end 
	elseif (KAS_TeamNamesEqual(TeamName, "IonCannonFrigates") ~= 0) then     --kasfThisTeamIs(kasAITeamPtr("IonCannonFrigates"))
	
	if (KAS_UnderAttack(TeamName, "GrowSelection_IonFrigUnderAttack") ~= 0) then     --kasfUnderAttack(kasGrowSelectionPtr("IonFrigUnderAttack"))
	
	KAS_FillShipsByClass_Normal("GrowSelection_Mothership", "GrowSelection_IonFrigUnderAttack", "Mothership")    --kasfShipsSelectClass(kasGrowSelectionPtr("Mothership"), kasGrowSelectionPtr("IonFrigUnderAttack"), "CLASS_Mothership")
	SobGroup_FillSubtract("GrowSelection_IonFrigUnderAttack", "GrowSelection_IonFrigUnderAttack", "GrowSelection_Mothership")    --kasfShipsRemove(kasGrowSelectionPtr("IonFrigUnderAttack"), kasGrowSelectionPtr("Mothership"))
	if (SobGroup_Count("GrowSelection_IonFrigUnderAttack") > 0) then     --kasfShipsCount(kasGrowSelectionPtr("IonFrigUnderAttack"))
	
	--kasJump("DefendYourself")
	--KASRule_Remove("FSM_Mission11_Cruiser", "Watch_Mission11_Cruiser_AttackPlayerMothership")
	KASRule_Add(TeamName, "Watch_Mission11_Cruiser_DefendYourself", "Watch_Mission11_Cruiser_AttackPlayerMothership")
	Init_Mission11_Cruiser_DefendYourself(TeamName)
	return
	end 
	end 
	end 
	if (KAS_TeamNamesEqual(TeamName, "Cruiser") ~= 0) then     --kasfThisTeamIs(kasAITeamPtr("Cruiser"))
	
	if (KAS_FindEnemiesNearTeam(TeamName, "GrowSelection_CruiserL00kingForSCs", 5250) ~= 0) then     --kasfFindEnemiesNearTeam(kasGrowSelectionPtr("CruiserL00kingForSCs"), 15000)
	
	KAS_FillShipsByType_Normal("GrowSelection_CruiserFoundSomeSCs", "GrowSelection_CruiserL00kingForSCs", "SalvageCorvette")    --kasfShipsSelectType(kasGrowSelectionPtr("CruiserFoundSomeSCs"), kasGrowSelectionPtr("CruiserL00kingForSCs"), "SalCapCorvette")
	if ((SobGroup_Count("GrowSelection_CruiserFoundSomeSCs") > 0) and (KAS_GetCurrentOrder("GrowSelection_CruiserFoundSomeSCs") == 7)) then     --kasfShipsCount(kasGrowSelectionPtr("CruiserFoundSomeSCs"))    --kasfShipsOrder(kasGrowSelectionPtr("CruiserFoundSomeSCs"))
	
	--kasJump("DefendYourself")
	--KASRule_Remove("FSM_Mission11_Cruiser", "Watch_Mission11_Cruiser_AttackPlayerMothership")
	KASRule_Add(TeamName, "Watch_Mission11_Cruiser_DefendYourself", "Watch_Mission11_Cruiser_AttackPlayerMothership")
	Init_Mission11_Cruiser_DefendYourself(TeamName)
	return
	end 
	end 
	elseif (KAS_TeamNamesEqual(TeamName, "Destroyers") ~= 0) then     --kasfThisTeamIs(kasAITeamPtr("Destroyers"))
	
	if (KAS_FindEnemiesNearTeam(TeamName, "GrowSelection_DestroyersL00kingForSCs", 5250) ~= 0) then     --kasfFindEnemiesNearTeam(kasGrowSelectionPtr("DestroyersL00kingForSCs"), 15000)
	
	KAS_FillShipsByType_Normal("GrowSelection_DestroyersFoundSomeSCs", "GrowSelection_DestroyersL00kingForSCs", "SalvageCorvette")    --kasfShipsSelectType(kasGrowSelectionPtr("DestroyersFoundSomeSCs"), kasGrowSelectionPtr("DestroyersL00kingForSCs"), "SalCapCorvette")
	if ((SobGroup_Count("GrowSelection_DestroyersFoundSomeSCs") > 0) and (KAS_GetCurrentOrder("GrowSelection_DestroyersFoundSomeSCs") == 7)) then     --kasfShipsCount(kasGrowSelectionPtr("DestroyersFoundSomeSCs"))    --kasfShipsOrder(kasGrowSelectionPtr("DestroyersFoundSomeSCs"))
	
	--kasJump("DefendYourself")
	--KASRule_Remove("FSM_Mission11_Cruiser", "Watch_Mission11_Cruiser_AttackPlayerMothership")
	KASRule_Add(TeamName, "Watch_Mission11_Cruiser_DefendYourself", "Watch_Mission11_Cruiser_AttackPlayerMothership")
	Init_Mission11_Cruiser_DefendYourself(TeamName)
	return
	end 
	end 
	elseif (KAS_TeamNamesEqual(TeamName, "IonCannonFrigates") ~= 0) then     --kasfThisTeamIs(kasAITeamPtr("IonCannonFrigates"))
	
	if (KAS_FindEnemiesNearTeam(TeamName, "GrowSelection_IonFrigL00kingForSCs", 5250) ~= 0) then     --kasfFindEnemiesNearTeam(kasGrowSelectionPtr("IonFrigL00kingForSCs"), 15000)
	
	KAS_FillShipsByType_Normal("GrowSelection_IonFrigFoundSomeSCs", "GrowSelection_IonFrigL00kingForSCs", "SalvageCorvette")    --kasfShipsSelectType(kasGrowSelectionPtr("IonFrigFoundSomeSCs"), kasGrowSelectionPtr("IonFrigL00kingForSCs"), "SalCapCorvette")
	if ((SobGroup_Count("GrowSelection_IonFrigFoundSomeSCs") > 0) and (KAS_GetCurrentOrder("GrowSelection_IonFrigFoundSomeSCs") == 7)) then     --kasfShipsCount(kasGrowSelectionPtr("IonFrigFoundSomeSCs"))    --kasfShipsOrder(kasGrowSelectionPtr("IonFrigFoundSomeSCs"))
	
	--kasJump("DefendYourself")
	--KASRule_Remove("FSM_Mission11_Cruiser", "Watch_Mission11_Cruiser_AttackPlayerMothership")
	KASRule_Add(TeamName, "Watch_Mission11_Cruiser_DefendYourself", "Watch_Mission11_Cruiser_AttackPlayerMothership")
	Init_Mission11_Cruiser_DefendYourself(TeamName)
	return
	end 
	end 
	end 
	
end 


--
--  "initialize" code for Mission11 Cruiser NullState state
--
function Init_Mission11_Cruiser_NullState(TeamName)
	--FSM: FSM_Mission11_Cruiser
	--TeamName = Cruiser
	
end 


--
--  "watch" code for Mission11 Cruiser NullState state
--
function Watch_Mission11_Cruiser_NullState(TeamName)
	--FSM: FSM_Mission11_Cruiser
	--TeamName = Cruiser
	
end 


--
--  "initialize" code for Mission11 mission
--
function Init_Mission11(MissionName)
	--FSM: FSM_Mission11
	--MissionName = "Mission11"
	--kasFSMCreate("FleetIntel")
	KASRule_AddFSM("FleetIntel", "Watch_Mission11_FleetIntel", "Init_Mission11")
	Init_Mission11_FleetIntel("FleetIntel")
	KAS_CampaignAutoSave(11, "$61550")    --kasfSaveLevel(11, LSTRING_Savegame[strCurLanguage])
	
end 


--
--  "watch" code for Mission11 mission
--
function Watch_Mission11(MissionName)
	--FSM: FSM_Mission11
	--MissionName = "Mission11"
	if (_VIFONCE017 == 0 and (1 ~= 0)) then  -- "ifonce" #17
	
	_VIFONCE017 = 1 --created,set;
	KASTimer_Start(TimerID_LocationCardTimer, 1)
	end 
	if (KASTimer_IsExpiredIfSoDestroy(TimerID_LocationCardTimer) ~= 0) then 
	
	singlePlayerLocationCard("$61551", 5)    --kasfLocationCard(5000, LSTRING_LocationCard[strCurLanguage])
	end 
	if (_VIFONCE018 == 0 and (1 ~= 0)) then  -- "ifonce" #18
	
	_VIFONCE018 = 1 --created,set;
	KASTimer_Start(TimerID_G_FCHyperspaceSuccessful, 5)
	end 
	if (_VIFONCE019 == 0 and (G_Nis7Complete == 1)) then  -- "ifonce" #19
	
	_VIFONCE019 = 1 --created,set;
	G_N07IsPlaying = 0 --set
	KAS_MusicPlayType("data:sound/music/battle/B04_EvilEmpire", MUS_Ambient)    --kasfMusicPlay(15)
	KASTimer_Start(TimerID_CreateNISTeamsTimer, 1)
	KASTimer_Start(TimerID_G_FIDefendTraders, 4)

    --ally the traders to player
    SetAlliance(0, 2)
    SetAlliance(2, 0)
    SobGroup_SwitchOwner("Traders", 2)

	end 
	if (_VIFONCE020 == 0 and (G_Nis8Complete == 1)) then  -- "ifonce" #20
	
	_VIFONCE020 = 1 --created,set;
	G_N08IsPlaying = 0 --set
	KAS_SetHidden("Traders", 0)    --kasfUnhideShips(kasAITeamShipsPtr("Traders"))
	KASTimer_Start(TimerID_G_TradersTalk, 6)
	end 
	if (_VIFONCE021 == 0 and (KASTimer_IsExpiredIfSoDestroy(TimerID_CreateNISTeamsTimer) ~= 0)) then  -- "ifonce" #21
	
	_VIFONCE021 = 1 --created,set;
	--kasFSMCreate("Traders")
	KASRule_AddFSM("Traders", "Watch_Mission11_Traders", "Watch_Mission11")
	Init_Mission11_Traders("Traders")
	--kasFSMCreate("Cruiser")
	KASRule_AddFSM("Cruiser", "Watch_Mission11_Cruiser", "Watch_Mission11")
	Init_Mission11_Cruiser("Cruiser")
	--kasFSMCreate("Cruiser")
	KASRule_AddFSM("Destroyers", "Watch_Mission11_Cruiser", "Watch_Mission11")
	Init_Mission11_Cruiser("Destroyers")
	--kasFSMCreate("Cruiser")
	KASRule_AddFSM("IonCannonFrigates", "Watch_Mission11_Cruiser", "Watch_Mission11")
	Init_Mission11_Cruiser("IonCannonFrigates")
	end 
	if (_VIFONCE022 == 0 and (G_FCDoneRasping == 1)) then  -- "ifonce" #22
	
	_VIFONCE022 = 1 --created,set;
	KASTimer_Start(TimerID_WideScreenInBeforeNIS, 4)
	KAS_SetLetterboxState(2, 3)    --kasfWideScreenIn(90)
	G_PlayedN07 = 1 --created,set
	end 
	if (KASTimer_IsExpiredIfSoDestroy(TimerID_WideScreenInBeforeNIS) ~= 0) then 
	
	G_PlayNis = 7 --created,set
	G_N07IsPlaying = 1 --created,set
	end 
	if (_VIFONCE023 == 0 and (G_CreateObjectiveNow == 1)) then  -- "ifonce" #23
	
	_VIFONCE023 = 1 --created,set;
	if (ignoredFunction(0) == 0) then     --kasfRaceOfHuman()
	
	KASObjective_Add(ObjectiveID_DestroyFleet, "$61552", OT_Primary)    --kasfObjectiveCreate("DestroyFleet", LSTRING_FIDestroyTaiidanTASKBAR[strCurLanguage], LSTRING_FIDestroyTaiidanTASKBAR[strCurLanguage])
	Objective_SetDescription(ObjectiveID_DestroyFleet, "$60636")
	elseif (ignoredFunction(0) == 1) then     --kasfRaceOfHuman()
	
	KASObjective_Add(ObjectiveID_DestroyFleet, "$61553", OT_Primary)    --kasfObjectiveCreate("DestroyFleet", LSTRING_FIDestroyKushanTASKBAR[strCurLanguage], LSTRING_FIDestroyKushanTASKBAR[strCurLanguage])
	Objective_SetDescription(ObjectiveID_DestroyFleet, "Mission11_Missing")
	end 
	end 
	if (G_Nis7Complete == 1) then 
	
	if (_VIFONCE024 == 0 and ((SobGroup_Count("Cruiser") == 0) and (SobGroup_Count("Destroyers") == 0) and (SobGroup_Count("IonCannonFrigates") == 0))) then  -- "ifonce" #24    --kasfShipsCount(kasAITeamShipsPtr("IonCannonFrigates"))    --kasfShipsCount(kasAITeamShipsPtr("Destroyers"))    --kasfShipsCount(kasAITeamShipsPtr("Cruiser"))
	
	_VIFONCE024 = 1 --created,set;
	KASObjective_SetState(ObjectiveID_DestroyFleet, 1)    --kasfObjectiveSet("DestroyFleet", 1)
	KAS_MusicStop(4)    --kasfMusicStop(4)
	end 
	end 
	if (G_MissionComplete == 1) then 
	
	KASObjective_Add(ObjectiveID_Hyperspace, "Hyperspace", OT_Primary)    --kasfObjectiveCreate("Hyperspace", LSTRING_Hyperspace[strCurLanguage], LSTRING_Hyperspace[strCurLanguage])
	Objective_SetDescription(ObjectiveID_Hyperspace, "hyperspace")
	end 
	if (G_Nis7Complete == 1) then 
	
	if (_VIFONCE025 == 0 and (SobGroup_Count("Traders") == 0)) then  -- "ifonce" #25    --kasfShipsCount(kasAITeamShipsPtr("Traders"))
	
	_VIFONCE025 = 1 --created,set;
	KAS_MissionFailed()    --kasfMissionFailed()
	end 
	end 
	KAS_FindEnemiesInside("WorldSphere", "GrowSelection_Everyone")    --kasfFindEnemiesInside(kasVolumePtr("WorldSphere"), kasGrowSelectionPtr("Everyone"), 3000)
	KAS_FillShipsByClass_Normal("GrowSelection_PlayerMothership", "GrowSelection_Everyone", "Mothership")    --kasfShipsSelectClass(kasGrowSelectionPtr("PlayerMothership"), kasGrowSelectionPtr("Everyone"), "CLASS_Mothership")
	EveryoneSHIPS = SobGroup_Count("GrowSelection_Everyone") --created,set    --kasfShipsCount(kasGrowSelectionPtr("Everyone"))
	MothershipSHIPS = SobGroup_Count("GrowSelection_PlayerMothership") --created,set    --kasfShipsCount(kasGrowSelectionPtr("PlayerMothership"))
	if (_VIFONCE026 == 0 and (1 ~= 0)) then  -- "ifonce" #26
	
	_VIFONCE026 = 1 --created,set;
	KASTimer_Start(TimerID_G_PlayTechEvent, RandomIntRange(95, 105))    --kasfRandom(95, 105)
	end 
	if (_VIFONCE027 == 0 and ((KAS_PlayerHasResearch(0, "SuperHeavyChassis") == 0) and (KASTimer_IsExpiredIfSoDestroy(TimerID_G_PlayTechEvent) ~= 0))) then  -- "ifonce" #27    --kasfDoesPlayerHave("RepairTech")
	
	_VIFONCE027 = 1 --created,set;
	KAS_UnrestrictResearchOption(0, "SuperHeavyChassis")    --kasfAllowPlayerToResearch("RepairTech")
	G_GivePlayerSuperHeavy = 1 --created,set
	end 
	if (_VIFONCE028 == 0 and (KAS_PlayerHasResearch(0, "CorvetteDrive") ~= 0)) then  -- "ifonce" #28    --kasfDoesPlayerHave("MassDrive10Kt")
	
	_VIFONCE028 = 1 --created,set;
	KAS_UnrestrictResearchOption(0, "CorvetteChassis")    --kasfAllowPlayerToResearch("Chassis2")
	end 
	if ((KAS_PlayerHasResearch(0, "CorvetteChassis") ~= 0) and (SetMediumGuns == 0)) then     --kasfDoesPlayerHave("Chassis2")
	
	KAS_UnrestrictResearchOption(0, "HeavyCorvetteUpgrade")    --kasfAllowPlayerToResearch("MediumGuns")
	SetMediumGuns = 1 --created,set
	end 
	if (_VIFONCE029 == 0 and (KAS_PlayerHasResearch(0, "FighterChassis") ~= 0)) then  -- "ifonce" #29    --kasfDoesPlayerHave("Chassis1")
	
	_VIFONCE029 = 1 --created,set;
	KAS_UnrestrictResearchOption(0, "CorvetteDrive")    --kasfAllowPlayerToResearch("MassDrive10Kt")
	end 
	
end 

function OnStartOrLoad()
    print("OnStartOrLoad issued")

    --Mission-global GrowSelections/SobGroups
    KASSobGroup_Create("GrowSelection_CruiserFoundSomeSCs")
    KASSobGroup_Create("GrowSelection_CruiserL00kingForSCs")
    KASSobGroup_Create("GrowSelection_CruiserNearbyTargets")
    KASSobGroup_Create("GrowSelection_CruiserUnderAttack")
    KASSobGroup_Create("GrowSelection_DestroyersFoundSomeSCs")
    KASSobGroup_Create("GrowSelection_DestroyersL00kingForSCs")
    KASSobGroup_Create("GrowSelection_DestroyersNearbyTargets")
    KASSobGroup_Create("GrowSelection_DestroyersUnderAttack")
    KASSobGroup_Create("GrowSelection_Everyone")
    KASSobGroup_Create("GrowSelection_IonFrigFoundSomeSCs")
    KASSobGroup_Create("GrowSelection_IonFrigL00kingForSCs")
    KASSobGroup_Create("GrowSelection_IonFrigNearbyTargets")
    KASSobGroup_Create("GrowSelection_IonFrigUnderAttack")
    KASSobGroup_Create("GrowSelection_Mothership")
    KASSobGroup_Create("GrowSelection_Null8723487238")
    KASSobGroup_Create("GrowSelection_Null87238923")
    KASSobGroup_Create("GrowSelection_Null929292")
    KASSobGroup_Create("GrowSelection_PlayerFleet")
    KASSobGroup_Create("GrowSelection_PlayerMothership")
    KASSobGroup_Create("GrowSelection_TraderTargets")
    KASSobGroup_CreateIfNotExist("Cruiser")
    KASSobGroup_CreateIfNotExist("Destroyers")
    KASSobGroup_CreateIfNotExist("IonCannonFrigates")
    KASSobGroup_CreateIfNotExist("Traders")

    Sound_SpeechSubtitlePath("speech:missions/Mission11/")
    Scar_TracesEnable("SGAction, SGQuery, Camera, ATI, Player")

    LCWatcher_SpecifyLocalFilter(LC_Scar, "_VIFONCE;Cruiser;Destroyers;IonCannonFrigates;FleetIntel;Traders;")
    KAS_SetColourSchemeColours(1, {1,0.823529411764706,0}, {1, 0, 0}, "DATA:Badges/Turanic.tga", {0.921,0.75,0.419}, "data:/effect/trails/tur_trail_clr.tga")
    Player_SetTeamColourTheme(1, {1,0.823529411764706,0}, {1, 0, 0}, "DATA:Badges/Turanic.tga", {0.921,0.75,0.419}, "data:/effect/trails/tur_trail_clr.tga")
    Player_SetTeamColourTheme(3, {1,0.823529411764706,0}, {1, 0, 0}, "DATA:Badges/Turanic.tga", {0.921,0.75,0.419}, "data:/effect/trails/tur_trail_clr.tga")
    Player_SetPlayerName(1, "$60648")
    Player_SetPlayerName(2, "$60649")

    singlePlayerOnStartOrLoad(11)
end

function OnInit()
    print("OnInit issued")

    Player_RestrictAllResearch(0, 1)
    SobGroup_LoadPersistantData("Kus_Mothership")
    Camera_Interpolate('here', 'Camera_Startpos', 0)
    KAS_RememberStartingRUs()
    singlePlayerStartGame(11)
    KAS_CPUPlayerInit()

    KASRule_Add("Mission11", "Watch_Mission11", "OnInit")
    Init_Mission11("Mission11")
    KAS_SetLetterboxStart(1, 5, 1, 0)
    singlePlayerPauseUntilHyperspaceComplete("OnInit_Finish()")
end

function OnInit_Finish()
    print("OnInit_Finish issued")

    KAS_MusicPlayType( "data:sound/music/ambient/A09_mission11and15", MUS_Ambient )
end

