-- string id's 
StringTable = {
	{ name = "ExitMsg", 			string = "$1110" },
	{ name = "InvalidChatName", 		string = "$1111" },
	{ name = "SaveErrorGeneral",		string = "$1112" },
	{ name = "SaveErrorFilename",	string = "$1113" },
	{ name = "SaveVerify",			string = "$1114" },
	{ name = "LoadErrorGeneral",		string = "$1115" },
	{ name = "LoadErrorFilename",	string = "$1116" },
	{ name = "LoadVerify",			string = "$1117" },
	{ name = "RecErrorNoSize",		string = "$1118" },
	{ name = "RecErrorSize",		string = "$1119" },
	{ name = "RecErrorFilename",		string = "$1120" },
	{ name = "RecErrorVersion",		string = "$1121" },
	{ name = "DeleteVerify",		string = "$1122" },
	{ name = "DeleteErrorGeneral", 	string = "$1123" },
	{ name = "NoProfileSelected",  	string = "$1124" },
	{ name = "ProfileAlreadyExists", 	string = "$1125" },
	{ name = "BadProfileName",       	string = "$1126" },
	{ name = "ModNotFound",         	string = "$1223" }, 
	{ name = "RestartMsg",	        	string = "$1128" },
	{ name = "DoneTutorials",	        string = "$1129" },
	{ name = "RetireMsg",	        	string = "$1130" },
	{ name = "ResetCampaign",         	string = "$1131" },
	{ name = "ProfileDelete",         	string = "$1132" },
	{ name = "RefitSubsystem",		string = "$1133" },
	{ name = "RestoreControlDefaults",	string = "$1134" },
	{ name = "KeyTaken", 			string = "$1135" },
	{ name = "KeyUnavailable",		string = "$1136" },
	{ name = "ResetKey",			string = "$1137" },
	{ name = "KeyUnassiged",		string = "$1138" },
	{ name = "EnterKey",			string = "$1139" },
	{ name = "RestoreProfileDefaults",	string = "$1140" },
	{ name = "ConfirmPasswordError", 	string = "$1141" },
	{ name = "ApplyUpdate", 		string = "$1142" },
	{ name = "ChatNameWarning", 	string = "$1143" },	
	{ name = "RestoreDefaultOptions", 	string = "$1144" },
	{ name = "KeyUpSequence", string = "$1145" },
	{ name = "CPUEasy", 		string = "$2571"},
	{ name = "CPUStandard", 	string = "$2572"},
	{ name = "CPUHard", 		string = "$2573"},
	{ name = "CPUExpert", 	string = "$2574"},
	{ name = "SlotCPU", 		string = "$2575"},
	{ name = "SlotOpen", 	string = "$2576"},
	{ name = "SlotClosed", 	string = "$2577"},
	{ name = "SlotHuman", 	string = "$2578"},
	{ name = "RezChange", 	string = "$1147"},
}