base_research = nil 
base_research = {

	{ 
		Name =			"WeakVgrHeavyMissiles",
		RequiredResearch =	"RESEARCH HACK",
		RequiredSubSystems =	"",
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"Reduces damage on Vgr Heavy Missiles (SP Game only!)",
		DisplayPriority =	1205,
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName =		"Vgr_HeavyMissileFrigate",
	        UpgradeName =		"WeaponDamage",
        	UpgradeValue =		0.25,
	},

	{
		Name =			"HyperspaceRecoveryTimeUpgradeSPGAME",
		RequiredResearch =	"RESEARCH HACK",
		RequiredSubSystems =	"",
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"Hyperspace Recovery - SP GAME ONLY",
		DisplayPriority =	1206,
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		AllShips,
	        UpgradeName =		"HyperspaceRecoveryTime",
	        UpgradeValue =		0.01,
	},

	{
		Name =			"VaygrCarrierHealthRegenDowngrade",
		RequiredResearch =	"RESEARCH HACK",                        
		RequiredSubSystems =	"",                              
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"Vaygr Carrier Health Regen Rate Downgrade",
		DisplayPriority =	1207,                                                   
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName =		"Vgr_Carrier",
	        UpgradeName =		"HealthRegenerationRate",
	        UpgradeValue =		0.1,
	},

	
	{
		Name =			"HyperspaceTransitionTimeUpgradeSPGAME",
		RequiredResearch =	"RESEARCH HACK",
		RequiredSubSystems =	"",
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"Hyperspace Transition - SP GAME ONLY",
		DisplayPriority =	1206,
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		AllShips,
	        UpgradeName =		"HyperspaceTime",
	        UpgradeValue =		0.1,
	},

	{ 
		Name =			"SuperCapHealthUpgradeSPGAME",
		RequiredResearch =	"RESEARCH HACK",                       
		RequiredSubSystems =	"",                              
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"Vgr Super Cap Health Upgrade",
		DisplayPriority =	1208,                                                    
		Description =		"Vaygr Carrier Health upgrade - SP GAME ONLY",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
	        UpgradeName =		"MAXHEALTH",
	        UpgradeValue =		2.5,
	},

-- Stronger ships, secretly
	{ 
		Name =			"SuperCapDamageAppliedSPGAME",
		RequiredResearch =	"RESEARCH HACK",                       
		RequiredSubSystems =	"",                              
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"",
		DisplayPriority =	1208,                                                    
		Description =		"Secret Upgrade",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Capital",
	        UpgradeName =		"DAMAGEAPPLIED",
	        UpgradeValue =		0.572,
	},
--
	{ 
		Name =			"ShipyardSpeedDowngradeSPGAME",
		RequiredResearch =	"RESEARCH HACK",                       
		RequiredSubSystems =	"",                              
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"Vaygr Shipyard Speed downgrade",
		DisplayPriority =	1208,                                                    
		Description =		"Vaygr Shipyard Speed downgrade - SP GAME ONLY",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName =		"Vgr_ShipYard",
	        UpgradeName =		"MAXSPEED",
	        UpgradeValue =		0.0001,
	},

	{ 
		Name =			"VaygrFrigateHealthUpgradeSPGAME",
		RequiredResearch =	"RESEARCH HACK",                       
		RequiredSubSystems =	"",                              
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"Vgr Frigate Health Upgrade",
		DisplayPriority =	1208,                                                    
		Description =		"Vaygr Frigate Health upgrade - SP GAME ONLY",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Frigate",
	        UpgradeName =		"MAXHEALTH",
	        UpgradeValue =		2.0,
	},

	{
		Name =			"VaygrFrigateHealthRegenDowngradeSPGAME",
		RequiredResearch =	"RESEARCH HACK",                        
		RequiredSubSystems =	"",                              
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"Vaygr Frigate Health Regen Rate Downgrade",
		DisplayPriority =	1207,                                                   
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Frigate",
	        UpgradeName =		"HealthRegenerationRate",
	        UpgradeValue =		0.1,
	},

	{ 
		Name =			"CorvetteHealthUpgradeSPGAME",
		RequiredResearch =	"RESEARCH HACK",                       
		RequiredSubSystems =	"",                              
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"Vgr Corvette Health Upgrade",
		DisplayPriority =	1208,                                                    
		Description =		"Vaygr Corvette Health upgrade - SP GAME ONLY",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Corvette",
	        UpgradeName =		"MAXHEALTH",
	        UpgradeValue =		3.0,
	},

	{ 
		Name =			"ExtraStrongVgrHeavyMissilesSPGAME",
		RequiredResearch =	"RESEARCH HACK",
		RequiredSubSystems =	"",
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"Increases damage on Vgr Heavy Missiles (SP Game only!)",
		DisplayPriority =	1205,
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName =		"Vgr_HeavyMissileFrigate",
	        UpgradeName =		"WeaponDamage",
        	UpgradeValue =		1.35,
	},
	
	{ 
		Name =			"VaygrCaptureHack",
		RequiredResearch =	"RESEARCH HACK",
		RequiredSubSystems =	"",
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"Increases Capture Speed (SP Game only!)",
		DisplayPriority =	1205,
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName =		"Vgr_InfiltratorFrigate",
	        UpgradeName =		"Capture",
        	UpgradeValue =		1.35,
	},

	{ 
		Name =			"VaygrReduceCaptureHack",
		RequiredResearch =	"RESEARCH HACK",
		RequiredSubSystems =	"",
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"Increases Capture Speed (SP Game only!)",
		DisplayPriority =	1205,
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName =		"Vgr_InfiltratorFrigate",
	        UpgradeName =		"Capture",
        	UpgradeValue =		.75,
	},

	{ 
		Name =			"VaygrRadiationImmunityHack",
		RequiredResearch =	"RESEARCH HACK",
		RequiredSubSystems =	"",
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"Makes Vaygr Immune to Radiation (SP Game only!)",
		DisplayPriority =	1205,
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		AllShips,
	        UpgradeName =		"NebulaSensitivity",
        	UpgradeValue =		0,
	},
	{
		Name =			"VaygrCarrierHealthUpgrade",
		RequiredResearch =	"RESEARCH HACK",                        
		RequiredSubSystems =	"",                              
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"Vaygr Carrier Health Upgrade",
		DisplayPriority =	1208,                                                   
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName =		"Vgr_Carrier",
	        UpgradeName =		"MAXHEALTH",
	        UpgradeValue =		3,
	},

-- Makaan's Elite Guard
	{
		Name =			"MakaanCarrierHealth",
		RequiredResearch =	"RESEARCH HACK",                        
		RequiredSubSystems =	"",    
                Cost = 			0,
		Time = 			0,
		DisplayedName =		"",
		DisplayPriority =	1208,                                                   
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName =		"Vgr_Carrier",
	        UpgradeName =		"MAXHEALTH",
	        UpgradeValue =		1.8,
	},
	{
		Name =			"MakaanDestroyerHealth",
		RequiredResearch =	"RESEARCH HACK",                        
		RequiredSubSystems =	"",    
                Cost = 			0,
		Time = 			0,
		DisplayedName =		"",
		DisplayPriority =	1208,                                                   
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName =		"Vgr_Destroyer",
	        UpgradeName =		"MAXHEALTH",
	        UpgradeValue =		1.8,
	},
	{
		Name =			"MakaanShipyardHealth",
		RequiredResearch =	"RESEARCH HACK",                        
		RequiredSubSystems =	"",    
                Cost = 			0,
		Time = 			0,
		DisplayedName =		"",
		DisplayPriority =	1208,                                                   
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName =		"Vgr_Shipyard",
	        UpgradeName =		"MAXHEALTH",
	        UpgradeValue =		1.8,
	},
	{
		Name =			"MakaanBattleCruiserHealth",
		RequiredResearch =	"RESEARCH HACK",                        
		RequiredSubSystems =	"",                              
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"",
		DisplayPriority =	1208,                                                   
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName =		"Vgr_BattleCruiser",
	        UpgradeName =		"MAXHEALTH",
	        UpgradeValue =		1.475,
	},
	{
		Name =			"MakaanFrigateHealth",
		RequiredResearch =	"RESEARCH HACK",                        
		RequiredSubSystems =	"",                              
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"",
		DisplayPriority =	1208,                                                   
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Frigate",
	        UpgradeName =		"MAXHEALTH",
	        UpgradeValue =		1.6,
	},
	{
		Name =			"MakaanCorvetteHealth",
		RequiredResearch =	"RESEARCH HACK",                        
		RequiredSubSystems =	"",                              
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"",
		DisplayPriority =	1208,                                                   
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Corvette",
	        UpgradeName =		"MAXHEALTH",
	        UpgradeValue =		1.6,
	},
	{
		Name =			"MakaanFighterHealth",
		RequiredResearch =	"RESEARCH HACK",                        
		RequiredSubSystems =	"",                              
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"",
		DisplayPriority =	1208,                                                   
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Corvette",
	        UpgradeName =		"MAXHEALTH",
	        UpgradeValue =		1.5,
	},
	{
		Name =			"MakaanUtilityHealth",
		RequiredResearch =	"RESEARCH HACK",                        
		RequiredSubSystems =	"",                              
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"",
		DisplayPriority =	1208,                                                   
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Utility",
	        UpgradeName =		"MAXHEALTH",
	        UpgradeValue =		2.25,
	},
	{
		Name =			"MakaanPlatformHealth",
		RequiredResearch =	"RESEARCH HACK",                        
		RequiredSubSystems =	"",                              
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"",
		DisplayPriority =	1208,                                                   
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Family,
		TargetName =		"Platform",
	        UpgradeName =		"MAXHEALTH",
	        UpgradeValue =		2.15,
	},

-- Normal Vaygr bumps
	{ 
		Name =			"StrongerGunPlats",
		RequiredResearch =	"RESEARCH HACK",
		RequiredSubSystems =	"",
		Cost = 			0,
		Time = 			0,
		DisplayedName =		" (SP Game only!)",
		DisplayPriority =	1205,
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName =		"Vgr_WeaponPlatform_gun",
	        UpgradeName =		"WeaponDamage",
        	UpgradeValue =		1.15,
	},
	{ 
		Name =			"StrongerMissilePlats",
		RequiredResearch =	"RESEARCH HACK",
		RequiredSubSystems =	"",
		Cost = 			0,
		Time = 			0,
		DisplayedName =		"(SP Game only!)",
		DisplayPriority =	1205,
		Description =		"",
		UpgradeType =		Modifier,
		TargetType =		Ship,
		TargetName =		"Vgr_WeaponPlatform_missile",
	        UpgradeName =		"WeaponDamage",
        	UpgradeValue =		1.15,
	},
}


-- Add these items to the research tree!
for i,e in base_research do
	research[res_index] = e
	res_index = res_index+1
end
base_research = nil 
