--  ============================================================================= 
-- Homeworld 2 Clean Data Resource Project
-- By S110
-- Version 1.0
-- 02/06/2010
-- Tools used: EditPad Lite, LuaDC version 0.9.19, and Cold Fusion LUA Decompiler v1.0.0
--  =============================================================================


at 0
	cameraCut("camera1")

at 0
	wideScreenIn(1)

at 0
	cameraCut("camera1")

cameraBlendIn(4)

with |HitEffect3
{
	at 4.7
		show()
}

with |HitEffect2
{
	at 5.0
		show()
}

with |HitEffect1
{
	at 5.2
		show()
}

with |TurretExplosion
{
	at 8
		show()
}


at 10
	wideScreenOut(2)
