Number_Properties_Priority = 3.0

Number_Properties = {
	dm_challenge_research_baseline = 5,
}

String_Properties_Priority = 3.0

String_Properties = {

	dm_fightersonly_build_restrict = "Vgr_MS_Production_Corvette,Vgr_C_Production_Corvette,Vgr_MS_Production_Frigate,Vgr_C_Production_Frigate,Vgr_MS_Production_CapShip,Vgr_SY_Production_CapShip",
	dm_fightersonly_research_restrict = "CorvetteTech,FrigateTech",
	dm_fightersandvettesonly_build_restrict = "Vgr_MS_Production_Frigate,Vgr_C_Production_Frigate,Vgr_MS_Production_CapShip,Vgr_SY_Production_CapShip",
	dm_fightersandvettesonly_research_restrict = "FrigateTech",
	dm_vettesonly_build_restrict = "Vgr_MS_Production_Fighter,Vgr_C_Production_Fighter,Vgr_MS_Production_Frigate,Vgr_C_Production_Frigate,Vgr_MS_Production_CapShip,Vgr_SY_Production_CapShip",
	dm_vettesonly_research_restrict = "",
	dm_frigatesonly_build_restrict = "VGR_SCOUT,Vgr_MS_Production_Fighter,Vgr_C_Production_Fighter,Vgr_MS_Production_Corvette,Vgr_C_Production_Corvette,Vgr_MS_Production_CapShip,Vgr_SY_Production_CapShip",
	dm_frigatesonly_research_restrict = "CorvetteTech",
	dm_destroyersonly_build_restrict = "VGR_SCOUT,Vgr_MS_Production_Fighter,Vgr_C_Production_Fighter,Vgr_MS_Production_Corvette,Vgr_C_Production_Corvette,Vgr_MS_Production_Frigate,Vgr_C_Production_Frigate,Vgr_Carrier",
	dm_destroyersonly_research_restrict = "CorvetteTech,FrigateTech",
	dm_disablebuilding_build_restrict = "VGR_SCOUT,Vgr_MS_Production_Fighter,Vgr_C_Production_Fighter,Vgr_MS_Production_Corvette,Vgr_C_Production_Corvette,Vgr_MS_Production_Frigate,Vgr_C_Production_Frigate,Vgr_MS_Production_CapShip,Vgr_SY_Production_CapShip,Vgr_MS_Module_Research,Vgr_C_Module_Research",
	dm_disablebuilding__research_restrict = "", 
	dm_strikecraftgamemode_build_restrict = "Vgr_AssaultFrigate,Vgr_HeavyMissileFrigate,Vgr_Destroyer,Vgr_Battlecruiser",
	dm_strikecraftgamemode_research_restrict = "FrigateAssault,BattlecruiserIonWeapons,DestroyerGuns,SuperCapHealthUpgrade1,FrigateHealthUpgrade1",
	dm_strikecraftgamemode_grant = "SGMCapitalHealth,SGMFrigateHealth,SGMCarrierHealth,SGMShipyardHealth",
}
