-- pairs, when first state is set so is the second
inclusive =
{
    "Normal", "Docked",
    "Normal", "Closed",
    "Normal", "CodeGreen",
    "Normal", "ResourceEnd",
    "Normal", "RepairEnd",
    "Normal", "DockPathClosed",
    "Normal", "DockPathClosed1",
    "Normal", "DockPathClosed2",
    "Normal", "DockPathClosed3",
    "Normal", "DockPathClosed4",
    "Normal", "DockPathClosed5",
    "Normal", "DefenseFieldDeActivate",
    "Normal", "CloakFieldDeactivate",
    "Normal", "HyperspaceGateDeActivate",
    "Normal", "CaptureInActive",
	"Normal", "CustomCommandDeActivate",
};

-- pairs, when the first state is set then the second is unset
exclusive =
{
    "Open",             "Closed",
    "Closed",           "Open",
    "CodeGreen",        "CodeRed",
    "CodeRed",          "CodeGreen",
    "ResourceStart",    "ResourceDo",       "ResourceStart",    "ResourceEnd",
    "ResourceDo",       "ResourceStart",    "ResourceDo",       "ResourceEnd",
    "ResourceEnd",      "ResourceStart",    "ResourceEnd",      "ResourceDo",
    "RepairStart",      "RepairDo",         "RepairStart",      "RepairEnd",
    "RepairDo",         "RepairStart",      "RepairDo",         "RepairEnd",
    "RepairEnd",        "RepairStart",      "RepairEnd",        "RepairDo",
    "DockPathClosed",   "DockPathOpen",
    "DockPathClosed1",   "DockPathOpen1",
    "DockPathClosed2",   "DockPathOpen2",
    "DockPathClosed3",   "DockPathOpen3",
    "DockPathClosed4",   "DockPathOpen4",
    "DockPathClosed5",   "DockPathOpen5",
    "DockPathOpen",     "DockPathClosed",
    "DockPathOpen1",     "DockPathClosed1",
    "DockPathOpen2",     "DockPathClosed2",
    "DockPathOpen3",     "DockPathClosed3",
    "DockPathOpen4",     "DockPathClosed4",
    "DockPathOpen5",     "DockPathClosed5",
    "Docked",           "Launched",
    "Launched",         "Docked",
    "DefenseFieldDeActivate",   "DefenseFieldActivate",
    "DefenseFieldActivate",     "DefenseFieldDeActivate",
    "CloakFieldDeactivate",     "CloakFieldActivate",
    "CloakFieldActivate",       "CloakFieldDeactivate",
    "HyperspaceGateDeActivate", "HyperspaceGateActivate",
    "HyperspaceGateActivate",   "HyperspaceGateDeActivate",
    "Normal",               "DoingFlightManeuver",
    "DoingFlightManeuver",  "Normal",
    "CaptureActive",    "CaptureInActive",
    "CaptureInActive",  "CaptureActive",
	"CustomCommandActivate",     "CustomCommandDeActivate",
	"CustomCommandDeActivate",   "CustomCommandActivate",
};

