------------------------------------------------------------------
-- mapping table from speech event name to localized event text --

-- NOTE: Names need to be all UPPERCASE

STATUS_FRIGATEDIES_1 = "$5600"	-- Frigate lost
STATUS_MOBILEREFINERYDIES_1 = "$5601"	-- Mobile Refinery destroyed
STATUS_DESTROYERDIES_1 = "$5602"	-- Destroyer lost
STATUS_CARRIERDIES_1 = "$5603"	-- Carrier destroyed
STATUS_SHIPYARDDIES_1 = "$5604"	-- Shipyard destroyed
STATUS_BATTLECRUISERDIES_1 = "$5605"	-- Battlecruiser destroyed
STATUS_HEAVYCRUISERDIES_1 = "$5853"	-- Heavy Cruiser destroyed

STATUS_ENEMYFRIGATECAPTURED_1 = "$5606"	-- Enemy Frigate captured
STATUS_ENEMYDESTROYERCAPTURED_1 = "$5607"	-- Enemy Destroyer captured
STATUS_ENEMYCARRIERCAPTURED_1 = "$5608"	-- Enemy Carrier captured
STATUS_ENEMYSHIPYARDCAPTURED_1 = "$5609"	-- Enemy Shipyard captured
STATUS_ENEMYBATTLECRUISERCAPTURED_1 = "$5610"	-- Enemy Battlecruiser captured
STATUS_ENEMYHEAVYCRUISERCAPTURED_1 = "$5854"	-- Enemy Heavy Cruiser captured
STATUS_ENEMYMARINEFRIGATEATTACK_CARRIER_1 = "$5611"	-- Frigate being boarded
STATUS_ENEMYMARINEFRIGATEATTACK_CARRIER_1 = "$5612"	-- Destory being boarded
STATUS_ENEMYMARINEFRIGATEATTACK_CARRIER_1 = "$5613"	-- Carrier being boarded
STATUS_ENEMYMARINEFRIGATEATTACK_BATTLECRUISER_1 = "$5614"	-- Battlecruiser being boarded
STATUS_ENEMYMARINEFRIGATEATTACK_HEAVYCRUISER_1	= "$5855"	-- Heavy Cruiser being boarded
STATUS_ENEMYMARINEFRIGATEATTACK_MOTHERSHIP_1 = "$5615"	-- Mothership being boarded
STATUS_ENEMYMARINEFRIGATEATTACK_SHIPYARD_1 = "$5616"	-- Shipyard being boarded
STATUS_ENEMYMARINEFRIGATEATTACK_DREADNAUGHT_1 = "$5617"	-- Dreadnaught being boarded
--STATUS_MOTHERSHIPUNDERSMALLATTACK_REPORT_1 = "$5618"	-- Mothership under attack
--STATUS_MOTHERSHIPUNDERSMALLATTACK_REPORT_2 = "$5619"	-- Mothership under attack
STATUS_MOTHERSHIPUNDERSMALLATTACK_REPORT = "$5620"	-- Mothership under attack
--STATUS_MOTHERSHIPUNDERLARGEATTACK_REPORT_1 = "$5621"	-- Mothership under attack
--STATUS_MOTHERSHIPUNDERLARGEATTACK_REPORT_2 = "$5622"	-- Mothership under attack
STATUS_MOTHERSHIPUNDERLARGEATTACK_REPORT = "$5623"	-- Mothership under attack
--STATUS_DREADNAUGHTUNDERSMALLATTACK_REPORT_1 = "$5624"	-- Dreadnaught under attack
--STATUS_DREADNAUGHTUNDERSMALLATTACK_REPORT_2 = "$5625"	-- Dreadnaught under attack
STATUS_DREADNAUGHTUNDERSMALLATTACK_REPORT = "$5626"	-- Dreadnaught under attack
--STATUS_DREADNAUGHTUNDERLARGEATTACK_REPORT_1 = "$5627"	-- Dreadnaught under attack
--STATUS_DREADNAUGHTUNDERLARGEATTACK_REPORT_2 = "$5628"	-- Dreadnaught under attack
STATUS_DREADNAUGHTUNDERLARGEATTACK_REPORT = "$5629"	-- Dreadnaught under attack
STATUS_DREADNAUGHTDESTROYED_REPORT_1 = "$5630"	-- Dreadnaught Destoryed
STATUS_DREADNAUGHTDESTROYEDGAMEOVER_REPORT_1 = "$5631"	-- Dreadnaught Destoryed
STATUS_SAJUUKUNDERSMALLATTACK_REPORT_1 = "$5632"	-- Sajuuk under attack
STATUS_SAJUUKUNDERSMALLATTACK_REPORT_2 = "$5633"	-- Sajuuk under attack
STATUS_SAJUUKUNDERSMALLATTACK_REPORT_3 = "$5634"	-- Sajuuk under attack
STATUS_SAJUUKUNDERLARGEATTACK_REPORT_1 = "$5635"	-- Sajuuk under attack
STATUS_SAJUUKUNDERLARGEATTACK_REPORT_2 = "$5636"	-- Sajuuk under attack
STATUS_SAJUUKUNDERLARGEATTACK_REPORT_3 = "$5637"	-- Sajuuk under attack
STATUS_SAJUUKDESTROYED_REPORT_1 = "$5638"	-- Sajuuk destoryed
STATUS_SAJUUKDESTROYEDGAMEOVER_REPORT_1 = "$5639"	-- Sajuuk destoryed
STATUS_SHIPYARDDESTROYED_REPORT_1 = "$5640"	-- Shipyard destroyed
STATUS_SHIPYARDDESTROYEDGAMEOVER_REPORT_1 = "$5641"	-- Shipyard destroyed

STATUS_LONGRANGETORPEDOLAUNCHDETECTED_1 = "$5642"	-- Torpedo detected
STATUS_DESTORYERUNDERATTACK_0 = "$5643"	-- Destroyer under attack
STATUS_CARRIERUNDERATTACK_1 = "$5644"	-- Carrier under attack
STATUS_BATTLECRUISERUNDERATTACK_1 = "$5645"	-- Battlecruiser under attack
STATUS_HEAVYCRUISERUNDERATTACK_1 = "$5856"	-- Heavy Cruiser under attack
STATUS_SHIPYARDUNDERATTACK_1 = "$5646"	-- Shipyard under attack
STATUS_SUBSYSTEMDESTROYED_2 = "$5647"	-- Subsystem lost.
STATUS_MOTHERSHIP_FIGHTERFACILITYUNDERATTACK_1 = "$5648"	-- Mothership Fighter Facility under attack.
STATUS_MOTHERSHIP_FIGHTERFACILITYDAMAGED_1 = "$5649"	-- Mothership Fighter Facility damaged.
STATUS_MOTHERSHIP_FIGHTERFACILITYDESTROYED_1 = "$5650"	-- Mothership Fighter Facility lost.
STATUS_MOTHERSHIP_CORVETTEFACILITYUNDERATTACK_1 = "$5651"	-- Mothership Corvette Facility under attack.
STATUS_MOTHERSHIP_CORVETTEFACILITYDAMAGED_1 = "$5652"	-- Mothership Corvette Facility damaged.
STATUS_MOTHERSHIP_CORVETTEFACILITYDESTROYED_1 = "$5653"	-- Mothership Corvette Facility lost.
STATUS_MOTHERSHIP_FRIGATEFACILITYUNDERATTACK_1 = "$5654"	-- Mothership Frigate Facility under attack.
STATUS_MOTHERSHIP_FRIGATEFACILITYDAMAGED_1 = "$5655"	-- Mothership Frigate Facility damaged.
STATUS_MOTHERSHIP_FRIGATEFACILITYDESTROYED_1 = "$5656"	-- Mothership Frigate Facility lost.
STATUS_MOTHERSHIP_ADVANCEDFRIGATEFACILITYUNDERATTACK_1 = "$5657"	-- Mothership Advanced Frigate Facility under attack.
STATUS_MOTHERSHIP_ADVANCEDFRIGATEFACILITYDAMAGED_1 = "$5658"	-- Mothership Advanced Frigate Facility damaged.
STATUS_MOTHERSHIP_ADVANCEDFRIGATEFACILITYDESTROYED_1 = "$5659"	-- Mothership Advanced Frigate Facility lost.
STATUS_MOTHERSHIP_PLATFORMFACILITYUNDERATTACK_1 = "$5660"	-- Mothership Platform Facility under attack.
STATUS_MOTHERSHIP_PLATFORMFACILITYDAMAGED_1 = "$5661"	-- Mothership Platform Facility damaged.
STATUS_MOTHERSHIP_PLATFORMFACILITYDESTROYED_1 = "$5662"	-- Mothership Platform Facility lost.
STATUS_MOTHERSHIP_CAPITALSHIPFACILITYUNDERATTACK_1 = "$5663"	-- Mothership Capital Ship Facility under attack.
STATUS_MOTHERSHIP_CAPITALSHIPFACILITYDAMAGED_1 = "$5664"	-- Mothership Capital Ship Facility damaged.
STATUS_MOTHERSHIP_CAPITALSHIPFACILITYDESTROYED_1 = "$5665"	-- Mothership Capital Ship Facility lost.
STATUS_MOTHERSHIP_ADVANCEDCAPITALSHIPFACILITYUNDERATTACK_1 = "$5666"	-- Mothership Advanced Capital Ship Facility under attack.
STATUS_MOTHERSHIP_ADVANCEDCAPITALSHIPFACILITYDAMAGED_1 = "$5667"	-- Mothership Advanced Capital Ship Facility damaged.
STATUS_MOTHERSHIP_ADVANCEDCAPITALSHIPFACILITYDESTROYED_1 = "$5668"	-- Mothership Advanced Capital Ship Facility lost.
STATUS_MOTHERSHIP_RESEARCHMODULEUNDERATTACK_1 = "$5669"	-- Mothership Research Module under attack.
STATUS_MOTHERSHIP_RESEARCHMODULEDAMAGED_1 = "$5670"	-- Mothership Research Module damaged.
STATUS_MOTHERSHIP_RESEARCHMODULEDESTROYED_1 = "$5671"	-- Mothership Research Module lost.
STATUS_MOTHERSHIP_SENSORARRAYUNDERATTACK_1 = "$5672"	-- Mothership Sensor Array under attack.
STATUS_MOTHERSHIP_SENSORARRAYDAMAGED_1 = "$5673"	-- Mothership Sensor Array damaged.
STATUS_MOTHERSHIP_SENSORARRAYDESTROYED_1 = "$5674"	-- Mothership Sensor Array lost.
STATUS_MOTHERSHIP_CLOAKGENERATORUNDERATTACK_1 = "$5675"	-- Mothership Cloak Generator under attack.
STATUS_MOTHERSHIP_CLOAKGENERATORDAMAGED_1 = "$5676"	-- Mothership Cloak Generator damaged.
STATUS_MOTHERSHIP_CLOAKGENERATORDESTROYED_1 = "$5677"	-- Mothership Cloak Generator lost.
STATUS_MOTHERSHIP_HYPERSPACECOREUNDERATTACK_1 = "$5678"	-- Mothership Hyperspace Module under attack.
STATUS_MOTHERSHIP_HYPERSPACECOREDAMAGED_1 = "$5679"	-- Mothership Hyperspace Module damaged.
STATUS_MOTHERSHIP_HYPERSPACECOREDESTROYED_1 = "$5680"	-- Mothership Hyperspace Module lost.
STATUS_MOTHERSHIP_FIRECONTROLTOWERUNDERATTACK_1 = "$5681"	-- Mothership Fire Control Tower under attack.
STATUS_MOTHERSHIP_FIRECONTROLTOWERDAMAGED_1 = "$5682"	-- Mothership Fire Control Tower damaged.
STATUS_MOTHERSHIP_FIRECONTROLTOWERDESTROYED_1 = "$5683"	-- Mothership Fire Control Tower lost.
STATUS_MOTHERSHIP_ENGINESUNDERATTACK_1 = "$5684"	-- Mothership Engines under attack.
STATUS_MOTHERSHIP_ENGINESDAMAGED_1 = "$5685"	-- Mothership Engines damaged.
STATUS_MOTHERSHIP_ENGINESDISABLED_1 = "$5686"	-- Mothership Engines disabled. We can't move.
STATUS_MOTHERSHIP_ENGINESREPAIRED_1 = "$5687"	-- Mothership Engines repaired. We can move.
STATUS_ARM_UNDERATTACK_2 = "$5688"	-- Advanced Research Module Under Attack
STATUS_ARM_DAMAGED_1 = "$5689"	-- Advanced Research Module damaged
STATUS_ARM_DESTROYED_1 = "$5690"	-- Advanced Research Module lost

STATUS_RESOURCECOLLECTORDESTROYED_REPORT_1 = "$5691"	-- Resource Collector destroyed
STATUS_RESOURCECOLLECTORDESTROYED_REPORT_3 = "$5692"	-- Resource Collector lost
STATUS_RESOURCECONTROLLERDAMAGED_1 = "$5693"	-- Mobile Refinery under fire.
STATUS_RESOURCECOLLECTORDAMAGED_1 = "$5694"	-- Mobile Refinery under attack
STATUS_RESOURCECONTROLLERDIES = "$5857"	-- Resouce Controller destroyed.
STATUS_RESOURCECONTROLLERCAPTURED = "$5858"	-- Resource Controller captured.
STATUS_RESOURCECONTROLLERDAMAGED = "$5860" 	-- Resource Controller under attack.

STATUS_UNITCAPREACHED_1 = "$5695"	-- Unit Limit Reached
STATUS_UNITCAPINCREASED_1 = "$5696"	-- Unit Limit increased
STATUS_UNITCAPDECREASED_1 = "$5697"	-- Unit Limit decreased
STATUS_SCOUTCONSTRUCTED_1 = "$5698"	-- Scout squadron complete
STATUS_INTERCEPTORCONSTRUCTED_1 = "$5699"	-- Interceptor squadron complete
STATUS_BOMBERCONSTRUCTED_1 = "$5700"	-- Bomber squadron complete
STATUS_ASSAULTCORVETTECONSTRUCTED_1 = "$5701"	-- Gunship Corvette squadron complete
STATUS_PULSARCORVETTECONSTRUCTED_1 = "$5702"	-- Pulsar Gunship squadron complete
STATUS_MINELAYERCORVETTECONSTRUCTED_1 = "$5703"	-- Minelayer Corvette  complete
STATUS_ASSAULTFRIGATECONSTRUCTED_1 = "$5704"	-- Flak Frigate complete
STATUS_TORPEDOFRIGATECONSTRUCTED_1 = "$5705"	-- Torpedo Frigate complete
STATUS_SUPPORTFRIGATECONSTRUCTED_1 = "$5706"	-- Support Frigate complete
STATUS_MARINEFRIGATECONSTRUCTED_1 = "$5707"	-- Marine Frigate complete
STATUS_DEFENSEFIELDFRIGATECONSTRUCTED_1 = "$5708"	-- Defense Field Frigate complete
STATUS_DESTROYERCONSTRUCTED_1 = "$5709"	-- Destroyer complete
STATUS_CARRIERCONSTRUCTED_1 = "$5710"	-- Carrier complete
STATUS_BATTLECRUISERCONSTRUCTED_1 = "$5711"	-- Battlecruiser complete
STATUS_SHIPYARDCONSTRUCTED_1 = "$5712"	-- Shipyard has arrived
STATUS_GUNTURRETCONSTRUCTED_1 = "$5713"	-- Gun Turret complete
STATUS_IONCANNONTURRETCONSTRUCTED_1 = "$5714"	-- Ion Cannon Turret complete
STATUS_RESOURCECOLLECTORCONSTRUCTED_1 = "$5715"	-- Resource Collector complete
STATUS_RESOURCECONTROLLERCONSTRUCTED_1 = "$5716"	-- Mobile Refinery complete
STATUS_PROBECONSTRUCTED_1 = "$5717"	-- Probe complete
STATUS_ECMPROBECONSTRUCTED_1 = "$5718"	-- ECM Probe complete
STATUS_PROXIMITYSENSORCONSTRUCTED_1 = "$5719"	-- Proximity Sensor complete
STATUS_ADVRESEARCHMODULECONSTRUCTEDFROMMOTHERSHIP_1 = "$5720"	-- Mothership Advanced Research Module Complete
STATUS_FIGHTERFACILITYCONSTRUCTEDFROMMOTHERSHIP_1 = "$5721"	-- Carrier Fighter Facility complete
STATUS_CORVETTEFACILITYCONSTRUCTEDFROMMOTHERSHIP_1 = "$5722"	-- Carrier Corvette Facility complete
STATUS_FIGHTERFACILITYCONSTRUCTEDFROMMOTHERSHIP_1 = "$5723"	-- Mothership Fighter Facility complete
STATUS_CORVETTEFACILITYCONSTRUCTEDFROMMOTHERSHIP_1 = "$5724"	-- Mothership Corvette Facility complete
STATUS_FRIGATEFACILITYCONSTRUCTEDFROMMOTHERSHIP_1 = "$5725"	-- Mothership Frigate Facility complete
STATUS_ADVANCEDFRIGATEFACILITYCONSTRUCTEDFROMMOTHERSHIP_1 = "$5726"	-- Mothership Advanced Frigate Facility complete
STATUS_PLATFORMFACILITYCONSTRUCTEDFROMMOTHERSHIP_1 = "$5727"	-- Mothership Platform Facility complete
STATUS_CAPITALSHIPFACILITYCONSTRUCTEDFROMMOTHERSHIP_1 = "$5728"	-- Mothership Capital Ship Facility complete
STATUS_ADVANCEDCAPITALSHIPFACILITYCONSTRUCTEDFROMMOTHERSHIP_1 = "$5729"	-- Mothership Advanced Capital Ship Facility complete
STATUS_RESEARCHMODULECONSTRUCTEDFROMMOTHERSHIP_1 = "$5730"	-- Mothership Research Module complete
STATUS_SENSORSARRAYCONSTRUCTEDFROMMOTHERSHIP_1 = "$5731"	-- Mothership Sensors Array complete
STATUS_CLOAKGENERATORCONSTRUCTEDFROMMOTHERSHIP_1 = "$5732"	-- Mothership Cloak Generator complete
STATUS_HYPERSPACECORECONSTRUCTEDFROMMOTHERSHIP_1 = "$5733"	-- Mothership Hyperspace Module complete
STATUS_FIRECONTROLTOWERCONSTRUCTEDFROMMOTHERSHIP_1 = "$5734"	-- Mothership Fire Control Tower complete
STATUS_NEWBUILDOPTIONS = "$5735"	-- New Build Options Available

STATUS_SCOUTCONSTRUCTED = "$5861"	-- Scout complete
STATUS_INTERCEPTORCONSTRUCTED = "$5862"	-- Interceptor complete
STATUS_ATTACKBOMBERCONSTRUCTED_1 = "$5863"	-- Attack Bomber complete
STATUS_DEFENDERCONSTRUCTED_1 = "$5864"	-- Defender complete
STATUS_CLOAKEDFIGHTERCONSTRUCTED_1 = "$5865"	-- Cloaked Fighter complete
STATUS_DEFENSEFIGHTERCONSTRUCTED_1 = "$5866"	-- Defense Fighter complete
STATUS_LIGHTCORVETTECONSTRUCTED_1 = "$5867"	-- Light Corvette complete
STATUS_HEAVYCORVETTECONSTRUCTED_1 = "$5868"	-- Heavy Corvette complete
STATUS_MULTIGUNCORVETTECONSTRUCTED_1 = "$5869"	-- Multi-Gun Corvette complete
STATUS_REPAIRCORVETTECONSTRUCTED_1 = "$5870"	-- Repair Corvette complete
STATUS_SALVAGECORVETTECONSTRUCTED_1 = "$5871"	-- Salvage Corvette complete
STATUS_ASSAULTFRIGATECONSTRUCTED = "$5873"	-- Assault Frigate complete
STATUS_IONCANNONFRIGATECONSTRUCTED_1 = "$5874"	-- Ion Cannon Frigate complete
STATUS_DRONEFRIGATECONSTRUCTED_1 = "$5875"	-- Drone Frigate complete
STATUS_HEAVYCRUISERCONSTRUCTED_1 = "$5877"	-- Heavy Cruiser complete
STATUS_RESOURCECONTROLLERCONSTRUCTED = "$5878"	-- Resource Controller complete
STATUS_CLOAKGENERATORCONSTRUCTED_1 = "$5879"	-- Cloak Generator complete
STATUS_GRAVWELLGENERATORCONSTRUCTED_1 = "$5880"	-- GravWell Generator complete
STATUS_PROXIMITYSENSORCONSTRUCTED_1 = "$5881"	-- Proximity Sensor complete
STATUS_SENSORSARRAYCONSTRUCTED_1 = "$5882"	-- Sensors Array complete

STATUS_STRIKEGROUP_UNDERATTACK_1 = "$5736"	-- Strikegroup under attack.

STATUS_ASSIGNEDGROUPUNDERATTACK_REPORT_G1_1 = "$5737"	-- Group one under attack
STATUS_ASSIGNEDGROUPUNDERATTACK_REPORT_G2_1 = "$5738"	-- Group two under attack
STATUS_ASSIGNEDGROUPUNDERATTACK_REPORT_G3_1 = "$5739"	-- Group three under attack
STATUS_ASSIGNEDGROUPUNDERATTACK_REPORT_G4_1 = "$5740"	-- Group four under attack
STATUS_ASSIGNEDGROUPUNDERATTACK_REPORT_G5_1 = "$5741"	-- Group five under attack
STATUS_ASSIGNEDGROUPUNDERATTACK_REPORT_G6_1 = "$5742"	-- Group six under attack
STATUS_ASSIGNEDGROUPUNDERATTACK_REPORT_G7_1 = "$5743"	-- Group seven under attack
STATUS_ASSIGNEDGROUPUNDERATTACK_REPORT_G8_1 = "$5744"	-- Group eight under attack
STATUS_ASSIGNEDGROUPUNDERATTACK_REPORT_G9_1 = "$5745"	-- Group nine under attack
STATUS_ASSIGNEDGROUPUNDERATTACK_REPORT_G10_1 = "$5746"	-- Group ten under attack
STATUS_ASSIGNEDGROUPUNDERATTACK_REPORT_G1_2 = "$5747"	-- Group one reports enemy contact
STATUS_ASSIGNEDGROUPUNDERATTACK_REPORT_G2_2 = "$5748"	-- Group two reports enemy contact
STATUS_ASSIGNEDGROUPUNDERATTACK_REPORT_G3_2 = "$5749"	-- Group three reports enemy contact
STATUS_ASSIGNEDGROUPUNDERATTACK_REPORT_G4_2 = "$5750"	-- Group four reports enemy contact
STATUS_ASSIGNEDGROUPUNDERATTACK_REPORT_G5_2 = "$5751"	-- Group five reports enemy contact
STATUS_ASSIGNEDGROUPUNDERATTACK_REPORT_G6_2 = "$5752"	-- Group six reports enemy contact
STATUS_ASSIGNEDGROUPUNDERATTACK_REPORT_G7_2 = "$5753"	-- Group seven reports enemy contact
STATUS_ASSIGNEDGROUPUNDERATTACK_REPORT_G8_2 = "$5754"	-- Group eight reports enemy contact
STATUS_ASSIGNEDGROUPUNDERATTACK_REPORT_G9_2 = "$5755"	-- Group nine reports enemy contact
STATUS_ASSIGNEDGROUPUNDERATTACK_REPORT_G10_2 = "$5756"	-- Group ten reports enemy contact
STATUS_HOTKEYGROUP_VICTORY_01_1 = "$5757"	-- Group One has defeated the enemy
STATUS_HOTKEYGROUP_VICTORY_02_1 = "$5758"	-- Group Two has defeated the enemy
STATUS_HOTKEYGROUP_VICTORY_03_1 = "$5759"	-- Group Three has defeated the enemy
STATUS_HOTKEYGROUP_VICTORY_04_1 = "$5760"	-- Group Four has defeated the enemy
STATUS_HOTKEYGROUP_VICTORY_05_1 = "$5761"	-- Group Five has defeated the enemy
STATUS_HOTKEYGROUP_VICTORY_06_1 = "$5762"	-- Group Six has defeated the enemy
STATUS_HOTKEYGROUP_VICTORY_07_1 = "$5763"	-- Group Seven has defeated the enemy
STATUS_HOTKEYGROUP_VICTORY_08_1 = "$5764"	-- Group Eight has defeated the enemy
STATUS_HOTKEYGROUP_VICTORY_09_1 = "$5765"	-- Group Nine has defeated the enemy
STATUS_HOTKEYGROUP_VICTORY_10_1 = "$5766"	-- Group Ten has defeated the enemy
STATUS_HOTKEYGROUP_VICTORY_01 = "$5767"	-- Group One reports victory
STATUS_HOTKEYGROUP_VICTORY_02 = "$5768"	-- Group Two reports victory
STATUS_HOTKEYGROUP_VICTORY_03 = "$5769"	-- Group Three reports victory
STATUS_HOTKEYGROUP_VICTORY_04 = "$5770"	-- Group Four reports victory
STATUS_HOTKEYGROUP_VICTORY_05 = "$5771"	-- Group Five reports victory
STATUS_HOTKEYGROUP_VICTORY_06 = "$5772"	-- Group Six reports victory
STATUS_HOTKEYGROUP_VICTORY_07 = "$5773"	-- Group Seven reports victory
STATUS_HOTKEYGROUP_VICTORY_08 = "$5774"	-- Group Eight reports victory
STATUS_HOTKEYGROUP_VICTORY_09 = "$5775"	-- Group Nine reports victory
STATUS_HOTKEYGROUP_VICTORY_10 = "$5776"	-- Group Ten reports victory
STATUS_HOTKEYGROUP_DEFEAT_01_1 = "$5777"	-- Group One lost
STATUS_HOTKEYGROUP_DEFEAT_02_1 = "$5778"	-- Group Two lost
STATUS_HOTKEYGROUP_DEFEAT_03_1 = "$5779"	-- Group Three lost
STATUS_HOTKEYGROUP_DEFEAT_04_1 = "$5780"	-- Group Four lost
STATUS_HOTKEYGROUP_DEFEAT_05_1 = "$5781"	-- Group Five lost
STATUS_HOTKEYGROUP_DEFEAT_06_1 = "$5782"	-- Group Six lost
STATUS_HOTKEYGROUP_DEFEAT_07_1 = "$5783"	-- Group Seven lost
STATUS_HOTKEYGROUP_DEFEAT_08_1 = "$5784"	-- Group Eight lost
STATUS_HOTKEYGROUP_DEFEAT_09_1 = "$5785"	-- Group Nine lost
STATUS_HOTKEYGROUP_DEFEAT_10_1 = "$5786"	-- Group Ten lost
STATUS_HOTKEYGROUP_DEFEAT_01_2 = "$5787"	-- Group One destroyed
STATUS_HOTKEYGROUP_DEFEAT_02_2 = "$5789"	-- Group Two destroyed
STATUS_HOTKEYGROUP_DEFEAT_03_2 = "$5790"	-- Group Three destroyed
STATUS_HOTKEYGROUP_DEFEAT_04_2 = "$5791"	-- Group Four destroyed
STATUS_HOTKEYGROUP_DEFEAT_05_2 = "$5792"	-- Group Five destroyed
STATUS_HOTKEYGROUP_DEFEAT_06_2 = "$5793"	-- Group Six destroyed
STATUS_HOTKEYGROUP_DEFEAT_07_2 = "$5794"	-- Group Seven destroyed
STATUS_HOTKEYGROUP_DEFEAT_08_2 = "$5795"	-- Group Eight destroyed
STATUS_HOTKEYGROUP_DEFEAT_09_2 = "$5796"	-- Group Nine destroyed
STATUS_HOTKEYGROUP_DEFEAT_20_2 = "$5797"	-- Group Ten destroyed
STATUS_HOTKEYGROUP_DEFEAT_01 = "$5798"	-- Group One defeated
STATUS_HOTKEYGROUP_DEFEAT_02 = "$5799"	-- Group Two defeated
STATUS_HOTKEYGROUP_DEFEAT_03 = "$5800"	-- Group Three defeated
STATUS_HOTKEYGROUP_DEFEAT_04 = "$5801"	-- Group Four defeated
STATUS_HOTKEYGROUP_DEFEAT_05 = "$5802"	-- Group Five defeated
STATUS_HOTKEYGROUP_DEFEAT_06 = "$5803"	-- Group Six defeated
STATUS_HOTKEYGROUP_DEFEAT_07 = "$5804"	-- Group Seven defeated
STATUS_HOTKEYGROUP_DEFEAT_08 = "$5805"	-- Group Eight defeated
STATUS_HOTKEYGROUP_DEFEAT_09 = "$5806"	-- Group Nine defeated
STATUS_HOTKEYGROUP_DEFEAT_10 = "$5807"	-- Group Ten defeated

STATUS_RESEARCHCOMPLETE_1 = "$5808"	-- Research complete
STATUS_RESEARCHAVALIABLE_1 = "$5809"	-- New Research  avaliable
STATUS_RESEARCHNORUS_1 = "$5810"	-- Insufficient resources.  Research paused.
STATUS_UPGRADECOMPLETE_1 = "$5811"	-- Upgrade complete
STATUS_UPGRADEAVALIABLE_1 = "$5812"	-- New Upgrades avaliable
STATUS_UPGRADENORUS_1 = "$5813"	-- Insufficient resources.  Upgrades paused.
STATUS_BUILDAVALIABLE_1 = "$5814"	-- New construction options avaliable
STATUS_BUILDSTRIKEAVALIABLE_1 = "$5815"	-- New Fighters avaliable for construction
STATUS_BUILDCORVETTEAVALIABLE_1 = "$5816"	-- New corvettes avaliable for construction
STATUS_BUILDFRIGATEAVALIABLE_1 = "$5817"	-- New frigates avaliable for construction
STATUS_BUILDCAPITALAVALIABLE_1 = "$5818"	-- New capital ships avaliable for construction
STATUS_BUILDSUPERCAPAVALIABLE_1 = "$5819"	-- New supercapital ships avaliable for construction
STATUS_BUILDUTILITYAVALIABLE_1 = "$5820"	-- New utility class ships avaliable for construction
STATUS_BUILDPLATFORMAVALIABLE_1 = "$5821"	-- New platforms avaliable for construction
STATUS_ADVRESEACHMODAVALIABLE = "$5822"	-- Research Module Complete
STATUS_RESEACHMODAVALIABLE = "$5823"	-- Advanced Research Module Complete

STATUS_PROBELAUNCHED_1 = "$5824"	-- Probe deployed
STATUS_PROBEDETECTED = "$5825"	-- Probe deployed
STATUS_PROXIMITYPROBEWARNING_1 = "$5826"	-- Probe deployed

STATUS_HYPERSPACEINSUFFICENT_1 = "$5827"	-- Insufficient resources for Hyperspace jump.  Jump aborted.
STATUS_HYPERSPACEINSUFFICENT_1 = "$5828"	-- Insufficient resources for Hyperspace jump.  Jump aborted.

COMMAND_BUILD_PAUSED_1 = "$5829"	-- Unit Limit reached
COMMAND_BUILD_PAUSED = "$5830"	-- Unit Limit reached
STATUS_UNITCAPREACHEDCAPTURE_1 = "$5831"	-- Unit Limit reached
COMMAND_MARINEFRIGATE_CAPTURE_WHEN_OVER_UNITLIMIT = "$5832"	-- Unit Limit reached

STATUS_RESOURCEPOCKETEXHAUSTEDGOINGIDLE_1 = "$5850" --Resources Exhausted

STATUS_BUILDNORUS_1 = "$5884"	-- Insufficient resources.  Build paused.
