--
--  Generated\Mission06.c
--
--  Finite state machine routines for "Mission06" mission
--
--  Copyright (C) 1998 Relic Entertainment Inc.
--  All rights reserved
--
--  This code was autogenerated from Mission06.kp by KAS2C Version 2.05
--


--#include "Generated\Mission06.h"  -- prototypes and #includes for exposed game functions

--extern AITeam *CurrentTeamP;
--#define kasThisTeamPtr CurrentTeamP

--  for run-time scoping of symbols (variables, timers, etc.)

-- List of ignored functions (stubbed out to ignoredFunction()):
--kasfSoundEvent
--kasfTutSetTextDisplayBoxToSubtitleRegion


dofilepath("data:scripts/SCAR/SCAR_Util.lua")             --stock HW2 scripting utilities
dofilepath("data:scripts/SCAR/KASUtil.lua")               --HW1->HW2 scripting utilities
dofilepath("data:scripts/SCAR/SinglePlayerFlow.lua")      --Emulation of HW1 singleplayer functionality
dofilepath("data:scripts/SCAR/SinglePlayerNIS.lua")       --Emulation of HW1 singleplayer NIS functionality
dofilepath("data:scripts/SCAR/SinglePlayerHyperspace.lua")--Emulation of HW1 hyperspace logic
dofilepath("data:scripts/SCAR/SpecialFlags.lua")          --Emulation of HW1 SPECIAL_xxx logic


--kas global variables, including variables used in ifOnce blocks
G_CLICK_ProtectMothership = 0
G_FISaidClearedField = 0
G_GoToTradersNebulaIsBad = 0
G_ModuleIsCharged = 0
G_NowPlayingNISLet = 0
G_PlayIonTechEvent = 0
G_PlayNislet = 0
G_PlaySuperCapTechEvent = 0
G_PlayTraderNISLet = 0
G_PlayerHasAttackedTraders = 0
G_PlayerHasClearedField = 0
G_ProtectMothershipHasPlayed = 0
G_TechEventHasPlayed = 0
G_TradersAreDone = 0
G_TradersAreDoneTalking = 0
G_TradersObliteratePlayer = 0
SetMediumGuns = 0
_VIFONCE012 = 0
_VIFONCE013 = 0
_VIFONCE014 = 0
_VIFONCE015 = 0
_VIFONCE016 = 0
_VIFONCE017 = 0
_VIFONCE018 = 0
_VIFONCE019 = 0
_VIFONCE020 = 0
_VIFONCE021 = 0
_VIFONCE022 = 0
_VIFONCE023 = 0
_VIFONCE024 = 0
_VIFONCE025 = 0
_VIFONCE026 = 0
_VIFONCE027 = 0
_VIFONCE028 = 0

--Following are global variables: created outside of the KAS structure and stubbed out here.
--G_Nislet60Complete : see SinglePlayerFlow.lua, nReferences: 1

--Following are Team-Scoped variables: referenced differently than globals.
IntelEvent = {["FleetIntel"] = 0}
_VIFONCE001 = {["FleetIntel"] = 0}
_VIFONCE002 = {["FleetIntel"] = 0}
_VIFONCE003 = {["FleetIntel"] = 0}
_VIFONCE004 = {["FleetIntel"] = 0}
_VIFONCE005 = {["FleetIntel"] = 0}
_VIFONCE006 = {["FleetIntel"] = 0}
_VIFONCE007 = {["FleetIntel"] = 0}
_VIFONCE008 = {["FleetIntel"] = 0}
_VIFONCE009 = {["FleetIntel"] = 0}
_VIFONCE010 = {["FleetIntel"] = 0}
_VIFONCE011 = {["FleetIntel"] = 0}

--Following are Team-Scoped timers: referenced differently than globals.
FIOpenSensorsTimer = {["FleetIntel"] = 13}
FIProtectMothershipENDTimer = {["FleetIntel"] = 14}
FIProtectMothershipLBXOutTimer = {["FleetIntel"] = 15}
FIProtectMothershipPINGTimer = {["FleetIntel"] = 16}
FIProtectMothershipTimer = {["FleetIntel"] = 17}


--kas timer names, with mappings to indices
TimerID_G_AsteroidTimer = 8
TimerID_G_BringUpTraderGUI = 0
TimerID_G_FCHyperspaceSuccessful = 2
TimerID_G_GivePlayerTimeToWithdrawAttack = 1
TimerID_G_GiveTechnology = 9
TimerID_G_PlayFCTalkToTraders = 6
TimerID_G_PlayFIClearedField = 3
TimerID_G_PlayTraderArrival = 4
TimerID_G_TradersAreInPlace = 5
TimerID_G_TradersHaveLeftTheBuilding = 7
TimerID_G_TradersWaitingToTrade = 11
TimerID_LocationCardTimer = 10
TimerID_WideScreenInBeforeNISLet = 12


--KAS objective names, set by KASObjective_Add
ObjectiveID_Hyperspace = 1
ObjectiveID_ProtectMothership = 0
ObjectiveID_Count = 2


--Pointer IDs, set by KASPointer_Add<xxx>
PointerID_CollisionEnvelopePOINTER = 0


--extern sdword CurrentMissionScope;
--extern char CurrentMissionScopeName[];

--  for displaying localized strings
strCurLanguage = 1  --Naive treatement of localization language.;

LSTRING_Savegame = {  -- multilingual strings
	"06 - Diamond Shoals",
	"06 - R�cifs de Diamant",
	"06 - Diamantengrund",
	"06 - Monta�as de diamantes",
	"06 - I diamanti", }
LSTRING_LocationCard = {  -- multilingual strings
	"DIAMOND SHOALS",
	"RECIFS DE DIAMANT",
	"DIAMANTENGRUND",
	"MONTA�AS DE DIAMANTES",
	"I DIAMANTI", }
LSTRING_FIProtectTASKBAR = {  -- multilingual strings
	"Protect the Mothership",
	"Protection du Vaisseau M�re.",
	"Das Mutterschiff sch�tzen.",
	"Proteger la Nave nodriza",
	"Proteggi l'Astronave Madre", }
LSTRING_TraderIntro = {  -- multilingual strings
	"Welcome.",
	"Bienvenue",
	"Willkommen.",
	"Bienvenido.",
	"Benvenuto.", }
LSTRING_TraderPurchaseMade = {  -- multilingual strings
	"Thank you.  Enjoy your purchase.",
	"Merci. Profitez bien de votre acquisition.",
	"Besten Dank. Erfreut euch an eurem Kauf.",
	"Gracias. Que disfrutes de tu compra.",
	"Grazie.  Buon divertimento con il vostro nuovo acquisto.", }
LSTRING_Hyperspace = {  -- multilingual strings
	"                      HYPERSPACE",
	"                      HYPERESPACE",
	"           HYPERRAUMSPRUNG",
	"                    HIPERESPACIO",
	"					IPERSPAZIO", }

--
--  "initialize" code for Mission06 FleetIntel FSM
--
function Init_Mission06_FleetIntel(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	--kasJump("FIIdle")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIIdle", "Init_Mission06_FleetIntel")
	Init_Mission06_FleetIntel_FIIdle(TeamName)
	return
	
end


--
--  "watch" code for Mission06 FleetIntel FSM
--
function Watch_Mission06_FleetIntel(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	
end


--
--  "initialize" code for Mission06 FleetIntel FCIntro state
--
function Init_Mission06_FleetIntel_FCIntro(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	KAS_SubtitleAddOnce(Actor_HW1_FleetCommand, "$60528", 3)    --kasfSpeechEvent((528 + 2048 + 268435456), 0)
	
end


--
--  "watch" code for Mission06 FleetIntel FCIntro state
--
function Watch_Mission06_FleetIntel_FCIntro(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	if (Subtitle_IsDoneOrSkipped(Actor_FleetIntel) ~= 0) then     --kasfIntelEventEnded()
	
	--kasJump("FIProtectMothershipLBXIn")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FCIntro")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIProtectMothershipLBXIn", "Watch_Mission06_FleetIntel_FCIntro")
	Init_Mission06_FleetIntel_FIProtectMothershipLBXIn(TeamName)
	return
	end
	
end


--
--  "initialize" code for Mission06 FleetIntel FIProtectMothershipLBXIn state
--
function Init_Mission06_FleetIntel_FIProtectMothershipLBXIn(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	KASRules_PauseExceptFSM(TeamName)    --kasfOtherKASPause()
	KAS_SetLetterboxState(2, 3)    --kasfWideScreenIn(90)
	--kasJump("FIProtectMothershipOpenSensors")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIProtectMothershipOpenSensors", "Init_Mission06_FleetIntel_FIProtectMothershipLBXIn")
	Init_Mission06_FleetIntel_FIProtectMothershipOpenSensors(TeamName)
	return
	
end


--
--  "watch" code for Mission06 FleetIntel FIProtectMothershipLBXIn state
--
function Watch_Mission06_FleetIntel_FIProtectMothershipLBXIn(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	
end


--
--  "initialize" code for Mission06 FleetIntel FIProtectMothershipOpenSensors state
--
function Init_Mission06_FleetIntel_FIProtectMothershipOpenSensors(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	KASTimer_Start(FIOpenSensorsTimer[TeamName], 4)
	
end


--
--  "watch" code for Mission06 FleetIntel FIProtectMothershipOpenSensors state
--
function Watch_Mission06_FleetIntel_FIProtectMothershipOpenSensors(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	if (KASTimer_IsExpiredIfSoDestroy(FIOpenSensorsTimer[TeamName]) ~= 0) then
	
	KAS_SensorsToggle(1, 1)    --kasfOpenSensors(1)
	KAS_UniversePause(1)    --kasfUniversePause()
	--kasJump("FIProtectMothership")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIProtectMothershipOpenSensors")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIProtectMothership", "Watch_Mission06_FleetIntel_FIProtectMothershipOpenSensors")
	Init_Mission06_FleetIntel_FIProtectMothership(TeamName)
	return
	end
	
end


--
--  "initialize" code for Mission06 FleetIntel FIProtectMothership state
--
function Init_Mission06_FleetIntel_FIProtectMothership(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	KASTimer_Start(FIProtectMothershipTimer[TeamName], 1)
	
end


--
--  "watch" code for Mission06 FleetIntel FIProtectMothership state
--
function Watch_Mission06_FleetIntel_FIProtectMothership(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	if (KASTimer_IsExpiredIfSoDestroy(FIProtectMothershipTimer[TeamName]) ~= 0) then
	
	--kasJump("FIProtectMothership2")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIProtectMothership")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIProtectMothership2", "Watch_Mission06_FleetIntel_FIProtectMothership")
	Init_Mission06_FleetIntel_FIProtectMothership2(TeamName)
	return
	end
	
end


--
--  "initialize" code for Mission06 FleetIntel FIProtectMothership2 state
--
function Init_Mission06_FleetIntel_FIProtectMothership2(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60529", 3)    --kasfSpeechEvent((529 + 4096 + 268435456), 0)
	G_ProtectMothershipHasPlayed = 1 --created,set
	
end


--
--  "watch" code for Mission06 FleetIntel FIProtectMothership2 state
--
function Watch_Mission06_FleetIntel_FIProtectMothership2(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	IntelEvent[TeamName] = 0 --destroyed
	IntelEvent[TeamName] = Subtitle_IsDoneOrSkipped(Actor_FleetIntel) --created,set    --kasfIntelEventEnded()
	if (IntelEvent[TeamName] == 2) then
	
	--kasJump("FIProtectMothershipEND")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIProtectMothership2")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIProtectMothershipEND", "Watch_Mission06_FleetIntel_FIProtectMothership2")
	Init_Mission06_FleetIntel_FIProtectMothershipEND(TeamName)
	return
	elseif (IntelEvent[TeamName] ~= 0) then
	
	--kasJump("FIProtectMothership3")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIProtectMothership2")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIProtectMothership3", "Watch_Mission06_FleetIntel_FIProtectMothership2")
	Init_Mission06_FleetIntel_FIProtectMothership3(TeamName)
	return
	end
	
end


--
--  "initialize" code for Mission06 FleetIntel FIProtectMothership3 state
--
function Init_Mission06_FleetIntel_FIProtectMothership3(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60530", 3)    --kasfSpeechEvent((530 + 4096 + 268435456), 0)
	--kasJump("FIProtectMothershipPING")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIProtectMothershipPING", "Init_Mission06_FleetIntel_FIProtectMothership3")
	Init_Mission06_FleetIntel_FIProtectMothershipPING(TeamName)
	return
	
end


--
--  "watch" code for Mission06 FleetIntel FIProtectMothership3 state
--
function Watch_Mission06_FleetIntel_FIProtectMothership3(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	
end


--
--  "initialize" code for Mission06 FleetIntel FIProtectMothershipPING state
--
function Init_Mission06_FleetIntel_FIProtectMothershipPING(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	KASTimer_Start(FIProtectMothershipPINGTimer[TeamName], 2)
	
end


--
--  "watch" code for Mission06 FleetIntel FIProtectMothershipPING state
--
function Watch_Mission06_FleetIntel_FIProtectMothershipPING(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	IntelEvent[TeamName] = 0 --destroyed
	IntelEvent[TeamName] = Subtitle_IsDoneOrSkipped(Actor_FleetIntel) --created,set    --kasfIntelEventEnded()
	if (IntelEvent[TeamName] == 2) then
	
	--KAS_SetLetterboxState(0, 1)    --kasfWideScreenOut(30)
	--kasJump("FIProtectMothershipEND")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIProtectMothershipPING")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIProtectMothershipEND", "Watch_Mission06_FleetIntel_FIProtectMothershipPING")
	Init_Mission06_FleetIntel_FIProtectMothershipEND(TeamName)
	return
	elseif (IntelEvent[TeamName] ~= 0) then
	
	--kasJump("FIProtectMothershipWAITEND")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIProtectMothershipPING")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIProtectMothershipWAITEND", "Watch_Mission06_FleetIntel_FIProtectMothershipPING")
	Init_Mission06_FleetIntel_FIProtectMothershipWAITEND(TeamName)
	return
	end
	if (KASTimer_IsExpiredIfSoDestroy(FIProtectMothershipPINGTimer[TeamName]) ~= 0) then
	
	ignoredFunction()    --kasfSoundEvent(267)
	ignoredFunction()    --kasfTutSetTextDisplayBoxToSubtitleRegion()
	PointerID_CollisionEnvelopePOINTER = KASPointer_AddVolume("CollisionEnvelope")    --kasfTutSetPointerTargetAIVolume("CollisionEnvelopePOINTER", kasVolumePtr("CollisionEnvelope"))
	end
	
end


--
--  "initialize" code for Mission06 FleetIntel FIProtectMothershipLBXOut state
--
function Init_Mission06_FleetIntel_FIProtectMothershipLBXOut(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	KASTimer_Start(FIProtectMothershipLBXOutTimer[TeamName], 1)
	
end


--
--  "watch" code for Mission06 FleetIntel FIProtectMothershipLBXOut state
--
function Watch_Mission06_FleetIntel_FIProtectMothershipLBXOut(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	if (KASTimer_IsExpiredIfSoDestroy(FIProtectMothershipLBXOutTimer[TeamName]) ~= 0) then
	
	--KAS_SetLetterboxState(0, 5)    --kasfWideScreenOut(150)
	--kasJump("FIProtectMothershipWAITEND")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIProtectMothershipLBXOut")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIProtectMothershipWAITEND", "Watch_Mission06_FleetIntel_FIProtectMothershipLBXOut")
	Init_Mission06_FleetIntel_FIProtectMothershipWAITEND(TeamName)
	return
	end
	if (Subtitle_IsDoneOrSkipped(Actor_FleetIntel) ~= 0) then     --kasfIntelEventEnded()
	
	--KAS_SetLetterboxState(0, 1)    --kasfWideScreenOut(30)
	--kasJump("FIProtectMothershipEND")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIProtectMothershipLBXOut")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIProtectMothershipEND", "Watch_Mission06_FleetIntel_FIProtectMothershipLBXOut")
	Init_Mission06_FleetIntel_FIProtectMothershipEND(TeamName)
	return
	end
	
end


--
--  "initialize" code for Mission06 FleetIntel FIProtectMothershipWAITEND state
--
function Init_Mission06_FleetIntel_FIProtectMothershipWAITEND(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	KASTimer_Start(FIProtectMothershipENDTimer[TeamName], 3)
	
end


--
--  "watch" code for Mission06 FleetIntel FIProtectMothershipWAITEND state
--
function Watch_Mission06_FleetIntel_FIProtectMothershipWAITEND(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	IntelEvent[TeamName] = 0 --destroyed
	IntelEvent[TeamName] = Subtitle_IsDoneOrSkipped(Actor_FleetIntel) --created,set    --kasfIntelEventEnded()
	if (IntelEvent[TeamName] == 2) then
	
	--KAS_SetLetterboxState(0, 1)    --kasfWideScreenOut(30)
	--kasJump("FIProtectMothershipEND")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIProtectMothershipWAITEND")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIProtectMothershipEND", "Watch_Mission06_FleetIntel_FIProtectMothershipWAITEND")
	Init_Mission06_FleetIntel_FIProtectMothershipEND(TeamName)
	return
	end
	if (KASTimer_IsExpiredIfSoDestroy(FIProtectMothershipENDTimer[TeamName]) ~= 0) then
	
	--KAS_SetLetterboxState(0, 1)    --kasfWideScreenOut(30)
	--kasJump("FIProtectMothershipEND")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIProtectMothershipWAITEND")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIProtectMothershipEND", "Watch_Mission06_FleetIntel_FIProtectMothershipWAITEND")
	Init_Mission06_FleetIntel_FIProtectMothershipEND(TeamName)
	return
	end
	
end


--
--  "initialize" code for Mission06 FleetIntel FIProtectMothershipEND state
--
function Init_Mission06_FleetIntel_FIProtectMothershipEND(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	KASPointer_RemoveAll()    --kasfTutRemoveAllPointers()
	KAS_UniversePause(0)    --kasfUniverseUnpause()
	KASRules_UnpauseOthers()    --kasfOtherKASUnpause()
	KAS_SensorsToggle(0, 1)    --kasfCloseSensors(1)
	G_CLICK_ProtectMothership = 0 --destroyed
	--kasJump("FIIdle")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIIdle", "Init_Mission06_FleetIntel_FIProtectMothershipEND")
	Init_Mission06_FleetIntel_FIIdle(TeamName)
	KAS_SetLetterboxState(0, 2)    --kasfWideScreenOut(30)
	return
	
end


--
--  "watch" code for Mission06 FleetIntel FIProtectMothershipEND state
--
function Watch_Mission06_FleetIntel_FIProtectMothershipEND(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	
end


--
--  "initialize" code for Mission06 FleetIntel FIResearchCapShipDrive state
--
function Init_Mission06_FleetIntel_FIResearchCapShipDrive(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60531", 3)    --kasfSpeechEvent((531 + 4096 + 268435456), 0)
	
end


--
--  "watch" code for Mission06 FleetIntel FIResearchCapShipDrive state
--
function Watch_Mission06_FleetIntel_FIResearchCapShipDrive(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	if (Subtitle_IsDoneOrSkipped(Actor_FleetIntel) ~= 0) then     --kasfIntelEventEnded()
	
	--kasJump("FIIdle")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIResearchCapShipDrive")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIIdle", "Watch_Mission06_FleetIntel_FIResearchCapShipDrive")
	Init_Mission06_FleetIntel_FIIdle(TeamName)
	return
	end
	
end


--
--  "initialize" code for Mission06 FleetIntel FIResearchIonCannons state
--
function Init_Mission06_FleetIntel_FIResearchIonCannons(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60763", 3)    --kasfSpeechEvent((763 + 4096 + 268435456), 0)
	
end


--
--  "watch" code for Mission06 FleetIntel FIResearchIonCannons state
--
function Watch_Mission06_FleetIntel_FIResearchIonCannons(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	if (Subtitle_IsDoneOrSkipped(Actor_FleetIntel) ~= 0) then     --kasfIntelEventEnded()
	
	--kasJump("FIIdle")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIResearchIonCannons")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIIdle", "Watch_Mission06_FleetIntel_FIResearchIonCannons")
	Init_Mission06_FleetIntel_FIIdle(TeamName)
	return
	end
	
end


--
--  "initialize" code for Mission06 FleetIntel FIClearedField state
--
function Init_Mission06_FleetIntel_FIClearedField(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60533", 3)    --kasfSpeechEvent((533 + 4096 + 268435456), 0)
	
end


--
--  "watch" code for Mission06 FleetIntel FIClearedField state
--
function Watch_Mission06_FleetIntel_FIClearedField(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	if (Subtitle_IsDoneOrSkipped(Actor_FleetIntel) ~= 0) then     --kasfIntelEventEnded()
	
	G_FISaidClearedField = 1 --created,set
	--kasJump("FIIdle")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIClearedField")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIIdle", "Watch_Mission06_FleetIntel_FIClearedField")
	Init_Mission06_FleetIntel_FIIdle(TeamName)
	return
	end
	
end


--
--  "initialize" code for Mission06 FleetIntel FIBentusiArriving state
--
function Init_Mission06_FleetIntel_FIBentusiArriving(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60765", 3)    --kasfSpeechEvent((765 + 4096 + 268435456), 0)
	KAS_MusicPlayType("data:sound/music/battle/NISlet01", MUS_Ambient)    --kasfMusicPlay(16)
	
end


--
--  "watch" code for Mission06 FleetIntel FIBentusiArriving state
--
function Watch_Mission06_FleetIntel_FIBentusiArriving(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	if (Subtitle_IsDoneOrSkipped(Actor_FleetIntel) ~= 0) then     --kasfIntelEventEnded()
	
	if (_VIFONCE001[TeamName] == 0 and (1 ~= 0)) then  -- "ifonce" #1
	
	_VIFONCE001[TeamName] = 1 --created,set;
	G_PlayTraderNISLet = 1 --created,set
	end
	--kasJump("FIIdle")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIBentusiArriving")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIIdle", "Watch_Mission06_FleetIntel_FIBentusiArriving")
	Init_Mission06_FleetIntel_FIIdle(TeamName)
	return
	end
	
end


--
--  "initialize" code for Mission06 FleetIntel TradersHello state
--
function Init_Mission06_FleetIntel_TradersHello(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	KAS_SubtitleAddOnce(Actor_HW1_BentusiTraders, "$60534", 3)    --kasfSpeechEvent((534 + 8192 + 268435456), 0)
	
end


--
--  "watch" code for Mission06 FleetIntel TradersHello state
--
function Watch_Mission06_FleetIntel_TradersHello(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	if (Subtitle_IsDoneOrSkipped(Actor_FleetIntel) ~= 0) then     --kasfIntelEventEnded()
	
	KASTimer_Start(TimerID_G_BringUpTraderGUI, 1)
	--kasJump("FIIdle")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_TradersHello")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIIdle", "Watch_Mission06_FleetIntel_TradersHello")
	Init_Mission06_FleetIntel_FIIdle(TeamName)
	return
	end
	
end


--
--  "initialize" code for Mission06 FleetIntel TradersBringUpGUI state
--
function Init_Mission06_FleetIntel_TradersBringUpGUI(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	ignoredFunction()    --kasfSoundEvent(267)
	KAS_EnableTradeGUI()    --kasfEnableTraderGUI()
	--kasJump("FIIdle")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIIdle", "Init_Mission06_FleetIntel_TradersBringUpGUI")
	Init_Mission06_FleetIntel_FIIdle(TeamName)
	return
	
end


--
--  "watch" code for Mission06 FleetIntel TradersBringUpGUI state
--
function Watch_Mission06_FleetIntel_TradersBringUpGUI(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	
end


--
--  "initialize" code for Mission06 FleetIntel TradersFirstWarning state
--
function Init_Mission06_FleetIntel_TradersFirstWarning(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	KAS_SubtitleAddOnce(Actor_HW1_BentusiTraders, "$60494", 3)    --kasfSpeechEvent((494 + 8192 + 268435456), 0)
	
end


--
--  "watch" code for Mission06 FleetIntel TradersFirstWarning state
--
function Watch_Mission06_FleetIntel_TradersFirstWarning(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	if (Subtitle_IsDoneOrSkipped(Actor_FleetIntel) ~= 0) then     --kasfIntelEventEnded()
	
	--kasJump("FICeaseFire")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_TradersFirstWarning")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FICeaseFire", "Watch_Mission06_FleetIntel_TradersFirstWarning")
	Init_Mission06_FleetIntel_FICeaseFire(TeamName)
	return
	end
	
end


--
--  "initialize" code for Mission06 FleetIntel FICeaseFire state
--
function Init_Mission06_FleetIntel_FICeaseFire(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60495", 3)    --kasfSpeechEvent((495 + 4096 + 268435456), 0)
	KASTimer_Start(TimerID_G_GivePlayerTimeToWithdrawAttack, 12)
	
end


--
--  "watch" code for Mission06 FleetIntel FICeaseFire state
--
function Watch_Mission06_FleetIntel_FICeaseFire(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	if ((G_PlayerHasAttackedTraders == 0) and (KASTimer_IsExpiredIfSoDestroy(TimerID_G_GivePlayerTimeToWithdrawAttack) ~= 0)) then
	
	--kasJump("FIIdle")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FICeaseFire")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIIdle", "Watch_Mission06_FleetIntel_FICeaseFire")
	Init_Mission06_FleetIntel_FIIdle(TeamName)
	return
	end
	if ((G_PlayerHasAttackedTraders == 1) and (KASTimer_IsExpiredIfSoDestroy(TimerID_G_GivePlayerTimeToWithdrawAttack) ~= 0)) then
	
	--kasJump("TradersTellPlayer")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FICeaseFire")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_TradersTellPlayer", "Watch_Mission06_FleetIntel_FICeaseFire")
	Init_Mission06_FleetIntel_TradersTellPlayer(TeamName)
	return
	end
	
end


--
--  "initialize" code for Mission06 FleetIntel TradersTellPlayer state
--
function Init_Mission06_FleetIntel_TradersTellPlayer(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	KAS_SubtitleAddOnce(Actor_HW1_BentusiTraders, "$60496", 3)    --kasfSpeechEvent((496 + 8192 + 268435456), 0)
	
end


--
--  "watch" code for Mission06 FleetIntel TradersTellPlayer state
--
function Watch_Mission06_FleetIntel_TradersTellPlayer(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	if (Subtitle_IsDoneOrSkipped(Actor_FleetIntel) ~= 0) then     --kasfIntelEventEnded()
	
	G_TradersObliteratePlayer = 1 --created,set
	end
	
end


--
--  "initialize" code for Mission06 FleetIntel FCGiveUsInfo state
--
function Init_Mission06_FleetIntel_FCGiveUsInfo(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	KAS_SubtitleAddOnce(Actor_HW1_FleetCommand, "$60535", 3)    --kasfSpeechEvent((535 + 2048 + 268435456), 0)
	
end


--
--  "watch" code for Mission06 FleetIntel FCGiveUsInfo state
--
function Watch_Mission06_FleetIntel_FCGiveUsInfo(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	if (Subtitle_IsDoneOrSkipped(Actor_FleetIntel) ~= 0) then     --kasfIntelEventEnded()
	
	G_GoToTradersNebulaIsBad = 1 --created,set
	--kasJump("FIIdle")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FCGiveUsInfo")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIIdle", "Watch_Mission06_FleetIntel_FCGiveUsInfo")
	Init_Mission06_FleetIntel_FIIdle(TeamName)
	return
	end
	
end


--
--  "initialize" code for Mission06 FleetIntel TradersNebulaIsBad state
--
function Init_Mission06_FleetIntel_TradersNebulaIsBad(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	if (ignoredFunction(0) == 0) then     --kasfRaceOfHuman()
	
	KAS_SubtitleAddOnce(Actor_HW1_BentusiTraders, "$60536", 3)    --kasfSpeechEvent((536 + 8192 + 268435456), 0)
	elseif (ignoredFunction(0) == 1) then     --kasfRaceOfHuman()
	
	KAS_SubtitleAddOnce(Actor_HW1_BentusiTraders, "$60537", 3)    --kasfSpeechEvent((537 + 8192 + 268435456), 0)
	end
	
end


--
--  "watch" code for Mission06 FleetIntel TradersNebulaIsBad state
--
function Watch_Mission06_FleetIntel_TradersNebulaIsBad(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	if (Subtitle_IsDoneOrSkipped(Actor_FleetIntel) ~= 0) then     --kasfIntelEventEnded()
	
	G_TradersAreDoneTalking = 1 --created,set
	--kasJump("FIIdle")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_TradersNebulaIsBad")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIIdle", "Watch_Mission06_FleetIntel_TradersNebulaIsBad")
	Init_Mission06_FleetIntel_FIIdle(TeamName)
	return
	end
	
end


--
--  "initialize" code for Mission06 FleetIntel FIModuleCharged state
--
function Init_Mission06_FleetIntel_FIModuleCharged(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	KAS_SubtitleAddOnce(Actor_HW1_FleetIntel, "$60538", 3)    --kasfSpeechEvent((538 + 4096 + 268435456), 0)
	
end


--
--  "watch" code for Mission06 FleetIntel FIModuleCharged state
--
function Watch_Mission06_FleetIntel_FIModuleCharged(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	if (Subtitle_IsDoneOrSkipped(Actor_FleetIntel) ~= 0) then     --kasfIntelEventEnded()
	
	G_ModuleIsCharged = 1 --created,set
	--kasJump("FIIdle")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIModuleCharged")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIIdle", "Watch_Mission06_FleetIntel_FIModuleCharged")
	Init_Mission06_FleetIntel_FIIdle(TeamName)
	return
	end
	
end


--
--  "initialize" code for Mission06 FleetIntel FIIdle state
--
function Init_Mission06_FleetIntel_FIIdle(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	
end


--
--  "watch" code for Mission06 FleetIntel FIIdle state
--
function Watch_Mission06_FleetIntel_FIIdle(TeamName)
	--FSM: FSM_Mission06_FleetIntel
	--TeamName = FleetIntel
	if (_VIFONCE002[TeamName] == 0 and (KASTimer_IsExpiredIfSoDestroy(TimerID_G_FCHyperspaceSuccessful) ~= 0)) then  -- "ifonce" #2
	
	_VIFONCE002[TeamName] = 1 --created,set;
	--kasJump("FCIntro")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIIdle")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FCIntro", "Watch_Mission06_FleetIntel_FIIdle")
	Init_Mission06_FleetIntel_FCIntro(TeamName)
	return
	end
	if (_VIFONCE003[TeamName] == 0 and (G_PlayIonTechEvent == 1)) then  -- "ifonce" #3
	
	_VIFONCE003[TeamName] = 1 --created,set;
	--kasJump("FIResearchIonCannons")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIIdle")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIResearchIonCannons", "Watch_Mission06_FleetIntel_FIIdle")
	Init_Mission06_FleetIntel_FIResearchIonCannons(TeamName)
	return
	end
	if (_VIFONCE004[TeamName] == 0 and (G_PlaySuperCapTechEvent == 1)) then  -- "ifonce" #4
	
	_VIFONCE004[TeamName] = 1 --created,set;
	--kasJump("FIResearchCapShipDrive")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIIdle")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIResearchCapShipDrive", "Watch_Mission06_FleetIntel_FIIdle")
	Init_Mission06_FleetIntel_FIResearchCapShipDrive(TeamName)
	return
	end
	if (_VIFONCE005[TeamName] == 0 and (KASTimer_IsExpiredIfSoDestroy(TimerID_G_PlayFIClearedField) ~= 0)) then  -- "ifonce" #5
	
	_VIFONCE005[TeamName] = 1 --created,set;
	--kasJump("FIClearedField")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIIdle")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIClearedField", "Watch_Mission06_FleetIntel_FIIdle")
	Init_Mission06_FleetIntel_FIClearedField(TeamName)
	return
	end
	if (_VIFONCE006[TeamName] == 0 and (KASTimer_IsExpiredIfSoDestroy(TimerID_G_PlayTraderArrival) ~= 0)) then  -- "ifonce" #6
	
	_VIFONCE006[TeamName] = 1 --created,set;
	--kasJump("FIBentusiArriving")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIIdle")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIBentusiArriving", "Watch_Mission06_FleetIntel_FIIdle")
	Init_Mission06_FleetIntel_FIBentusiArriving(TeamName)
	return
	end
	if (_VIFONCE007[TeamName] == 0 and (KASTimer_IsExpiredIfSoDestroy(TimerID_G_TradersAreInPlace) ~= 0)) then  -- "ifonce" #7
	
	_VIFONCE007[TeamName] = 1 --created,set;
	--kasJump("TradersHello")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIIdle")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_TradersHello", "Watch_Mission06_FleetIntel_FIIdle")
	Init_Mission06_FleetIntel_TradersHello(TeamName)
	return
	end
	if (_VIFONCE008[TeamName] == 0 and (KASTimer_IsExpiredIfSoDestroy(TimerID_G_BringUpTraderGUI) ~= 0)) then  -- "ifonce" #8
	
	_VIFONCE008[TeamName] = 1 --created,set;
	--kasJump("TradersBringUpGUI")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIIdle")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_TradersBringUpGUI", "Watch_Mission06_FleetIntel_FIIdle")
	Init_Mission06_FleetIntel_TradersBringUpGUI(TeamName)
	return
	end
	if (_VIFONCE009[TeamName] == 0 and ((KASTimer_IsExpiredIfSoDestroy(TimerID_G_PlayFCTalkToTraders) ~= 0) and (G_PlayerHasAttackedTraders == 0))) then  -- "ifonce" #9
	
	_VIFONCE009[TeamName] = 1 --created,set;
	--kasJump("FCGiveUsInfo")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIIdle")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FCGiveUsInfo", "Watch_Mission06_FleetIntel_FIIdle")
	Init_Mission06_FleetIntel_FCGiveUsInfo(TeamName)
	return
	end
	if (G_PlayerHasAttackedTraders == 1) then
	
	--kasJump("TradersFirstWarning")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIIdle")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_TradersFirstWarning", "Watch_Mission06_FleetIntel_FIIdle")
	Init_Mission06_FleetIntel_TradersFirstWarning(TeamName)
	return
	end
	if (_VIFONCE010[TeamName] == 0 and ((G_GoToTradersNebulaIsBad == 1) and (G_PlayerHasAttackedTraders == 0))) then  -- "ifonce" #10
	
	_VIFONCE010[TeamName] = 1 --created,set;
	--kasJump("TradersNebulaIsBad")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIIdle")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_TradersNebulaIsBad", "Watch_Mission06_FleetIntel_FIIdle")
	Init_Mission06_FleetIntel_TradersNebulaIsBad(TeamName)
	return
	end
	if (_VIFONCE011[TeamName] == 0 and (KASTimer_IsExpiredIfSoDestroy(TimerID_G_TradersHaveLeftTheBuilding) ~= 0)) then  -- "ifonce" #11
	
	_VIFONCE011[TeamName] = 1 --created,set;
	--kasJump("FIModuleCharged")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIIdle")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIModuleCharged", "Watch_Mission06_FleetIntel_FIIdle")
	Init_Mission06_FleetIntel_FIModuleCharged(TeamName)
	return
	end
	if (G_CLICK_ProtectMothership ~= 0) then
	
	--kasJump("FIProtectMothershipLBXIn")
	--KASRule_Remove("FSM_Mission06_FleetIntel", "Watch_Mission06_FleetIntel_FIIdle")
	KASRule_Add(TeamName, "Watch_Mission06_FleetIntel_FIProtectMothershipLBXIn", "Watch_Mission06_FleetIntel_FIIdle")
	Init_Mission06_FleetIntel_FIProtectMothershipLBXIn(TeamName)
	return
	end
	
end


--
--  "initialize" code for Mission06 Traders FSM
--
function Init_Mission06_Traders(TeamName)
	--FSM: FSM_Mission06_Traders
	--TeamName = Traders
	KAS_SetTraderDisabled(0)    --kasfSetTraderDisabled(0)
	KAS_TeamAttributesSet(TeamName, 256)    --kasfTeamAttributesSet(256)
	--kasJump("Trading")
	KASRule_Add(TeamName, "Watch_Mission06_Traders_Trading", "Init_Mission06_Traders")
	Init_Mission06_Traders_Trading(TeamName)
	return
	
end


--
--  "watch" code for Mission06 Traders FSM
--
function Watch_Mission06_Traders(TeamName)
	--FSM: FSM_Mission06_Traders
	--TeamName = Traders
	if (KAS_TeamHealth(TeamName) < 95) then     --kasfTeamHealthAverage()
	
	SobGroup_SetHealth(TeamName, 100 / 100)    --kasfTeamSetPercentDamaged(100)
	end
	
end


--
--  "initialize" code for Mission06 Traders Trading state
--
function Init_Mission06_Traders_Trading(TeamName)
	--FSM: FSM_Mission06_Traders
	--TeamName = Traders
	KAS_SetTradeCost("DroneTechnology", 1100)    --kasfSetBaseTechnologyCost("DDDFDFGFTech", 500)
	KAS_AllowToPurchase("DroneTechnology")    --kasfAllowPlayerToPurchase("DDDFDFGFTech")
	KAS_SetTradeString(0, "$61303")    --kasfSetTraderDialog(0, LSTRING_TraderIntro[strCurLanguage])
	KAS_SetTradeString(1, "$61303")    --kasfSetTraderDialog(1, LSTRING_TraderIntro[strCurLanguage])
	KAS_SetTradeString(2, "$61303")    --kasfSetTraderDialog(2, LSTRING_TraderIntro[strCurLanguage])
	KAS_SetTradeString(3, "$61303")    --kasfSetTraderDialog(3, LSTRING_TraderIntro[strCurLanguage])
	KAS_SetTradeString(4, "$61304")    --kasfSetTraderDialog(4, LSTRING_TraderPurchaseMade[strCurLanguage])
	KAS_SetTradeString(5, "$61304")    --kasfSetTraderDialog(5, LSTRING_TraderPurchaseMade[strCurLanguage])
	--kasJump("Watching")
	KASRule_Add(TeamName, "Watch_Mission06_Traders_Watching", "Init_Mission06_Traders_Trading")
	Init_Mission06_Traders_Watching(TeamName)
	return
	
end


--
--  "watch" code for Mission06 Traders Trading state
--
function Watch_Mission06_Traders_Trading(TeamName)
	--FSM: FSM_Mission06_Traders
	--TeamName = Traders
	
end


--
--  "initialize" code for Mission06 Traders Watching state
--
function Init_Mission06_Traders_Watching(TeamName)
	--FSM: FSM_Mission06_Traders
	--TeamName = Traders
	
end


--
--  "watch" code for Mission06 Traders Watching state
--
function Watch_Mission06_Traders_Watching(TeamName)
	--FSM: FSM_Mission06_Traders
	--TeamName = Traders
	if (G_TradersAreDoneTalking == 1) then
	
	--kasJump("HyperspaceOut")
	--KASRule_Remove("FSM_Mission06_Traders", "Watch_Mission06_Traders_Watching")
	KASRule_Add(TeamName, "Watch_Mission06_Traders_HyperspaceOut", "Watch_Mission06_Traders_Watching")
	Init_Mission06_Traders_HyperspaceOut(TeamName)
	return
	end
	if (KAS_UnderAttack(TeamName, "GrowSelection_Null87238923") ~= 0) then     --kasfUnderAttack(kasGrowSelectionPtr("Null87238923"))
	
	G_PlayerHasAttackedTraders = 1 --created,set
	--kasJump("UnderAttackWatch")
	--KASRule_Remove("FSM_Mission06_Traders", "Watch_Mission06_Traders_Watching")
	KASRule_Add(TeamName, "Watch_Mission06_Traders_UnderAttackWatch", "Watch_Mission06_Traders_Watching")
	Init_Mission06_Traders_UnderAttackWatch(TeamName)
	return
	end
	
end


--
--  "initialize" code for Mission06 Traders UnderAttackWatch state
--
function Init_Mission06_Traders_UnderAttackWatch(TeamName)
	--FSM: FSM_Mission06_Traders
	--TeamName = Traders
	
end


--
--  "watch" code for Mission06 Traders UnderAttackWatch state
--
function Watch_Mission06_Traders_UnderAttackWatch(TeamName)
	--FSM: FSM_Mission06_Traders
	--TeamName = Traders
	if (G_TradersObliteratePlayer == 1) then
	
	--kasJump("TradersObliteratePlayer")
	--KASRule_Remove("FSM_Mission06_Traders", "Watch_Mission06_Traders_UnderAttackWatch")
	KASRule_Add(TeamName, "Watch_Mission06_Traders_TradersObliteratePlayer", "Watch_Mission06_Traders_UnderAttackWatch")
	Init_Mission06_Traders_TradersObliteratePlayer(TeamName)
	return
	end
	if (KAS_UnderAttack(TeamName, "GrowSelection_Null8723487238") == 0) then     --kasfUnderAttack(kasGrowSelectionPtr("Null8723487238"))
	
	G_PlayerHasAttackedTraders = 0 --destroyed
	--kasJump("Watching")
	--KASRule_Remove("FSM_Mission06_Traders", "Watch_Mission06_Traders_UnderAttackWatch")
	KASRule_Add(TeamName, "Watch_Mission06_Traders_Watching", "Watch_Mission06_Traders_UnderAttackWatch")
	Init_Mission06_Traders_Watching(TeamName)
	return
	end
	
end


--
--  "initialize" code for Mission06 Traders TradersObliteratePlayer state
--
function Init_Mission06_Traders_TradersObliteratePlayer(TeamName)
	--FSM: FSM_Mission06_Traders
	--TeamName = Traders
	KAS_FindEnemiesInside("MothershipSphere", "GrowSelection_PlayerFleet")    --kasfFindEnemiesInside(kasVolumePtr("MothershipSphere"), kasGrowSelectionPtr("PlayerFleet"), 1000)
	if (KAS_FillShipsByClass_Normal("GrowSelection_TraderTargets", "GrowSelection_PlayerFleet", "SmallCapitalShip") ~= 0) then     --kasfShipsSelectClass(kasGrowSelectionPtr("TraderTargets"), kasGrowSelectionPtr("PlayerFleet"), "CLASS_Destroyer")
	
	elseif (KAS_FillShipsByClass_Normal("GrowSelection_TraderTargets", "GrowSelection_PlayerFleet", "Frigate") ~= 0) then     --kasfShipsSelectClass(kasGrowSelectionPtr("TraderTargets"), kasGrowSelectionPtr("PlayerFleet"), "CLASS_Frigate")
	
	elseif (KAS_FillShipsByClass_Normal("GrowSelection_TraderTargets", "GrowSelection_PlayerFleet", "Mothership") ~= 0) then     --kasfShipsSelectClass(kasGrowSelectionPtr("TraderTargets"), kasGrowSelectionPtr("PlayerFleet"), "CLASS_Mothership")
	
	else
	
	KAS_ShipsAdd("GrowSelection_TraderTargets", "GrowSelection_PlayerFleet")    --kasfShipsAdd(kasGrowSelectionPtr("TraderTargets"), kasGrowSelectionPtr("PlayerFleet"))
	end
	if (SobGroup_Count("GrowSelection_TraderTargets") > 0) then     --kasfShipsCount(kasGrowSelectionPtr("TraderTargets"))
	
	KAS_Attack(TeamName, "GrowSelection_TraderTargets")    --kasfAttack(kasGrowSelectionPtr("TraderTargets"))
	end
	
end


--
--  "watch" code for Mission06 Traders TradersObliteratePlayer state
--
function Watch_Mission06_Traders_TradersObliteratePlayer(TeamName)
	--FSM: FSM_Mission06_Traders
	--TeamName = Traders
	if ((SobGroup_Count("GrowSelection_TraderTargets") == 0) or (KAS_GetCurrentOrder("Traders") ~= 2)) then     --kasfShipsCount(kasGrowSelectionPtr("TraderTargets"))    --kasfShipsOrder(kasAITeamShipsPtr("Traders"))
	
	--kasJump("TradersObliteratePlayer")
	--KASRule_Remove("FSM_Mission06_Traders", "Watch_Mission06_Traders_TradersObliteratePlayer")
	KASRule_Add(TeamName, "Watch_Mission06_Traders_TradersObliteratePlayer", "Watch_Mission06_Traders_TradersObliteratePlayer")
	Init_Mission06_Traders_TradersObliteratePlayer(TeamName)
	return
	end
	
end


--
--  "initialize" code for Mission06 Traders HyperspaceOut state
--
function Init_Mission06_Traders_HyperspaceOut(TeamName)
	--FSM: FSM_Mission06_Traders
	--TeamName = Traders
	KASTimer_Start(TimerID_G_TradersHaveLeftTheBuilding, 15)
	KAS_TeamHyperspaceOut(TeamName)    --kasfTeamHyperspaceOut()
	KAS_MusicStop(4)    --kasfMusicStop(4)
	--kasJump("NullState")
	KASRule_Add(TeamName, "Watch_Mission06_Traders_NullState", "Init_Mission06_Traders_HyperspaceOut")
	Init_Mission06_Traders_NullState(TeamName)
	return
	
end


--
--  "watch" code for Mission06 Traders HyperspaceOut state
--
function Watch_Mission06_Traders_HyperspaceOut(TeamName)
	--FSM: FSM_Mission06_Traders
	--TeamName = Traders
	
end


--
--  "initialize" code for Mission06 Traders NullState state
--
function Init_Mission06_Traders_NullState(TeamName)
	--FSM: FSM_Mission06_Traders
	--TeamName = Traders
	
end


--
--  "watch" code for Mission06 Traders NullState state
--
function Watch_Mission06_Traders_NullState(TeamName)
	--FSM: FSM_Mission06_Traders
	--TeamName = Traders
	
end


--
--  "initialize" code for Mission06 mission
--
function Init_Mission06(MissionName)
	--FSM: FSM_Mission06
	--MissionName = "Mission06"
	--kasFSMCreate("FleetIntel")
	KASRule_AddFSM("FleetIntel", "Watch_Mission06_FleetIntel", "Init_Mission06")
	Init_Mission06_FleetIntel("FleetIntel")
	KASTimer_Start(TimerID_G_AsteroidTimer, 840)
	KASTimer_Start(TimerID_G_GiveTechnology, RandomIntRange(35, 55))    --kasfRandom(35, 55)
	KAS_CampaignAutoSave(6, "$61300")    --kasfSaveLevel(6, LSTRING_Savegame[strCurLanguage])
	
end


--
--  "watch" code for Mission06 mission
--
function Watch_Mission06(MissionName)
	--FSM: FSM_Mission06
	--MissionName = "Mission06"
	if (_VIFONCE012 == 0 and (1 ~= 0)) then  -- "ifonce" #12
	
	_VIFONCE012 = 1 --created,set;
	KASTimer_Start(TimerID_LocationCardTimer, 1)
	end
	if (KASTimer_IsExpiredIfSoDestroy(TimerID_LocationCardTimer) ~= 0) then
	
	singlePlayerLocationCard("$61301", 5)    --kasfLocationCard(5000, LSTRING_LocationCard[strCurLanguage])
	end
	if (_VIFONCE013 == 0 and (G_Nislet60Complete ~= 0)) then  -- "ifonce" #13
	
	_VIFONCE013 = 1 --created,set;
	KAS_SetLetterboxState(0, 2)    --kasfWideScreenOut(60)
	--kasFSMCreate("Traders")
	KASRule_AddFSM("Traders", "Watch_Mission06_Traders", "Watch_Mission06")
	Init_Mission06_Traders("Traders")
	KASTimer_Start(TimerID_G_TradersAreInPlace, 5)
	KASTimer_Start(TimerID_G_TradersWaitingToTrade, 90)
	end
	if (_VIFONCE014 == 0 and (1 ~= 0)) then  -- "ifonce" #14
	
	_VIFONCE014 = 1 --created,set;
	KASTimer_Start(TimerID_G_FCHyperspaceSuccessful, 5)
	end
	if (_VIFONCE015 == 0 and ((KAS_PlayerHasResearch(0, "DroneTechnology") ~= 0) or (KASTimer_IsExpiredIfSoDestroy(TimerID_G_TradersWaitingToTrade) ~= 0))) then  -- "ifonce" #15    --kasfDoesPlayerHave("DDDFDFGFTech")
	
	_VIFONCE015 = 1 --created,set;
	G_TradersAreDone = 1 --created,set
	KASTimer_Start(TimerID_G_PlayFCTalkToTraders, 5)
	end
	if (_VIFONCE016 == 0 and (G_PlayerHasClearedField ~= 0)) then  -- "ifonce" #16
	
	_VIFONCE016 = 1 --created,set;
	KASTimer_Start(TimerID_G_PlayFIClearedField, 5)
	end
	if (_VIFONCE017 == 0 and (G_ProtectMothershipHasPlayed == 1)) then  -- "ifonce" #17
	
	_VIFONCE017 = 1 --created,set;
	KASObjective_Add(ObjectiveID_ProtectMothership, "$61302", OT_Primary)    --kasfObjectiveCreate("ProtectMothership", LSTRING_FIProtectTASKBAR[strCurLanguage], LSTRING_FIProtectTASKBAR[strCurLanguage])
	Objective_SetDescription(ObjectiveID_ProtectMothership, "$60824")
	end
	if (KASTimer_IsExpiredIfSoDestroy(TimerID_G_AsteroidTimer) ~= 0) then
	
	G_PlayerHasClearedField = 1 --created,set
	end
	if (_VIFONCE018 == 0 and (G_FISaidClearedField == 1)) then  -- "ifonce" #18
	
	_VIFONCE018 = 1 --created,set;
	KASObjective_SetState(ObjectiveID_ProtectMothership, 1)    --kasfObjectiveSet("ProtectMothership", 1)
	end
	if (_VIFONCE019 == 0 and (G_ModuleIsCharged == 1)) then  -- "ifonce" #19
	
	_VIFONCE019 = 1 --created,set;
	KASObjective_Add(ObjectiveID_Hyperspace, "Hyperspace", OT_Primary)    --kasfObjectiveCreate("Hyperspace", LSTRING_Hyperspace[strCurLanguage], LSTRING_Hyperspace[strCurLanguage])
	Objective_SetDescription(ObjectiveID_Hyperspace, "hyperspace")
	end
	if (_VIFONCE020 == 0 and (G_PlayerHasClearedField == 1)) then  -- "ifonce" #20
	
	_VIFONCE020 = 1 --created,set;
	KASTimer_Start(TimerID_G_PlayTraderArrival, 15)
	end
	if (_VIFONCE021 == 0 and (G_PlayTraderNISLet == 1)) then  -- "ifonce" #21
	
	_VIFONCE021 = 1 --created,set;
	KASTimer_Start(TimerID_WideScreenInBeforeNISLet, 4)
	KAS_SetLetterboxState(2, 3)    --kasfWideScreenIn(90)
	end
	if (_VIFONCE022 == 0 and (KASTimer_IsExpiredIfSoDestroy(TimerID_WideScreenInBeforeNISLet) ~= 0)) then  -- "ifonce" #22
	
	_VIFONCE022 = 1 --created,set;
	KAS_FindEnemiesInside("MothershipSphere", "GrowSelection_EntireFleet")    --kasfFindEnemiesInside(kasVolumePtr("MothershipSphere"), kasGrowSelectionPtr("EntireFleet"), 100)
	KAS_FillShipsByClass_Normal("GrowSelection_PlayerMothership", "GrowSelection_EntireFleet", "Mothership")    --kasfShipsSelectClass(kasGrowSelectionPtr("PlayerMothership"), kasGrowSelectionPtr("EntireFleet"), "CLASS_Mothership")
	KAS_ShipsAdd("GrowSelection_NisCentreShip", "GrowSelection_PlayerMothership")    --kasfShipsAdd(kasGrowSelectionPtr("NisCentreShip"), kasGrowSelectionPtr("PlayerMothership"))
	G_PlayNislet = 60 --created,set
	G_NowPlayingNISLet = 1 --created,set
	end
	if (G_TechEventHasPlayed == 0) then
	
	if (_VIFONCE023 == 0 and ((KASTimer_IsExpired(TimerID_G_GiveTechnology) ~= 0) and (KAS_PlayerHasResearch(0, "IonCannons") ~= 0))) then  -- "ifonce" #23    --kasfDoesPlayerHave("IonWeapons")
	
	_VIFONCE023 = 1 --created,set;
	KAS_UnrestrictResearchOption(0, "SuperCapitalShipDrive")    --kasfAllowPlayerToResearch("MassDrive1Mt")
	G_PlaySuperCapTechEvent = 1 --created,set
	G_TechEventHasPlayed = 1 --created,set
	end
	end
	if (G_TechEventHasPlayed == 0) then
	
	if (_VIFONCE024 == 0 and ((KASTimer_IsExpired(TimerID_G_GiveTechnology) ~= 0) and (Player_CanResearch(0, "IonCannons") ~= 0))) then  -- "ifonce" #24    --kasfCanPlayerResearch("IonWeapons")
	
	_VIFONCE024 = 1 --created,set;
	KAS_UnrestrictResearchOption(0, "SuperCapitalShipDrive")    --kasfAllowPlayerToResearch("MassDrive1Mt")
	G_PlaySuperCapTechEvent = 1 --created,set
	G_TechEventHasPlayed = 1 --created,set
	end
	end
	if (G_TechEventHasPlayed == 0) then
	
	if (_VIFONCE025 == 0 and ((KASTimer_IsExpired(TimerID_G_GiveTechnology) ~= 0) and (KAS_PlayerHasResearch(0, "PlasmaBombLauncher") ~= 0) and ( (KAS_PlayerHasResearch(0, "IonCannons"))== 0) and ( (Player_CanResearch(0, "IonCannons"))== 0))) then  -- "ifonce" #25    --kasfCanPlayerResearch("IonWeapons")    --kasfDoesPlayerHave("IonWeapons")    --kasfDoesPlayerHave("PlasmaWeapons")
	
	_VIFONCE025 = 1 --created,set;
	KAS_UnrestrictResearchOption(0, "IonCannons")    --kasfAllowPlayerToResearch("IonWeapons")
	G_PlayIonTechEvent = 1 --created,set
	G_TechEventHasPlayed = 1 --created,set
	end
	end
	if (G_TechEventHasPlayed == 0) then
	
	if (_VIFONCE026 == 0 and ((KASTimer_IsExpired(TimerID_G_GiveTechnology) ~= 0) and (Player_CanResearch(0, "PlasmaBombLauncher") ~= 0) and ( (KAS_PlayerHasResearch(0, "IonCannons"))== 0) and ( (Player_CanResearch(0, "IonCannons"))== 0))) then  -- "ifonce" #26    --kasfCanPlayerResearch("IonWeapons")    --kasfCanPlayerResearch("PlasmaWeapons")    --kasfDoesPlayerHave("IonWeapons")
	
	_VIFONCE026 = 1 --created,set;
	KAS_UnrestrictResearchOption(0, "IonCannons")    --kasfAllowPlayerToResearch("IonWeapons")
	G_PlayIonTechEvent = 1 --created,set
	G_TechEventHasPlayed = 1 --created,set
	end
	end
	if (_VIFONCE027 == 0 and (KAS_PlayerHasResearch(0, "CorvetteDrive") ~= 0)) then  -- "ifonce" #27    --kasfDoesPlayerHave("MassDrive10Kt")
	
	_VIFONCE027 = 1 --created,set;
	KAS_UnrestrictResearchOption(0, "CorvetteChassis")    --kasfAllowPlayerToResearch("Chassis2")
	end
	if ((KAS_PlayerHasResearch(0, "CorvetteChassis") ~= 0) and (SetMediumGuns == 0)) then     --kasfDoesPlayerHave("Chassis2")
	
	KAS_UnrestrictResearchOption(0, "HeavyCorvetteUpgrade")    --kasfAllowPlayerToResearch("MediumGuns")
	SetMediumGuns = 1 --created,set
	end
	if (_VIFONCE028 == 0 and (KAS_PlayerHasResearch(0, "FighterChassis") ~= 0)) then  -- "ifonce" #28    --kasfDoesPlayerHave("Chassis1")
	
	_VIFONCE028 = 1 --created,set;
	KAS_UnrestrictResearchOption(0, "CorvetteDrive")    --kasfAllowPlayerToResearch("MassDrive10Kt")
	end
	
end

function OnStartOrLoad()
    print("OnStartOrLoad issued")

    --Mission-global GrowSelections/SobGroups
    KASSobGroup_Create("GrowSelection_EntireFleet")
    KASSobGroup_Create("GrowSelection_NisCentreShip")
    KASSobGroup_Create("GrowSelection_Null8723487238")
    KASSobGroup_Create("GrowSelection_Null87238923")
    KASSobGroup_Create("GrowSelection_PlayerFleet")
    KASSobGroup_Create("GrowSelection_PlayerMothership")
    KASSobGroup_Create("GrowSelection_TraderTargets")
    KASSobGroup_CreateIfNotExist("FleetIntel")
    KASSobGroup_CreateIfNotExist("Traders")

    Sound_SpeechSubtitlePath("speech:missions/Mission06/")
    Scar_TracesEnable("SGAction, SGQuery, Camera, ATI, Player")

    LCWatcher_SpecifyLocalFilter(LC_Scar, "_VIFONCE;FleetIntel;Traders;")
    KAS_SetColourSchemeColours(1, {1,0.823529411764706,0}, {1, 0, 0}, "DATA:Badges/Turanic.tga", {0.921,0.75,0.419}, "data:/effect/trails/tur_trail_clr.tga")
    Player_SetTeamColourTheme(1, {1,0.823529411764706,0}, {1, 0, 0}, "DATA:Badges/Turanic.tga", {0.921,0.75,0.419}, "data:/effect/trails/tur_trail_clr.tga")
    Player_SetTeamColourTheme(3, {1,0.823529411764706,0}, {1, 0, 0}, "DATA:Badges/Turanic.tga", {0.921,0.75,0.419}, "data:/effect/trails/tur_trail_clr.tga")
    Player_SetPlayerName(2, "$60539")

    singlePlayerOnStartOrLoad(06)
end

function OnInit()
    print("OnInit issued")

    Player_RestrictAllResearch(0, 1)
    SobGroup_LoadPersistantData("Kus_Mothership")
    Camera_Interpolate('here', 'Camera_Startpos', 0)
    KAS_RememberStartingRUs()
    singlePlayerStartGame(06)
    KAS_CPUPlayerInit()

    KASRule_Add("Mission06", "Watch_Mission06", "OnInit")
    Init_Mission06("Mission06")
    KAS_SetLetterboxStart(1, 5, 1, 0)
    singlePlayerPauseUntilHyperspaceComplete("OnInit_Finish()")
	HW2_ReactiveInfo() --Added for info in log file
end

function OnInit_Finish()
    print("OnInit_Finish issued")

    KAS_MusicPlayType( "data:sound/music/ambient/A05_mission6and12", MUS_Ambient )
end

