Number_Properties_Priority = 3.0

Number_Properties = {
	dm_challenge_research_baseline = 5,
}

String_Properties_Priority = 3.0

String_Properties = {

	dm_fightersonly_build_restrict = "Hgn_MS_Production_Corvette,Hgn_C_Production_Corvette,Hgn_MS_Production_Frigate,Hgn_C_Production_Frigate,Hgn_MS_Production_CapShip,Hgn_SY_Production_CapShip",
	dm_fightersonly_research_restrict = "",
	dm_fightersandvettesonly_build_restrict = "Hgn_MS_Production_Frigate,Hgn_C_Production_Frigate,Hgn_MS_Production_CapShip,Hgn_SY_Production_CapShip",
	dm_fightersandvettesonly_research_restrict = "",
	dm_vettesonly_build_restrict = "Hgn_MS_Production_Fighter,Hgn_C_Production_Fighter,Hgn_MS_Production_Frigate,Hgn_C_Production_Frigate,Hgn_MS_Production_CapShip,Hgn_SY_Production_CapShip",
	dm_vettesonly_research_restrict = "",
	dm_frigatesonly_build_restrict = "HGN_SCOUT,Hgn_MS_Production_Fighter,Hgn_C_Production_Fighter,Hgn_MS_Production_Corvette,Hgn_C_Production_Corvette,Hgn_MS_Production_CapShip,Hgn_SY_Production_CapShip",
	dm_frigatesonly_research_restrict = "",
	dm_destroyersonly_build_restrict = "HGN_SCOUT,Hgn_MS_Production_Fighter,Hgn_C_Production_Fighter,Hgn_MS_Production_Corvette,Hgn_C_Production_Corvette,Hgn_MS_Production_Frigate,Hgn_C_Production_Frigate,Hgn_Carrier",
	dm_destroyersonly_research_restrict = "",
	dm_disablebuilding_build_restrict = "HGN_SCOUT,Hgn_MS_Production_Fighter,Hgn_C_Production_Fighter,Hgn_MS_Production_Corvette,Hgn_C_Production_Corvette,Hgn_MS_Production_Frigate,Hgn_C_Production_Frigate,Hgn_MS_Production_CapShip,Hgn_SY_Production_CapShip,Hgn_C_Module_Hyperspace,Hgn_MS_Module_Hyperspace",
	dm_disablebuilding__research_restrict = "", 
	dm_strikecraftgamemode_build_restrict = "Hgn_Torpedofrigate,Hgn_Ioncannonfrigate,Hgn_AssaultFrigate,Hgn_Destroyer,Hgn_Battlecruiser",
	dm_strikecraftgamemode_research_restrict = "DestroyerTech,BattlecruiserIonWeapons,ImprovedTorpedo,TorpedoFrigateMAXSPEEDUpgrade1,TorpedoFrigateHealthUpgrade1,IonCannonFrigateHealthUpgrade1,IonCannonFrigateMAXSPEEDUpgrade1,AssaultFrigateHealthUpgrade1,AssaultFrigateMAXSPEEDUpgrade1,BattlecruiserHealthUpgrade1,BattlecruiserMAXSPEEDUpgrade1,CarrierHealthUpgrade1,MothershipHealthUpgrade1,ShipyardHealthUpgrade1",
	dm_strikecraftgamemode_grant = "SGMCapitalHealth,SGMCarrierHealth,SGMFrigateHealth,SGMShipyardHealth",
}
