aitrace("LOADING HIIGARAN UPGRADE INFO")
rt_mothership = {
	health = {
		MOTHERSHIPHEALTHUPGRADE1,
--		MOTHERSHIPHEALTHUPGRADE2,
	},
	speed = {
		MOTHERSHIPMAXSPEEDUPGRADE1,
--		MOTHERSHIPMAXSPEEDUPGRADE2,
	}
}
rt_carrier = {
	health = {
		CARRIERHEALTHUPGRADE1,
--		CARRIERHEALTHUPGRADE2,
	},
	speed = {
		CARRIERMAXSPEEDUPGRADE1,
--		CARRIERMAXSPEEDUPGRADE2,
	},
}
rt_fighter = {
	interceptor = {
		INTERCEPTORMAXSPEEDUPGRADE1,
--		INTERCEPTORMAXSPEEDUPGRADE2,
	},
	bomber = {
		health = {
			ATTACKBOMBERHEALTHUPGRADE1,
--			ATTACKBOMBERHEALTHUPGRADE2,
		},
		speed = {
			ATTACKBOMBERMAXSPEEDUPGRADE1,
--			ATTACKBOMBERMAXSPEEDUPGRADE2,
		},
	},
}
rt_corvette = {
	assault = {
		health = {
			ASSAULTCORVETTEHEALTHUPGRADE1,
--			ASSAULTCORVETTEHEALTHUPGRADE2,
		},
		speed = {
			ASSAULTCORVETTEMAXSPEEDUPGRADE1,
--			ASSAULTCORVETTEMAXSPEEDUPGRADE2,
		},
	},
	pulsar = {
		health = {
			PULSARCORVETTEHEALTHUPGRADE1,
--			PULSARCORVETTEHEALTHUPGRADE2,
		},
		speed = {
			PULSARCORVETTEMAXSPEEDUPGRADE1,
--			PULSARCORVETTEMAXSPEEDUPGRADE2,
		},
	},
}
rt_frigate = {
	torpedo = {
		health = {
			TORPEDOFRIGATEHEALTHUPGRADE1,
--			TORPEDOFRIGATEHEALTHUPGRADE2,
		},
		speed = {
			TORPEDOFRIGATEMAXSPEEDUPGRADE1,
--			TORPEDOFRIGATEMAXSPEEDUPGRADE2,
		},
	},
	ioncannon = {
		health = {
			IONCANNONFRIGATEHEALTHUPGRADE1,
--			IONCANNONFRIGATEHEALTHUPGRADE2,
		},
		speed = {
			IONCANNONFRIGATEMAXSPEEDUPGRADE1,
--			IONCANNONFRIGATEMAXSPEEDUPGRADE2,
		},
	},
	assault = {
		health = {
			ASSAULTFRIGATEHEALTHUPGRADE1,
--			ASSAULTFRIGATEHEALTHUPGRADE2,
		},
		speed = {
			ASSAULTFRIGATEMAXSPEEDUPGRADE1,
--			ASSAULTFRIGATEMAXSPEEDUPGRADE2,
		},
	},
}
rt_battlecruiser = {
	health = {
		BATTLECRUISERHEALTHUPGRADE1,
--		BATTLECRUISERHEALTHUPGRADE2,
	},
	speed = {
		BATTLECRUISERMAXSPEEDUPGRADE1,
--		BATTLECRUISERMAXSPEEDUPGRADE2,
	},
}
rt_destroyer = {
	DESTROYERHEALTHUPGRADE1,
	DESTROYERMAXSPEEDUPGRADE1,
--	DESTROYERHEALTHUPGRADE2,
--	DESTROYERMAXSPEEDUPGRADE2	,
}
rt_shipyard = {
	health = {
		SHIPYARDHEALTHUPGRADE1,
--		SHIPYARDHEALTHUPGRADE2,
	},
	speed = {
		SHIPYARDMAXSPEEDUPGRADE1,
--		SHIPYARDMAXSPEEDUPGRADE2,
	},
}
rt_platform = {
	gunturret = {
		GUNTURRETHEALTHUPGRADE1,
--		GUNTURRETHEALTHUPGRADE2,
	},
	ionturret = {
		IONTURRETHEALTHUPGRADE1,
--		IONTURRETHEALTHUPGRADE2,
	},
}
rt_collector = {
	RESOURCECOLLECTORHEALTHUPGRADE1,
--	RESOURCECOLLECTORHEALTHUPGRADE2,
}
rt_refinery = {
	RESOURCECONTROLLERHEALTHUPGRADE1,
--	RESOURCECONTROLLERHEALTHUPGRADE2,
}
rt_hyperspace = {
	cost = {
		HYPERSPACECOSTUPGRADE1,
		HYPERSPACECOSTUPGRADE2,
	},

}



