Number_Properties_Priority = 2.0

Number_Properties = {
	dm_challenge_research_baseline = 4,
}

String_Properties_Priority = 2.0

String_Properties = {
	dm_carriersonly_build_restrict = "vgr_shipyard",
	dm_carriersonly_research_restrict = "MothershipBUILDSPEEDUpgrade1",
	dm_carriersonly_research_grant = "SuperCapHealthUpgrade1,SuperCapSpeedUpgrade1,CarrierBUILDSPEEDUpgrade1",
	dm_nocruisers_build_restrict = "vgr_battlecruiser",
	dm_nocruisers_research_restrict = "BattlecruiserIonWeapons",
	dm_noplatforms_build_restrict = "Vgr_C_Module_PlatformControl,Vgr_MS_Module_PlatformControl",
	dm_noplatforms_research_restrict = "PlatformHeavyMissiles",
	generic_mp_ability_research_grant = "RepairAbility,BomberImprovedBombs",
	generic_mp_health_misc_research_grant = "UtilityHealthUpgrade1,PlatformHealthUpgrade1",
	generic_mp_speed_fighters_research_grant = "FighterspeedUpgrade1",
	generic_mp_speed_corvettes_research_grant = "CorvetteSpeedUpgrade1",
	generic_mp_speed_frigates_research_grant = "FrigateSpeedUpgrade1,InfiltratorSpeedUpgrade1",
	generic_mp_speed_capitals_research_grant = "SuperCapSpeedUpgrade1",
	generic_mp_health_fighters_research_grant = "",
	generic_mp_health_corvettes_research_grant = "CorvetteHealthUpgrade1",
	generic_mp_health_frigates_research_grant = "FrigateHealthUpgrade1",
	generic_mp_health_capitals_research_grant = "SuperCapHealthUpgrade1",
	generic_mp_buildspeed_research_grant = "MothershipBUILDSPEEDUpgrade1,CarrierBUILDSPEEDUpgrade1,ShipyardBUILDSPEEDUpgrade1",
	generic_mp_build_restrict = "Vgr_PlanetKillerMissile",
	generic_mp_research_restrict = "WeakVgrHeavyMissiles,HyperspaceRecoveryTimeUpgradeSPGAME,HyperspaceTransitionTimeUpgradeSPGAME,VaygrCarrierHealthRegenDowngrade,ShipyardSpeedDowngradeSPGAME,SuperCapHealthUpgradeSPGAME,SuperCapDamageAppliedSPGAME,VaygrFrigateHealthUpgradeSPGAME,VaygrFrigateHealthRegenDowngradeSPGAME,CorvetteHealthUpgradeSPGAME,ExtraStrongVgrHeavyMissilesSPGAME,VaygrCaptureHack,VaygrReduceCaptureHack,VaygrRadiationImmunityHack,VaygrCarrierHealthUpgrade,MakaanCarrierHealth,MakaanDestroyerHealth,MakaanShipyardHealth,MakaanBattleCruiserHealth,MakaanFrigateHealth,MakaanCorvetteHealth,MakaanFighterHealth,MakaanUtilityHealth,MakaanPlatformHealth,StrongerGunPlats,StrongerMissilePlats",
}
